# Generated by Django 6.0.1 on 2026-01-13 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic Versioning, z.B. 1.0.0",
                        max_length=20,
                        unique=True,
                        verbose_name="Version",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "content",
                    models.TextField(
                        help_text="Unterstützt Markdown-Formatierung. Nutze Listen für Änderungen.",
                        verbose_name="Changelog",
                    ),
                ),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("major", "Major Release"),
                            ("minor", "Minor Release"),
                            ("patch", "Patch/Bugfix"),
                        ],
                        default="minor",
                        max_length=20,
                        verbose_name="Release-Typ",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Release-Datum"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Veröffentlicht"),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="Link zum GitHub Release",
                        verbose_name="GitHub Release URL",
                    ),
                ),
                (
                    "breaking_changes",
                    models.BooleanField(
                        default=False,
                        help_text="Enthält inkompatible Änderungen",
                        verbose_name="Breaking Changes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Release",
                "verbose_name_plural": "Releases",
                "ordering": ["-release_date", "-version"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL-Slug"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Kurze Zusammenfassung für die Übersicht (max. 500 Zeichen)",
                        max_length=500,
                        verbose_name="Kurzbeschreibung",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Unterstützt Markdown-Formatierung",
                        verbose_name="Inhalt",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "Neuigkeiten"),
                            ("tutorial", "Tutorial"),
                            ("update", "Update"),
                            ("community", "Community"),
                            ("tech", "Technik"),
                        ],
                        default="news",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Entwurf"), ("published", "Veröffentlicht")],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/images/",
                        verbose_name="Beitragsbild",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bild-Alternativtext"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Veröffentlicht am"),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Für Suchmaschinen (max. 160 Zeichen)",
                        max_length=160,
                        verbose_name="Meta-Beschreibung",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog-Artikel",
                "verbose_name_plural": "Blog-Artikel",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
