# Generated by Django 6.0.1 on 2026-01-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_backend",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Leer lassen für Standardwert aus Umgebungsvariablen",
                        max_length=200,
                        verbose_name="E-Mail Backend",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True,
                        help_text="z.B. smtp.gmail.com oder mail.example.de",
                        max_length=255,
                        verbose_name="SMTP Host",
                    ),
                ),
                (
                    "email_port",
                    models.PositiveIntegerField(
                        default=587,
                        help_text="Standardport: 587 (TLS) oder 465 (SSL)",
                        verbose_name="SMTP Port",
                    ),
                ),
                (
                    "email_host_user",
                    models.CharField(blank=True, max_length=255, verbose_name="SMTP Benutzername"),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True,
                        help_text="Wird verschlüsselt gespeichert",
                        max_length=255,
                        verbose_name="SMTP Passwort",
                    ),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(
                        default=True,
                        help_text="STARTTLS (Port 587)",
                        verbose_name="TLS verwenden",
                    ),
                ),
                (
                    "email_use_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Implizites SSL (Port 465)",
                        verbose_name="SSL verwenden",
                    ),
                ),
                (
                    "email_timeout",
                    models.PositiveIntegerField(default=30, verbose_name="Timeout (Sekunden)"),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True,
                        help_text="z.B. noreply@mandari.de",
                        max_length=254,
                        verbose_name="Standard-Absender",
                    ),
                ),
                (
                    "default_from_name",
                    models.CharField(
                        blank=True,
                        default="Mandari",
                        help_text="z.B. 'Mandari System'",
                        max_length=255,
                        verbose_name="Absender-Name",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Mandari", max_length=100, verbose_name="Seitenname"),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        default="Kommunalpolitische Transparenz",
                        verbose_name="Seitenbeschreibung",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Website für Besucher sperren",
                        verbose_name="Wartungsmodus",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="Die Website wird gerade gewartet. Bitte versuchen Sie es später erneut.",
                        verbose_name="Wartungsnachricht",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Systemeinstellungen",
                "verbose_name_plural": "Systemeinstellungen",
            },
        ),
    ]
