# Generated by Django 6.0.1 on 2026-02-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="nebius_api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key für Nebius TokenFactory (KI-Zusammenfassungen)",
                max_length=255,
                verbose_name="Nebius API Key",
            ),
        ),
    ]
