# Generated by Django 6.0.6 on 2026-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_add_nebius_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Globaler Schalter für den KI-Assistenten im Dokumenten-Editor.",
                        verbose_name="KI aktiviert",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI"),
                            ("mistral", "Mistral"),
                            ("nebius", "Nebius TokenFactory"),
                            ("ovh", "OVHcloud AI Endpoints"),
                            ("ionos", "IONOS AI Model Hub"),
                        ],
                        default="nebius",
                        max_length=20,
                        verbose_name="KI-Anbieter",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Leer lassen für den Anbieter-Standard (OpenAI-kompatible Endpunkte bzw. Anthropic Messages API).",
                        verbose_name="API Base URL",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="openai/gpt-oss-120b",
                        help_text="z.B. openai/gpt-oss-120b (Nebius), gpt-4o-mini (OpenAI), claude-sonnet-4-5 (Anthropic), mistral-small-latest (Mistral).",
                        max_length=100,
                        verbose_name="Modell",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.BinaryField(
                        blank=True,
                        help_text="AES-256-GCM verschlüsselt mit dem ENCRYPTION_MASTER_KEY.",
                        null=True,
                        verbose_name="API Key (verschlüsselt)",
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Obergrenze für die Antwortlänge pro KI-Aufruf.",
                        verbose_name="Max. Output-Tokens",
                    ),
                ),
                (
                    "default_org_monthly_token_limit",
                    models.PositiveIntegerField(
                        default=3000000,
                        help_text="Gilt für Organisationen ohne eigenes Monatslimit. Pro Organisation überschreibbar über Organization → 'Token-Limit pro Monat' (leer = dieser Standard, 0 = KI deaktiviert).",
                        verbose_name="Standard-Monatslimit pro Organisation (Tokens)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KI-Einstellungen",
                "verbose_name_plural": "KI-Einstellungen",
            },
        ),
    ]
