# Generated by Django 5.2.11 on 2026-09-02 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_add_ai_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Ticket-Nr."
                    ),
                ),
                (
                    "error_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Fehler-ID"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Betroffene Seite"
                    ),
                ),
                ("message", models.TextField(verbose_name="Beschreibung")),
                (
                    "browser_info",
                    models.TextField(blank=True, verbose_name="Browser-Informationen"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="E-Mail für Rückmeldung",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-Adresse"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("in_progress", "In Bearbeitung"),
                            ("resolved", "Gelöst"),
                            ("closed", "Geschlossen"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True,
                        help_text="Wird beim Lösen des Tickets per E-Mail mitgeschickt",
                        verbose_name="Rückmeldung an die meldende Person",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöst am"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rückmeldung versandt am"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eingegangen am"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fehlermeldung",
                "verbose_name_plural": "Fehlermeldungen",
                "ordering": ["-created_at"],
            },
        ),
    ]
