# Generated by Django 6.1.1 on 2026-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_fehlermeldungen"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "scope",
                    models.CharField(
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "last_seq",
                    models.BigIntegerField(
                        default=0, verbose_name="Letzte laufende Nummer"
                    ),
                ),
                (
                    "last_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Hash des letzten Eintrags",
                    ),
                ),
                (
                    "initialized",
                    models.BooleanField(
                        default=False,
                        help_text="Aus, solange Altbestand noch nicht verkettet ist (audit_chain_backfill)",
                        verbose_name="Verkettung aktiv",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verkettet seit"
                    ),
                ),
                (
                    "anchor_seq",
                    models.BigIntegerField(
                        default=0, verbose_name="Anker: letzte gelöschte Nummer"
                    ),
                ),
                (
                    "anchor_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Anker: Hash des letzten gelöschten Eintrags",
                    ),
                ),
                (
                    "anchor_archive",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Anker: Archivpaket"
                    ),
                ),
                (
                    "anchor_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Anker gesetzt am"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Protokoll-Kettenkopf",
                "verbose_name_plural": "Protokoll-Kettenköpfe",
            },
        ),
    ]
