# Generated by Django 6.0.1 on 2026-01-19 22:00

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Kurzname"),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("committee", "Ausschuss"),
                            ("council", "Rat"),
                            ("faction", "Fraktion"),
                            ("advisory", "Beirat"),
                            ("commission", "Kommission"),
                            ("other", "Sonstiges"),
                        ],
                        default="committee",
                        max_length=100,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "default_meeting_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Standardort für Sitzungen",
                    ),
                ),
                (
                    "default_meeting_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Standardzeit für Sitzungen"
                    ),
                ),
                (
                    "allowance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Sitzungsgeld",
                    ),
                ),
                (
                    "allowance_currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="Währung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Startdatum"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Enddatum"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oparl_organization",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_organization",
                        to="insight_core.oparlorganization",
                        verbose_name="OParl-Gremium",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="session.sessionorganization",
                        verbose_name="Übergeordnetes Gremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gremium",
                "verbose_name_plural": "Gremien",
                "db_table": "session_organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SessionMeeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                ("start", models.DateTimeField(verbose_name="Beginn")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tatsächlicher Beginn"
                    ),
                ),
                (
                    "actual_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Tatsächliches Ende"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=500, verbose_name="Ort"),
                ),
                (
                    "room",
                    models.CharField(blank=True, max_length=100, verbose_name="Raum"),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, verbose_name="Straße"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
                ),
                (
                    "locality",
                    models.CharField(blank=True, max_length=100, verbose_name="Stadt"),
                ),
                (
                    "meeting_state",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("scheduled", "Geplant"),
                            ("invitation_sent", "Einladung versandt"),
                            ("in_progress", "Laufend"),
                            ("completed", "Abgeschlossen"),
                            ("cancelled", "Abgesagt"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cancelled",
                    models.BooleanField(default=False, verbose_name="Abgesagt"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Absagegrund"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Wird über OParl-API veröffentlicht",
                        verbose_name="Öffentlich",
                    ),
                ),
                (
                    "internal_notes_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Interne Notizen"),
                ),
                (
                    "invitation_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Einladung versandt am"
                    ),
                ),
                (
                    "invitation_text",
                    models.TextField(blank=True, verbose_name="Einladungstext"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oparl_meeting",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_meeting",
                        to="insight_core.oparlmeeting",
                        verbose_name="OParl-Sitzung",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="session.sessionorganization",
                        verbose_name="Gremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzung",
                "verbose_name_plural": "Sitzungen",
                "db_table": "session_meetings",
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="SessionApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Wird automatisch vergeben",
                        max_length=100,
                        verbose_name="Eingangsnummer",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titel")),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("motion", "Antrag"),
                            ("inquiry", "Anfrage"),
                            ("resolution", "Resolution"),
                            ("urgent", "Dringlichkeitsantrag"),
                            ("amendment", "Änderungsantrag"),
                            ("other", "Sonstiges"),
                        ],
                        default="motion",
                        max_length=100,
                        verbose_name="Art des Antrags",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Warum soll dieser Antrag beschlossen werden?",
                        verbose_name="Begründung",
                    ),
                ),
                (
                    "resolution_proposal",
                    models.TextField(
                        help_text="Was genau soll beschlossen werden?",
                        verbose_name="Beschlussvorschlag",
                    ),
                ),
                (
                    "financial_impact",
                    models.TextField(
                        blank=True,
                        help_text="Welche Kosten entstehen? (optional)",
                        verbose_name="Finanzielle Auswirkungen",
                    ),
                ),
                (
                    "additional_info_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Zusätzliche vertrauliche Informationen"
                    ),
                ),
                (
                    "submitter_name",
                    models.CharField(max_length=255, verbose_name="Name des Einreichers"),
                ),
                (
                    "submitter_email",
                    models.EmailField(max_length=254, verbose_name="E-Mail des Einreichers"),
                ),
                (
                    "submitter_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Telefon des Einreichers",
                    ),
                ),
                (
                    "co_signers",
                    models.TextField(
                        blank=True,
                        help_text="Namen der Mitunterzeichner (einer pro Zeile)",
                        verbose_name="Mitunterzeichner",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Eingereicht"),
                            ("received", "Eingegangen"),
                            ("in_review", "In Prüfung"),
                            ("accepted", "Angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("converted", "In Vorlage umgewandelt"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="submitted",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Eingegangen am"),
                ),
                (
                    "processing_notes",
                    models.TextField(blank=True, verbose_name="Bearbeitungsnotizen"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False,
                        help_text="Soll der Antrag bevorzugt behandelt werden?",
                        verbose_name="Dringend",
                    ),
                ),
                (
                    "urgency_reason",
                    models.TextField(blank=True, verbose_name="Begründung der Dringlichkeit"),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Bis wann soll der Antrag behandelt werden?",
                        null=True,
                        verbose_name="Gewünschter Beratungstermin",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Eingereicht am"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitting_organization",
                    models.ForeignKey(
                        help_text="Fraktion/Partei, die den Antrag einreicht",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_applications",
                        to="tenants.organization",
                        verbose_name="Einreichende Organisation",
                    ),
                ),
                (
                    "target_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="An welches Gremium soll der Antrag gehen?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_applications",
                        to="session.sessionorganization",
                        verbose_name="Zielgremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antrag",
                "verbose_name_plural": "Anträge",
                "db_table": "session_applications",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="z.B. V/2024/0001",
                        max_length=100,
                        verbose_name="Aktenzeichen",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Betreff")),
                (
                    "paper_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Beschlussvorlage"),
                            ("report", "Mitteilungsvorlage"),
                            ("motion", "Antrag"),
                            ("inquiry", "Anfrage"),
                            ("resolution", "Resolution"),
                            ("bylaw", "Satzung"),
                            ("budget", "Haushalt"),
                            ("other", "Sonstiges"),
                        ],
                        default="proposal",
                        max_length=100,
                        verbose_name="Vorlagenart",
                    ),
                ),
                ("main_text", models.TextField(blank=True, verbose_name="Sachverhalt")),
                (
                    "resolution_text",
                    models.TextField(blank=True, verbose_name="Beschlussvorschlag"),
                ),
                (
                    "confidential_text_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Vertraulicher Inhalt"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Wird über OParl-API veröffentlicht",
                        verbose_name="Öffentlich",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("review", "In Prüfung"),
                            ("approved", "Freigegeben"),
                            ("scheduled", "Terminiert"),
                            ("completed", "Abgeschlossen"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Datum")),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Frist"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Freigegeben am"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_papers",
                        to="session.sessionorganization",
                        verbose_name="Federführendes Gremium",
                    ),
                ),
                (
                    "oparl_paper",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_paper",
                        to="insight_core.oparlpaper",
                        verbose_name="OParl-Vorlage",
                    ),
                ),
                (
                    "originator_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originated_papers",
                        to="session.sessionorganization",
                        verbose_name="Einreichendes Gremium",
                    ),
                ),
                (
                    "source_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_papers",
                        to="session.sessionapplication",
                        verbose_name="Ursprungsantrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorlage",
                "verbose_name_plural": "Vorlagen",
                "db_table": "session_papers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionAgendaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="TOP-Nr.")),
                ("name", models.CharField(max_length=500, verbose_name="Betreff")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Öffentlich"),
                ),
                (
                    "resolution_text",
                    models.TextField(blank=True, verbose_name="Beschlusstext"),
                ),
                (
                    "resolution_text_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Nicht-öffentlicher Beschlusstext"
                    ),
                ),
                (
                    "vote_result",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("deferred", "Vertagt"),
                            ("withdrawn", "Zurückgezogen"),
                            ("noted", "Zur Kenntnis genommen"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Abstimmungsergebnis",
                    ),
                ),
                (
                    "votes_yes",
                    models.PositiveIntegerField(default=0, verbose_name="Ja-Stimmen"),
                ),
                (
                    "votes_no",
                    models.PositiveIntegerField(default=0, verbose_name="Nein-Stimmen"),
                ),
                (
                    "votes_abstain",
                    models.PositiveIntegerField(default=0, verbose_name="Enthaltungen"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Beginn"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oparl_agenda_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_agenda_item",
                        to="insight_core.oparlagendaitem",
                        verbose_name="OParl-TOP",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agenda_items",
                        to="session.sessionpaper",
                        verbose_name="Vorlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagesordnungspunkt",
                "verbose_name_plural": "Tagesordnungspunkte",
                "db_table": "session_agenda_items",
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="SessionPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=50, verbose_name="Titel"),
                ),
                (
                    "given_name",
                    models.CharField(max_length=100, verbose_name="Vorname"),
                ),
                (
                    "family_name",
                    models.CharField(max_length=100, verbose_name="Nachname"),
                ),
                (
                    "form_of_address",
                    models.CharField(blank=True, max_length=50, verbose_name="Anrede"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="E-Mail"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "bank_account_holder",
                    models.CharField(blank=True, max_length=255, verbose_name="Kontoinhaber"),
                ),
                (
                    "bank_iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "bank_bic",
                    models.CharField(blank=True, max_length=11, verbose_name="BIC"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Mandatsbeginn"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Mandatsende"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oparl_person",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_person",
                        to="insight_core.oparlperson",
                        verbose_name="OParl-Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
                "db_table": "session_persons",
                "ordering": ["family_name", "given_name"],
            },
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="originator_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originated_papers",
                to="session.sessionperson",
                verbose_name="Einreichende Person",
            ),
        ),
        migrations.CreateModel(
            name="SessionOrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Mitglied"),
                            ("chair", "Vorsitzende/r"),
                            ("deputy_chair", "Stellv. Vorsitzende/r"),
                            ("advisor", "Beratendes Mitglied"),
                            ("guest", "Gast"),
                        ],
                        default="member",
                        max_length=100,
                        verbose_name="Funktion",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Von"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Bis"),
                ),
                (
                    "has_voting_rights",
                    models.BooleanField(default=True, verbose_name="Stimmberechtigt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="session.sessionorganization",
                        verbose_name="Gremium",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gremienmitgliedschaft",
                "verbose_name_plural": "Gremienmitgliedschaften",
                "db_table": "session_organization_memberships",
                "unique_together": {("organization", "person", "start_date")},
            },
        ),
        migrations.AddField(
            model_name="sessionorganization",
            name="members",
            field=models.ManyToManyField(
                related_name="organizations",
                through="session.SessionOrganizationMembership",
                to="session.sessionperson",
                verbose_name="Mitglieder",
            ),
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Eingeladen"),
                            ("confirmed", "Zugesagt"),
                            ("declined", "Abgesagt"),
                            ("present", "Anwesend"),
                            ("absent", "Abwesend"),
                            ("excused", "Entschuldigt"),
                            ("left_early", "Vorzeitig gegangen"),
                            ("joined_late", "Verspätet"),
                        ],
                        default="invited",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(blank=True, null=True, verbose_name="Ankunft"),
                ),
                (
                    "departure_time",
                    models.TimeField(blank=True, null=True, verbose_name="Abgang"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "excuse_reason",
                    models.TextField(blank=True, verbose_name="Entschuldigungsgrund"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Mitglied"),
                            ("chair", "Vorsitz"),
                            ("deputy_chair", "Stellv. Vorsitz"),
                            ("guest", "Gast"),
                            ("expert", "Sachverständige/r"),
                            ("recorder", "Protokollant/in"),
                        ],
                        default="member",
                        max_length=50,
                        verbose_name="Funktion",
                    ),
                ),
                (
                    "has_voting_rights",
                    models.BooleanField(default=True, verbose_name="Stimmberechtigt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anwesenheit",
                "verbose_name_plural": "Anwesenheiten",
                "db_table": "session_attendances",
                "ordering": ["person__family_name"],
                "unique_together": {("meeting", "person")},
            },
        ),
        migrations.CreateModel(
            name="SessionTenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL-Slug"),
                ),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Kurzname"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="session/tenants/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(default="#1e40af", max_length=7, verbose_name="Primärfarbe"),
                ),
                (
                    "secondary_color",
                    models.CharField(default="#3b82f6", max_length=7, verbose_name="Sekundärfarbe"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Kontakt-E-Mail"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "encryption_key",
                    models.BinaryField(
                        blank=True,
                        help_text="AES-256 Schlüssel, verschlüsselt mit Master-Key",
                        null=True,
                        verbose_name="Verschlüsselungsschlüssel",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Einstellungen"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oparl_body",
                    models.OneToOneField(
                        blank=True,
                        help_text="Verknüpfung zur öffentlichen OParl-Schnittstelle",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_tenant",
                        to="insight_core.oparlbody",
                        verbose_name="OParl-Kommune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session-Mandant",
                "verbose_name_plural": "Session-Mandanten",
                "db_table": "session_tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SessionRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "can_view_dashboard",
                    models.BooleanField(default=True, verbose_name="Dashboard anzeigen"),
                ),
                (
                    "can_view_meetings",
                    models.BooleanField(default=True, verbose_name="Sitzungen anzeigen"),
                ),
                (
                    "can_create_meetings",
                    models.BooleanField(default=False, verbose_name="Sitzungen erstellen"),
                ),
                (
                    "can_edit_meetings",
                    models.BooleanField(default=False, verbose_name="Sitzungen bearbeiten"),
                ),
                (
                    "can_delete_meetings",
                    models.BooleanField(default=False, verbose_name="Sitzungen löschen"),
                ),
                (
                    "can_view_non_public_meetings",
                    models.BooleanField(
                        default=False,
                        verbose_name="Nicht-öffentliche Sitzungen anzeigen",
                    ),
                ),
                (
                    "can_view_papers",
                    models.BooleanField(default=True, verbose_name="Vorlagen anzeigen"),
                ),
                (
                    "can_create_papers",
                    models.BooleanField(default=False, verbose_name="Vorlagen erstellen"),
                ),
                (
                    "can_edit_papers",
                    models.BooleanField(default=False, verbose_name="Vorlagen bearbeiten"),
                ),
                (
                    "can_delete_papers",
                    models.BooleanField(default=False, verbose_name="Vorlagen löschen"),
                ),
                (
                    "can_approve_papers",
                    models.BooleanField(default=False, verbose_name="Vorlagen freigeben"),
                ),
                (
                    "can_view_non_public_papers",
                    models.BooleanField(
                        default=False,
                        verbose_name="Nicht-öffentliche Vorlagen anzeigen",
                    ),
                ),
                (
                    "can_view_applications",
                    models.BooleanField(default=True, verbose_name="Anträge anzeigen"),
                ),
                (
                    "can_process_applications",
                    models.BooleanField(default=False, verbose_name="Anträge bearbeiten"),
                ),
                (
                    "can_view_protocols",
                    models.BooleanField(default=True, verbose_name="Protokolle anzeigen"),
                ),
                (
                    "can_create_protocols",
                    models.BooleanField(default=False, verbose_name="Protokolle erstellen"),
                ),
                (
                    "can_edit_protocols",
                    models.BooleanField(default=False, verbose_name="Protokolle bearbeiten"),
                ),
                (
                    "can_approve_protocols",
                    models.BooleanField(default=False, verbose_name="Protokolle freigeben"),
                ),
                (
                    "can_manage_attendance",
                    models.BooleanField(default=False, verbose_name="Anwesenheit verwalten"),
                ),
                (
                    "can_manage_allowances",
                    models.BooleanField(default=False, verbose_name="Sitzungsgelder verwalten"),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(default=False, verbose_name="Benutzer verwalten"),
                ),
                (
                    "can_manage_organizations",
                    models.BooleanField(default=False, verbose_name="Gremien verwalten"),
                ),
                (
                    "can_manage_settings",
                    models.BooleanField(default=False, verbose_name="Einstellungen verwalten"),
                ),
                (
                    "can_view_audit_log",
                    models.BooleanField(default=False, verbose_name="Audit-Log anzeigen"),
                ),
                (
                    "can_access_api",
                    models.BooleanField(default=False, verbose_name="API-Zugang"),
                ),
                (
                    "can_access_oparl_api",
                    models.BooleanField(default=True, verbose_name="OParl-API-Zugang"),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Hat alle Berechtigungen",
                        verbose_name="Administrator",
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="Kann nicht gelöscht werden",
                        verbose_name="Systemrolle",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=50, verbose_name="Priorität"),
                ),
                (
                    "color",
                    models.CharField(default="#6b7280", max_length=7, verbose_name="Farbe"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session-Rolle",
                "verbose_name_plural": "Session-Rollen",
                "db_table": "session_roles",
                "ordering": ["-priority", "name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.AddField(
            model_name="sessionperson",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons",
                to="session.sessiontenant",
                verbose_name="Mandant",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="session.sessiontenant",
                verbose_name="Mandant",
            ),
        ),
        migrations.AddField(
            model_name="sessionorganization",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="session.sessiontenant",
                verbose_name="Mandant",
            ),
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="session.sessiontenant",
                verbose_name="Mandant",
            ),
        ),
        migrations.AddField(
            model_name="sessionapplication",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="session.sessiontenant",
                verbose_name="Mandant",
            ),
        ),
        migrations.CreateModel(
            name="SessionUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Einstellungen"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Beigetreten"),
                ),
                (
                    "last_access",
                    models.DateTimeField(blank=True, null=True, verbose_name="Letzter Zugriff"),
                ),
                (
                    "oparl_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_users",
                        to="insight_core.oparlperson",
                        verbose_name="OParl-Person",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="session.sessionrole",
                        verbose_name="Rollen",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session-Benutzer",
                "verbose_name_plural": "Session-Benutzer",
                "db_table": "session_users",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="SessionProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Protokollinhalt"),
                ),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Nicht-öffentlicher Protokollinhalt"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("review", "Zur Prüfung"),
                            ("approved", "Genehmigt"),
                            ("published", "Veröffentlicht"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Genehmigt am"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_protocols",
                        to="session.sessionuser",
                        verbose_name="Genehmigt von",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_protocols",
                        to="session.sessionuser",
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokoll",
                "verbose_name_plural": "Protokolle",
                "db_table": "session_protocols",
            },
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_papers",
                to="session.sessionuser",
                verbose_name="Freigegeben von",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_papers",
                to="session.sessionuser",
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_meetings",
                to="session.sessionuser",
                verbose_name="Erstellt von",
            ),
        ),
        migrations.CreateModel(
            name="SessionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                (
                    "file",
                    models.FileField(upload_to="session/files/%Y/%m/", verbose_name="Datei"),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, max_length=100, verbose_name="MIME-Typ"),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(default=0, verbose_name="Größe (Bytes)"),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Textinhalt"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Öffentlich"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="session.sessionagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "oparl_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_file",
                        to="insight_core.oparlfile",
                        verbose_name="OParl-Datei",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="session.sessionpaper",
                        verbose_name="Vorlage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to="session.sessionuser",
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datei",
                "verbose_name_plural": "Dateien",
                "db_table": "session_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sessionapplication",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_applications",
                to="session.sessionuser",
                verbose_name="Bearbeitet von",
            ),
        ),
        migrations.CreateModel(
            name="SessionAPIToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Beschreibender Name für den Token",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="SHA-256 Hash des API-Tokens",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        editable=False,
                        help_text="Die ersten 8 Zeichen des Tokens zur Identifikation",
                        max_length=8,
                        verbose_name="Token-Präfix",
                    ),
                ),
                (
                    "can_submit_applications",
                    models.BooleanField(
                        default=True,
                        help_text="Erlaubt das Einreichen von Anträgen",
                        verbose_name="Anträge einreichen",
                    ),
                ),
                (
                    "can_read_meetings",
                    models.BooleanField(
                        default=True,
                        help_text="Erlaubt das Lesen öffentlicher Sitzungsdaten",
                        verbose_name="Sitzungen lesen",
                    ),
                ),
                (
                    "can_read_papers",
                    models.BooleanField(
                        default=True,
                        help_text="Erlaubt das Lesen öffentlicher Vorlagen",
                        verbose_name="Vorlagen lesen",
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Maximale Anzahl von Anfragen pro Minute",
                        verbose_name="Rate-Limit pro Minute",
                    ),
                ),
                (
                    "allowed_ips",
                    models.TextField(
                        blank=True,
                        help_text="Komma-getrennte Liste erlaubter IP-Adressen (leer = alle)",
                        verbose_name="Erlaubte IP-Adressen",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Token läuft zu diesem Zeitpunkt ab (leer = kein Ablauf)",
                        null=True,
                        verbose_name="Ablaufdatum",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Zuletzt verwendet"),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Letzte IP-Adresse"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="Verwendungszähler"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tokens",
                        to="session.sessionuser",
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "API-Token",
                "verbose_name_plural": "API-Tokens",
                "db_table": "session_api_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionAllowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Betrag"),
                ),
                (
                    "currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="Währung"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Genehmigt"),
                            ("paid", "Ausgezahlt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Genehmigt am"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ausgezahlt am"),
                ),
                (
                    "export_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Export-Referenz"),
                ),
                (
                    "export_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Export-Datum"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance",
                        to="session.sessionattendance",
                        verbose_name="Anwesenheit",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_allowances",
                        to="session.sessionuser",
                        verbose_name="Genehmigt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzungsgeld",
                "verbose_name_plural": "Sitzungsgelder",
                "db_table": "session_allowances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="sessionpaper",
            unique_together={("tenant", "reference")},
        ),
        migrations.CreateModel(
            name="SessionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-Adresse"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Erstellt"),
                            ("update", "Geändert"),
                            ("delete", "Gelöscht"),
                            ("view", "Angesehen"),
                            ("download", "Heruntergeladen"),
                            ("approve", "Freigegeben"),
                            ("publish", "Veröffentlicht"),
                            ("login", "Anmeldung"),
                            ("logout", "Abmeldung"),
                        ],
                        max_length=50,
                        verbose_name="Aktion",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modell")),
                ("object_id", models.UUIDField(verbose_name="Objekt-ID")),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Objekt-Beschreibung"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, default=dict, verbose_name="Änderungen"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="session.sessionuser",
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit-Eintrag",
                "verbose_name_plural": "Audit-Log",
                "db_table": "session_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "model_name", "object_id"],
                        name="session_aud_tenant__406cc1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "user", "created_at"],
                        name="session_aud_tenant__9949ae_idx",
                    ),
                ],
            },
        ),
    ]
