# Generated by Django 5.2.11 on 2026-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0003_antragsarten_und_eingangsnummern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Erstellt"),
                    ("update", "Geändert"),
                    ("delete", "Gelöscht"),
                    ("view", "Angesehen"),
                    ("download", "Heruntergeladen"),
                    ("approve", "Freigegeben"),
                    ("publish", "Veröffentlicht"),
                    ("invitation_sent", "Einladung versandt"),
                    ("withdraw", "Abgesetzt"),
                    ("replace", "Ersetzt"),
                    ("login", "Anmeldung"),
                    ("logout", "Abmeldung"),
                ],
                max_length=50,
                verbose_name="Aktion",
            ),
        ),
    ]
