# Generated by Django 5.2.11 on 2026-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0004_audit_log_aktionen"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfile",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Version"),
        ),
    ]
