# Generated by Django 5.2.11 on 2026-07-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0005_sessionfile_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="is_supplementary",
            field=models.BooleanField(
                default=False,
                help_text="Nach Versand der Einladung hinzugefügt (Nachtragstagesordnung)",
                verbose_name="Nachtrag",
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="is_withdrawn",
            field=models.BooleanField(default=False, verbose_name="Abgesetzt"),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_items",
                to="session.sessionagendaitem",
                verbose_name="Übergeordneter TOP",
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="withdrawn_reason",
            field=models.TextField(blank=True, verbose_name="Absetzungsgrund"),
        ),
    ]
