# Generated by Django 5.2.11 on 2026-07-20 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0006_tagesordnung_verwaltung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionorganization",
            name="invitation_period_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Frist zwischen Ladung und Sitzung gemäß Geschäftsordnung",
                verbose_name="Ladungsfrist (Tage)",
            ),
        ),
        migrations.AddField(
            model_name="sessionorganization",
            name="meeting_frequency",
            field=models.CharField(
                blank=True,
                help_text="z. B. monatlich, 6-wöchentlich, nach Bedarf",
                max_length=100,
                verbose_name="Sitzungsturnus",
            ),
        ),
        migrations.AddField(
            model_name="sessionorganization",
            name="target_member_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Mitgliederzahl (Soll)"
            ),
        ),
        migrations.AddField(
            model_name="sessionorganizationmembership",
            name="substitute_for",
            field=models.ForeignKey(
                blank=True,
                help_text="Wird als Stellvertreter/in dieser Person geführt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substituted_by_memberships",
                to="session.sessionperson",
                verbose_name="Vertretung für",
            ),
        ),
        migrations.AlterField(
            model_name="sessionorganization",
            name="members",
            field=models.ManyToManyField(
                related_name="organizations",
                through="session.SessionOrganizationMembership",
                through_fields=("organization", "person"),
                to="session.sessionperson",
                verbose_name="Mitglieder",
            ),
        ),
        migrations.AlterField(
            model_name="sessionorganizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Mitglied"),
                    ("chair", "Vorsitzende/r"),
                    ("deputy_chair", "Stellv. Vorsitzende/r"),
                    ("expert_citizen", "Sachkundige/r Bürger/in"),
                    ("advisor", "Beratendes Mitglied"),
                    ("guest", "Gast"),
                ],
                default="member",
                max_length=100,
                verbose_name="Funktion",
            ),
        ),
        migrations.CreateModel(
            name="SessionInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Gültig bis")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Angenommen am"
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_session_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Angenommen von",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to="session.sessionuser",
                        verbose_name="Eingeladen von",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invitations",
                        to="session.sessionrole",
                        verbose_name="Rollen",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session-Einladung",
                "verbose_name_plural": "Session-Einladungen",
                "db_table": "session_invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
