# Generated by Django 5.2.11 on 2026-07-20 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0007_stammdaten_benutzer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionInvitationDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dispatch_type",
                    models.CharField(
                        choices=[
                            ("invitation", "Ladung"),
                            ("supplementary", "Nachladung/Nachtrag"),
                        ],
                        default="invitation",
                        max_length=20,
                        verbose_name="Versandart",
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Betreff")),
                ("message", models.TextField(blank=True, verbose_name="Anschreiben")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Versandt am"),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_dispatches",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_dispatches",
                        to="session.sessionuser",
                        verbose_name="Versandt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ladungsversand",
                "verbose_name_plural": "Ladungsversände",
                "db_table": "session_invitation_dispatches",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionInvitationRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "membership_role",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Funktion"
                    ),
                ),
                (
                    "includes_non_public",
                    models.BooleanField(
                        default=False, verbose_name="Inkl. nichtöffentlicher Teil"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Versandt"), ("failed", "Fehlgeschlagen")],
                        default="sent",
                        max_length=20,
                        verbose_name="Zustellstatus",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Fehler")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="session.sessioninvitationdispatch",
                        verbose_name="Versand",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_receipts",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ladungsempfänger",
                "verbose_name_plural": "Ladungsempfänger",
                "db_table": "session_invitation_recipients",
                "ordering": ["name"],
            },
        ),
    ]
