# Generated by Django 5.2.11 on 2026-07-20 19:08

import apps.common.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0008_ladungsversand"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="protocol_note",
            field=models.TextField(
                blank=True,
                help_text="Wortbeiträge/Beratungsverlauf zu diesem TOP (öffentlicher Teil der Niederschrift)",
                verbose_name="Protokolltext",
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="protocol_note_encrypted",
            field=apps.common.encryption.EncryptedTextField(
                verbose_name="Nicht-öffentlicher Protokolltext"
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="approval_meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Folgesitzung, in der die Niederschrift genehmigt wurde",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_protocols",
                to="session.sessionmeeting",
                verbose_name="Genehmigt in Sitzung",
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="approval_note",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Genehmigungsvermerk"
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="chair_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Vorsitz (Unterschrift)"
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Veröffentlicht am"
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="recorder_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Protokollführung (Unterschrift)",
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="review_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zur Prüfung gegeben am"
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="review_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_protocols",
                to="session.sessionuser",
                verbose_name="Zur Prüfung gegeben von",
            ),
        ),
    ]
