# Generated by Django 5.2.11 on 2026-07-20 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0009_niederschrift_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="resolution_number",
            field=models.CharField(
                blank=True,
                help_text="Wird bei der Beschlussausfertigung vergeben, z. B. B/2026/0012",
                max_length=50,
                verbose_name="Beschlussnummer",
            ),
        ),
        migrations.CreateModel(
            name="SessionResolutionForwarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="z. B. Bauamt, Kämmerei, externe Stelle",
                        max_length=255,
                        verbose_name="Zuständige Stelle/Amt",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email", "E-Mail"),
                            ("internal", "Interner Geschäftsgang"),
                            ("mail", "Postweg"),
                            ("handover", "Persönliche Übergabe"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="Übergabeweg",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Vermerk")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Übergeben am"
                    ),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forwardings",
                        to="session.sessionagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_forwardings",
                        to="session.sessionuser",
                        verbose_name="Übergeben von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beschlussauszug-Übergabe",
                "verbose_name_plural": "Beschlussauszug-Übergaben",
                "db_table": "session_resolution_forwardings",
                "ordering": ["-sent_at"],
            },
        ),
    ]
