# Generated by Django 5.2.11 on 2026-07-21 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0010_beschlussregister"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("preliminary", "Vorberatung"),
                            ("hearing", "Anhörung"),
                            ("decision", "Entscheidung"),
                            ("information", "Kenntnisnahme"),
                        ],
                        default="preliminary",
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "authoritative",
                    models.BooleanField(
                        default=False,
                        help_text="OParl: authoritative — die Station, die abschließend entscheidet",
                        verbose_name="Entscheidende Beratung",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Reihenfolge"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("deferred", "Vertagt"),
                            ("withdrawn", "Zurückgezogen"),
                            ("noted", "Zur Kenntnis genommen"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Ergebnis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation",
                        to="session.sessionagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zielsitzung dieser Beratungsstation (sobald terminiert)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="session.sessionorganization",
                        verbose_name="Gremium",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="session.sessionpaper",
                        verbose_name="Vorlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beratungsstation",
                "verbose_name_plural": "Beratungsfolge",
                "db_table": "session_consultations",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
