# Generated by Django 5.2.11 on 2026-07-21 12:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0011_beratungsfolge"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionLegislativeTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z. B. Wahlperiode 2025–2030",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Beginn"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Ende"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legislative_terms",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wahlperiode",
                "verbose_name_plural": "Wahlperioden",
                "db_table": "session_legislative_terms",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="SessionOParlTombstone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "oparl_type",
                    models.CharField(max_length=50, verbose_name="Objekttyp"),
                ),
                ("object_id", models.UUIDField(verbose_name="Objekt-ID")),
                (
                    "object_created_at",
                    models.DateTimeField(verbose_name="Objekt erstellt am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oparl_tombstones",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "OParl-Tombstone",
                "verbose_name_plural": "OParl-Tombstones",
                "db_table": "session_oparl_tombstones",
                "indexes": [
                    models.Index(
                        fields=["tenant", "oparl_type", "deleted_at"],
                        name="session_opa_tenant__6e2730_idx",
                    )
                ],
                "unique_together": {("tenant", "oparl_type", "object_id")},
            },
        ),
    ]
