# Generated by Django 5.2.11 on 2026-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0012_oparl_spec_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="insight_publish",
            field=models.BooleanField(
                default=False,
                help_text="Registriert die OParl-API dieses Mandanten als Quelle für das Insight-Bürgerportal",
                verbose_name="Im Bürgerportal veröffentlichen",
            ),
        ),
    ]
