# Generated by Django 5.2.11 on 2026-07-23 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0013_insight_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmeeting",
            name="legislative_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings",
                to="session.sessionlegislativeterm",
                verbose_name="Wahlperiode",
            ),
        ),
        migrations.AddField(
            model_name="sessionorganizationmembership",
            name="legislative_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="session.sessionlegislativeterm",
                verbose_name="Wahlperiode",
            ),
        ),
    ]
