# Generated by Django 5.2.11 on 2026-07-23 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0015_wahlperioden_bestandsdaten"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionallowance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_allowances",
                to="session.sessionuser",
                verbose_name="Erzeugt von",
            ),
        ),
        migrations.CreateModel(
            name="SessionAllowanceRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Mitglied"),
                            ("chair", "Vorsitz"),
                            ("deputy_chair", "Stellv. Vorsitz"),
                            ("expert", "Sachverständige/r"),
                            ("recorder", "Protokollant/in"),
                        ],
                        default="member",
                        max_length=50,
                        verbose_name="Funktion",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Betrag"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Währung"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_rates",
                        to="session.sessionorganization",
                        verbose_name="Gremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entschädigungssatz",
                "verbose_name_plural": "Entschädigungssätze",
                "db_table": "session_allowance_rates",
                "ordering": ["organization__name", "role"],
                "unique_together": {("organization", "role")},
            },
        ),
    ]
