# Generated by Django 5.2.11 on 2026-08-31 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0016_sitzungsgeld_saetze_und_lauf"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Erledigungsfrist"
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_note",
            field=models.TextField(blank=True, verbose_name="Erledigungsvermerk"),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_recipient",
            field=models.CharField(
                blank=True,
                help_text="z. B. Bauamt, Kämmerei",
                max_length=255,
                verbose_name="Zuständige Stelle/Amt",
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("in_progress", "In Umsetzung"),
                    ("done", "Erledigt"),
                    ("deferred", "Zurückgestellt"),
                ],
                default="open",
                max_length=20,
                verbose_name="Umsetzungsstand",
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Umsetzung aktualisiert am"
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolution_tracking_updates",
                to="session.sessionuser",
                verbose_name="Umsetzung aktualisiert von",
            ),
        ),
    ]
