# Generated by Django 5.2.11 on 2026-08-31 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0017_beschlusskontrolle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="reminder_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Abweichungen von den Standard-Vorlaufzeiten für Fristen-Erinnerungen",
                verbose_name="Erinnerungs-Einstellungen",
            ),
        ),
        migrations.CreateModel(
            name="SessionReminderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("invitation_upcoming", "Ladungsfrist läuft ab"),
                            ("invitation_overdue", "Ladungsfrist verstrichen"),
                            ("paper_deadline", "Vorlagenfrist läuft ab"),
                            ("attendance_rsvp", "Rückmeldung zur Sitzung fehlt"),
                            ("resolution_followup", "Wiedervorlage Beschlusskontrolle"),
                        ],
                        max_length=40,
                        verbose_name="Erinnerungstyp",
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        help_text="Objekt-/Frist-Bezug, verhindert doppelte Erinnerungen",
                        max_length=255,
                        verbose_name="Deduplizierungs-Schlüssel",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Empfänger"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Versendet am"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erinnerungs-Protokoll",
                "verbose_name_plural": "Erinnerungs-Protokolle",
                "db_table": "session_reminder_logs",
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "kind", "dedup_key"),
                        name="uniq_session_reminder",
                    )
                ],
            },
        ),
    ]
