# Generated by Django 5.2.11 on 2026-08-31 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0018_fristen_erinnerungen"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionStandardAgendaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Betreff")),
                (
                    "placement",
                    models.CharField(
                        choices=[("start", "Am Anfang"), ("end", "Am Ende")],
                        default="start",
                        max_length=10,
                        verbose_name="Position",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Öffentlich"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leer = gilt für alle Gremien",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_agenda_items",
                        to="session.sessionorganization",
                        verbose_name="Gremium",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_agenda_items",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard-Tagesordnungspunkt",
                "verbose_name_plural": "Standard-Tagesordnungspunkte",
                "db_table": "session_standard_agenda_items",
                "ordering": ["placement", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SessionTextBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("content", models.TextField(verbose_name="Text")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("resolution", "Beschlusstext"),
                            ("protocol", "Protokolltext"),
                            ("general", "Allgemein"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_blocks",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Textbaustein",
                "verbose_name_plural": "Textbausteine",
                "db_table": "session_text_blocks",
                "ordering": ["category", "order", "title"],
            },
        ),
    ]
