# Generated by Django 5.2.11 on 2026-09-01 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0019_textbausteine"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionpaper",
            name="financial_impact_note",
            field=models.TextField(
                blank=True,
                help_text="z. B. Höhe, Haushaltsstelle, Deckung",
                verbose_name="Erläuterung der finanziellen Auswirkungen",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="has_financial_impact",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Finanzielle Auswirkungen"
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="lead_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Amt/Fachbereich, das die Vorlage erstellt hat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_papers",
                to="session.sessionorganization",
                verbose_name="Federführendes Amt",
            ),
        ),
        migrations.AddField(
            model_name="sessionuser",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_users",
                to="session.sessionorganization",
                verbose_name="Ämter/Fachbereiche",
            ),
        ),
        migrations.AlterField(
            model_name="sessionorganization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("committee", "Ausschuss"),
                    ("council", "Rat"),
                    ("faction", "Fraktion"),
                    ("advisory", "Beirat"),
                    ("commission", "Kommission"),
                    ("department", "Amt/Fachbereich"),
                    ("other", "Sonstiges"),
                ],
                default="committee",
                max_length=100,
                verbose_name="Typ",
            ),
        ),
        migrations.CreateModel(
            name="SessionCosignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("signed", "Mitgezeichnet"),
                            ("rejected", "Zurückgewiesen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Kommentar")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entschieden am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cosignature_decisions",
                        to="session.sessionuser",
                        verbose_name="Entschieden von",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cosignatures",
                        to="session.sessionorganization",
                        verbose_name="Amt/Fachbereich",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cosignatures",
                        to="session.sessionpaper",
                        verbose_name="Vorlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitzeichnung",
                "verbose_name_plural": "Mitzeichnungen",
                "db_table": "session_cosignatures",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionCosignatureRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "paper_type",
                    models.CharField(
                        blank=True,
                        help_text="Leer = gilt für alle Vorlagenarten",
                        max_length=100,
                        verbose_name="Vorlagenart",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "only_financial",
                    models.BooleanField(
                        default=False,
                        help_text="z. B. Kämmerei: Mitzeichnung nur, wenn die Vorlage finanzielle Auswirkungen hat",
                        verbose_name="Nur bei finanziellen Auswirkungen",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cosignature_rules",
                        to="session.sessionorganization",
                        verbose_name="Amt/Fachbereich",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cosignature_rules",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitzeichnungsregel",
                "verbose_name_plural": "Mitzeichnungsregeln",
                "db_table": "session_cosignature_rules",
                "ordering": ["paper_type", "order"],
            },
        ),
    ]
