# Generated by Django 5.2.11 on 2026-09-01 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0020_aemter_mitzeichnung"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="voting_method",
            field=models.CharField(
                choices=[
                    ("summary", "Nur Summen"),
                    ("open", "Offen (einzeln erfasst)"),
                    ("roll_call", "Namentlich"),
                    ("secret", "Geheim"),
                ],
                default="summary",
                max_length=20,
                verbose_name="Abstimmungsart",
            ),
        ),
        migrations.CreateModel(
            name="SessionCircularResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="z. B. U/2026/0001",
                        max_length=50,
                        verbose_name="Umlauf-Nr.",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Betreff")),
                (
                    "resolution_text",
                    models.TextField(verbose_name="Beschlussvorschlag"),
                ),
                ("deadline", models.DateField(verbose_name="Rückmeldefrist")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Im Umlauf"),
                            ("adopted", "Angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("cancelled", "Abgebrochen"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "result_note",
                    models.TextField(blank=True, verbose_name="Ergebnisvermerk"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Öffentlich"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ergebnis festgestellt am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="circular_resolutions",
                        to="session.sessionuser",
                        verbose_name="Angelegt von",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circular_resolutions",
                        to="session.sessionorganization",
                        verbose_name="Gremium",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="circular_resolutions",
                        to="session.sessionpaper",
                        verbose_name="Vorlage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circular_resolutions",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umlaufbeschluss",
                "verbose_name_plural": "Umlaufbeschlüsse",
                "db_table": "session_circular_resolutions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionCircularVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("yes", "Ja"),
                            ("no", "Nein"),
                            ("abstain", "Enthaltung"),
                        ],
                        max_length=20,
                        verbose_name="Stimme",
                    ),
                ),
                ("received_at", models.DateField(verbose_name="Eingegangen am")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "circular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="session.sessioncircularresolution",
                        verbose_name="Umlaufbeschluss",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circular_votes",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_circular_votes",
                        to="session.sessionuser",
                        verbose_name="Erfasst von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umlauf-Rücklauf",
                "verbose_name_plural": "Umlauf-Rückläufe",
                "db_table": "session_circular_votes",
                "ordering": ["person__family_name", "person__given_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("circular", "person"), name="uniq_session_circular_vote"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("yes", "Ja"),
                            ("no", "Nein"),
                            ("abstain", "Enthaltung"),
                            ("excluded", "Befangen (Mitwirkungsverbot)"),
                            ("not_participating", "Nicht teilgenommen"),
                        ],
                        max_length=20,
                        verbose_name="Stimme",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="session.sessionagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_votes",
                        to="session.sessionuser",
                        verbose_name="Erfasst von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einzelstimme",
                "verbose_name_plural": "Einzelstimmen",
                "db_table": "session_votes",
                "ordering": ["person__family_name", "person__given_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agenda_item", "person"), name="uniq_session_vote"
                    )
                ],
            },
        ),
    ]
