# Generated by Django 5.2.11 on 2026-09-02 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0021_abstimmung_umlauf"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionMonthlyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z. B. Aufwandsentschädigung (Teilpauschale), Zulage Fraktionsvorsitz",
                        max_length=200,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Betrag/Monat"
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        help_text="z. B. § 2 Abs. 1 EntschVO NRW",
                        max_length=200,
                        verbose_name="Rechtsgrundlage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_rates",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monatliche Pauschale",
                "verbose_name_plural": "Monatliche Pauschalen",
                "db_table": "session_monthly_rates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SessionMonthlyAllowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="Jeweils der Monatserste", verbose_name="Monat"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Betrag"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Genehmigt"),
                            ("paid", "Ausgezahlt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Genehmigt am"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ausgezahlt am"
                    ),
                ),
                (
                    "export_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Export-Referenz"
                    ),
                ),
                (
                    "export_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Export-Datum"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_monthly_allowances",
                        to="session.sessionuser",
                        verbose_name="Genehmigt von",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_monthly_allowances",
                        to="session.sessionuser",
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_allowances",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_allowances",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allowances",
                        to="session.sessionmonthlyrate",
                        verbose_name="Pauschale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monats-Pauschale",
                "verbose_name_plural": "Monats-Pauschalen",
                "db_table": "session_monthly_allowances",
                "ordering": ["-period", "person__family_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "rate", "period"),
                        name="uniq_session_monthly_allowance",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionPersonMonthlyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Von"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Bis"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_rates",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="session.sessionmonthlyrate",
                        verbose_name="Pauschale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pauschalen-Zuordnung",
                "verbose_name_plural": "Pauschalen-Zuordnungen",
                "db_table": "session_person_monthly_rates",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "rate"),
                        name="uniq_session_person_monthly_rate",
                    )
                ],
            },
        ),
    ]
