# Generated by Django 5.2.11 on 2026-09-02 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0022_monatspauschalen"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionrole",
            name="can_manage_devices",
            field=models.BooleanField(
                default=False, verbose_name="Endgeräte verwalten"
            ),
        ),
        migrations.CreateModel(
            name="SessionDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="z. B. iPad 10. Gen, 64 GB",
                        max_length=200,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Seriennummer"
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Inventarnummer"
                    ),
                ),
                (
                    "accessories",
                    models.CharField(
                        blank=True,
                        help_text="z. B. Hülle, Tastatur, Netzteil",
                        max_length=300,
                        verbose_name="Zubehör",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "Im Bestand"),
                            ("issued", "Ausgegeben"),
                            ("defect", "Defekt"),
                            ("retired", "Ausgemustert"),
                        ],
                        default="in_stock",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ausgegeben am"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="session.sessionperson",
                        verbose_name="Ausgegeben an",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endgerät",
                "verbose_name_plural": "Endgeräte",
                "db_table": "session_devices",
                "ordering": ["label", "inventory_number"],
            },
        ),
        migrations.CreateModel(
            name="SessionDeviceGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Betrag"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="z. B. Ratsbeschluss, Beleg",
                        verbose_name="Vermerk",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Genehmigt"),
                            ("paid", "Ausgezahlt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Genehmigt am"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ausgezahlt am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_device_grants",
                        to="session.sessionuser",
                        verbose_name="Genehmigt von",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_device_grants",
                        to="session.sessionuser",
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_grants",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_grants",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endgeräte-Zuschuss",
                "verbose_name_plural": "Endgeräte-Zuschüsse",
                "db_table": "session_device_grants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionDeviceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Angelegt"),
                            ("issued", "Ausgegeben"),
                            ("returned", "Zurückgenommen"),
                            ("defect", "Defekt gemeldet"),
                            ("retired", "Ausgemustert"),
                            ("note", "Vermerk"),
                        ],
                        max_length=20,
                        verbose_name="Aktion",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Vermerk")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_logs",
                        to="session.sessionuser",
                        verbose_name="Erfasst von",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="session.sessiondevice",
                        verbose_name="Endgerät",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_logs",
                        to="session.sessionperson",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geräte-Historie",
                "verbose_name_plural": "Geräte-Historien",
                "db_table": "session_device_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
