# Generated by Django 6.0.6 on 2026-09-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0023_endgeraete"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_public",
            field=models.BooleanField(
                default=True,
                help_text="Nur wirksam, wenn der Mandant die Veröffentlichung eingeschaltet hat",
                verbose_name="Umsetzungsstand öffentlich zeigen",
            ),
        ),
        migrations.AddField(
            model_name="sessionagendaitem",
            name="implementation_public_note",
            field=models.TextField(
                blank=True,
                help_text="Kurzer Stand für Bürgerinnen und Bürger — ohne interne Details",
                verbose_name="Öffentliche Statusmeldung",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="implementation_publish",
            field=models.BooleanField(
                default=False,
                help_text="Zeigt den Umsetzungsstand öffentlicher, angenommener Beschlüsse in Insight („Was wurde aus …?“)",
                verbose_name="Umsetzungsstand im Bürgerportal veröffentlichen",
            ),
        ),
    ]
