# Generated by Django 6.0.6 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0024_beschluss_tracking_veroeffentlichung"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="require_2fa",
            field=models.BooleanField(
                default=False,
                help_text="Alle Session-Nutzer dieses Mandanten müssen einen zweiten Faktor einrichten",
                verbose_name="2FA für alle Nutzer erforderlich",
            ),
        ),
    ]
