# Generated by Django 6.1.1 on 2026-09-18 19:42
# Nummernkreise (Issue #150): konfigurierbare Vorlagennummern, Unternummern, Wahlperioden-Nummer.

import django.db.models.deletion
import uuid
from django.db import migrations, models


def bestand_uebernehmen(apps, schema_editor):
    """
    Je Mandant einen Standard-Nummernkreis ``V/{jahr}/{lfd:4}`` anlegen und die Zähler auf die
    höchste bereits vergebene Nummer je Jahr setzen – damit geht die bisherige Vergabe
    (``SessionPaper.next_reference``) nahtlos weiter und keine Nummer entsteht doppelt.
    """
    import re

    Tenant = apps.get_model("session", "SessionTenant")
    Paper = apps.get_model("session", "SessionPaper")
    Range = apps.get_model("session", "SessionNumberRange")
    Counter = apps.get_model("session", "SessionNumberCounter")
    muster = re.compile(r"^V/(\d{4})/(\d+)$")
    for tenant in Tenant.objects.all():
        if Range.objects.filter(tenant=tenant).exists():
            continue
        rng = Range.objects.create(
            tenant=tenant,
            name="Vorlagen",
            pattern="V/{jahr}/{lfd:4}",
            reset="yearly",
            assign_on="create",
            paper_types=[],
            sub_pattern="{parent}/{sub}",
        )
        hoechste: dict[str, int] = {}
        for ref in Paper.objects.filter(tenant=tenant).values_list("reference", flat=True):
            m = muster.match(ref or "")
            if m:
                hoechste[m.group(1)] = max(hoechste.get(m.group(1), 0), int(m.group(2)))
        for jahr, wert in hoechste.items():
            Counter.objects.create(number_range=rng, scope=jahr, value=wert)


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0033_geo_ausbau_adressen_verortungen"),
        ("session", "0025_zwei_faktor_pflicht"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionNumberCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(blank=True, max_length=120, verbose_name="Zählerbereich"),
                ),
                (
                    "value",
                    models.PositiveIntegerField(default=0, verbose_name="Zuletzt vergeben"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zählerstand",
                "verbose_name_plural": "Zählerstände",
                "db_table": "session_number_counters",
            },
        ),
        migrations.CreateModel(
            name="SessionNumberRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z. B. Drucksachen, Anträge der Politik",
                        max_length=100,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Wert des Platzhalters {prefix}",
                        max_length=20,
                        verbose_name="Präfix",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        default="V/{jahr}/{lfd:4}",
                        help_text="Platzhalter: {lfd} bzw. {lfd:4}, {jahr}, {jj}, {wp}, {prefix}, {gremium}",
                        max_length=100,
                        verbose_name="Muster",
                    ),
                ),
                (
                    "reset",
                    models.CharField(
                        choices=[
                            ("yearly", "Jährlich"),
                            ("term", "Je Wahlperiode"),
                            ("never", "Nie (fortlaufend)"),
                        ],
                        default="yearly",
                        max_length=10,
                        verbose_name="Zähler zurücksetzen",
                    ),
                ),
                (
                    "assign_on",
                    models.CharField(
                        choices=[
                            ("create", "Beim Anlegen"),
                            ("release", "Bei der Freigabe"),
                        ],
                        default="create",
                        max_length=10,
                        verbose_name="Nummer vergeben",
                    ),
                ),
                (
                    "paper_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Leer = alle Vorlagenarten ohne eigenen Nummernkreis",
                        verbose_name="Vorlagenarten",
                    ),
                ),
                (
                    "sub_pattern",
                    models.CharField(
                        default="{parent}.{sub}",
                        help_text="Ergänzungen, Neufassungen, Antworten: Platzhalter {parent} und {sub} bzw. {sub:2}",
                        max_length=60,
                        verbose_name="Muster für Unternummern",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nummernkreis",
                "verbose_name_plural": "Nummernkreise",
                "db_table": "session_number_ranges",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="sessionpaper",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sessionlegislativeterm",
            name="number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="z. B. 22 für die 22. Wahlperiode; Grundlage des Platzhalters {wp} in Nummernkreisen",
                null=True,
                verbose_name="Nummer",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="parent_paper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_papers",
                to="session.sessionpaper",
                verbose_name="Bezugsvorlage",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="reference_assigned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Nummer vergeben am"),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="relation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supplement", "Ergänzung"),
                    ("revision", "Neufassung"),
                    ("amendment", "Änderungsantrag"),
                    ("answer", "Antwort/Stellungnahme"),
                    ("recommendation", "Beschlussempfehlung"),
                ],
                max_length=20,
                verbose_name="Art des Bezugs",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="sub_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Unternummer"),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="reference_label",
            field=models.CharField(
                default="Vorlagen-Nr.",
                help_text="z. B. „Drucksache“ oder „Vorlagen-Nr.“",
                max_length=40,
                verbose_name="Bezeichnung der Vorlagennummer",
            ),
        ),
        migrations.AlterField(
            model_name="sessionpaper",
            name="paper_type",
            field=models.CharField(
                choices=[
                    ("proposal", "Beschlussvorlage"),
                    ("report", "Mitteilungsvorlage"),
                    ("motion", "Antrag"),
                    ("inquiry", "Anfrage"),
                    ("major_inquiry", "Große Anfrage"),
                    ("answer", "Antwort/Stellungnahme"),
                    ("recommendation", "Beschlussempfehlung"),
                    ("amendment", "Änderungsantrag"),
                    ("resolution", "Resolution"),
                    ("bylaw", "Satzung"),
                    ("budget", "Haushalt"),
                    ("other", "Sonstiges"),
                ],
                default="proposal",
                max_length=100,
                verbose_name="Vorlagenart",
            ),
        ),
        migrations.AlterField(
            model_name="sessionpaper",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Wird automatisch aus dem Nummernkreis vergeben, z. B. 22-0593 oder V/0599/2024",
                max_length=100,
                verbose_name="Vorlagennummer",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionpaper",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("tenant", "reference"),
                name="uniq_session_paper_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionpaper",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sub_number__isnull", False)),
                fields=("parent_paper", "sub_number"),
                name="uniq_session_paper_sub_number",
            ),
        ),
        migrations.AddField(
            model_name="sessionnumberrange",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="number_ranges",
                to="session.sessiontenant",
                verbose_name="Mandant",
            ),
        ),
        migrations.AddField(
            model_name="sessionnumbercounter",
            name="number_range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counters",
                to="session.sessionnumberrange",
                verbose_name="Nummernkreis",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionnumbercounter",
            constraint=models.UniqueConstraint(
                fields=("number_range", "scope"),
                name="uniq_session_number_counter_scope",
            ),
        ),
        migrations.RunPython(bestand_uebernehmen, migrations.RunPython.noop),
    ]
