# Generated by Django 6.1.1 on 2026-09-25 07:00
# Sitzungsmappe (Issue #218): Gesamt-PDF und ZIP-Paket je Sitzung und Fassung.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0026_nummernkreise"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionMeetingPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("public", "Öffentliche Fassung"),
                            ("internal", "Nichtöffentliche Fassung"),
                        ],
                        max_length=20,
                        verbose_name="Fassung",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Fassungsnummer")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Angefordert"),
                            ("building", "In Arbeit"),
                            ("ready", "Fertig"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 über die Eingaben (Tagesordnung, Vorlagen, Anlagen) dieser Fassung",
                        max_length=64,
                        verbose_name="Fingerabdruck",
                    ),
                ),
                (
                    "content_as_of",
                    models.DateTimeField(blank=True, null=True, verbose_name="Stand"),
                ),
                (
                    "contents",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Enthaltene Objekte"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to="session/files/mappen/%Y/%m/",
                        verbose_name="Gesamt-PDF",
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        blank=True,
                        upload_to="session/files/mappen/%Y/%m/",
                        verbose_name="ZIP-Paket",
                    ),
                ),
                (
                    "pdf_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Größe PDF (Bytes)"
                    ),
                ),
                (
                    "zip_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Größe ZIP (Bytes)"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(default=0, verbose_name="Seiten"),
                ),
                (
                    "embedded_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Eingebundene Anlagen"
                    ),
                ),
                (
                    "referenced_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Anlagen als Verweisseite"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Fehler")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Versuche"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Angefordert am"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Begonnen am"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fertig am"
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_meeting_packages",
                        to="session.sessionuser",
                        verbose_name="Angefordert von",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_packages",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzungsmappe",
                "verbose_name_plural": "Sitzungsmappen",
                "db_table": "session_meeting_packages",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="session_mee_status_bf1edf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "variant", "version"),
                        name="uniq_session_meeting_package_version",
                    )
                ],
            },
        ),
    ]
