# Generated by Django 6.1.1 on 2026-09-25 08:26

import apps.common.encryption
import apps.session.models
import django.db.models.deletion
from django.db import migrations, models


def altbestand_nachziehen(apps, schema_editor):
    """Bestehende Ladungsempfänger: eigener Link-Schlüssel je Zeile, Versandzeit aus created_at."""
    import secrets

    Recipient = apps.get_model("session", "SessionInvitationRecipient")
    for recipient in Recipient.objects.only("id", "status", "created_at").iterator():
        Recipient.objects.filter(pk=recipient.pk).update(
            response_nonce=secrets.token_urlsafe(12),
            sent_at=recipient.created_at if recipient.status == "sent" else None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0027_sitzungsmappe"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionattendance",
            name="responded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rückmeldung am"
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="response_reason_encrypted",
            field=apps.common.encryption.EncryptedTextField(
                verbose_name="Grund der Absage (verschlüsselt)"
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="response_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("link", "Rückmeldelink"),
                    ("portal", "Portal"),
                    ("staff", "Sitzungsdienst"),
                ],
                max_length=10,
                verbose_name="Rückmeldung über",
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="substitute_requested",
            field=models.BooleanField(default=False, verbose_name="Vertretung erbeten"),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="substitutes_notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Stellvertretung benachrichtigt am"
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="acknowledged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Empfang bestätigt am"
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="acknowledged_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("link", "Rückmeldelink"),
                    ("portal", "Portal"),
                    ("staff", "Sitzungsdienst"),
                ],
                max_length=10,
                verbose_name="Empfang bestätigt über",
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "E-Mail"),
                    ("portal", "Portal (mandari Work)"),
                    ("letter", "Brief"),
                ],
                default="email",
                max_length=10,
                verbose_name="Zustellweg",
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="last_reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zuletzt erinnert am"
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="reminder_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Erinnerungen"
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="response_nonce",
            field=models.CharField(
                default=apps.session.models.new_response_nonce,
                editable=False,
                max_length=32,
                verbose_name="Link-Schlüssel",
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Versandt am"
            ),
        ),
        migrations.AddField(
            model_name="sessioninvitationrecipient",
            name="substitute_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitution_requests",
                to="session.sessionperson",
                verbose_name="Vertretung für",
            ),
        ),
        migrations.AddField(
            model_name="sessionperson",
            name="delivery_channel",
            field=models.CharField(
                choices=[
                    ("email", "E-Mail"),
                    ("portal", "Portal (mandari Work)"),
                    ("letter", "Brief"),
                ],
                default="email",
                max_length=10,
                verbose_name="Zustellweg für Ladungen",
            ),
        ),
        migrations.AlterField(
            model_name="sessioninvitationdispatch",
            name="dispatch_type",
            field=models.CharField(
                choices=[
                    ("invitation", "Ladung"),
                    ("supplementary", "Nachladung/Nachtrag"),
                    ("substitution", "Vertretungsanfrage"),
                ],
                default="invitation",
                max_length=20,
                verbose_name="Versandart",
            ),
        ),
        migrations.AlterField(
            model_name="sessioninvitationrecipient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-Mail"),
        ),
        migrations.AlterField(
            model_name="sessioninvitationrecipient",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Versandt"),
                    ("failed", "Fehlgeschlagen"),
                    ("letter_pending", "Brief vorzubereiten"),
                    ("letter_sent", "Brief versandt"),
                ],
                default="sent",
                max_length=20,
                verbose_name="Zustellstatus",
            ),
        ),
        migrations.RunPython(altbestand_nachziehen, migrations.RunPython.noop),
    ]
