# Generated by Django 6.1.1 on 2026-09-25 09:24
#
# Vier-Augen-Prinzip und Vertretungen (Issue #222). Die Standardwerte gelten auch für bestehende
# Mandanten: Sitzungsgeld und Pauschalen an (wie bisher), Vorlagenfreigabe, Niederschrift und
# Übergabe von Beschlussauszügen aus – bestehende Abläufe bleiben unverändert.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0028_ladung_rueckmeldung"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionauditlog",
            name="on_behalf_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="session.sessionuser",
                verbose_name="In Vertretung für",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="approved_on_behalf_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="session.sessionuser",
                verbose_name="Freigegeben in Vertretung für",
            ),
        ),
        migrations.AddField(
            model_name="sessionpaper",
            name="content_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="session.sessionuser",
                verbose_name="Zuletzt inhaltlich bearbeitet von",
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="approved_on_behalf_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="session.sessionuser",
                verbose_name="Genehmigt in Vertretung für",
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="content_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="session.sessionuser",
                verbose_name="Zuletzt inhaltlich bearbeitet von",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="four_eyes_allowances",
            field=models.BooleanField(
                default=True,
                verbose_name="Vier-Augen-Prinzip: Sitzungsgeld und Pauschalen",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="four_eyes_forwardings",
            field=models.BooleanField(
                default=False,
                verbose_name="Vier-Augen-Prinzip: Übergabe von Beschlussauszügen",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="four_eyes_papers",
            field=models.CharField(
                choices=[
                    ("off", "Aus"),
                    ("financial", "Nur bei finanziellen Auswirkungen"),
                    ("always", "Immer"),
                ],
                default="off",
                max_length=10,
                verbose_name="Vier-Augen-Prinzip: Vorlagenfreigabe",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="four_eyes_protocols",
            field=models.BooleanField(
                default=False, verbose_name="Vier-Augen-Prinzip: Niederschrift"
            ),
        ),
        migrations.CreateModel(
            name="SessionDelegation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Von")),
                ("end_date", models.DateField(verbose_name="Bis einschließlich")),
                (
                    "scope_approvals",
                    models.BooleanField(
                        default=True, verbose_name="Freigaben und Genehmigungen"
                    ),
                ),
                (
                    "scope_worklist",
                    models.BooleanField(default=True, verbose_name="Arbeitsvorrat"),
                ),
                (
                    "scope_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Benachrichtigungen"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aufgehoben am"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Eingetragen von",
                    ),
                ),
                (
                    "deputy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to="session.sessionuser",
                        verbose_name="Vertretung",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to="session.sessionuser",
                        verbose_name="Vertretene Person",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Aufgehoben von",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vertretung",
                "verbose_name_plural": "Vertretungen",
                "db_table": "session_delegations",
                "ordering": ["start_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "deputy", "end_date"],
                        name="session_del_tenant__385fe6_idx",
                    ),
                    models.Index(
                        fields=["tenant", "principal", "end_date"],
                        name="session_del_tenant__465b4d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("principal", models.F("deputy")), _negated=True
                        ),
                        name="session_delegation_not_self",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="session_delegation_period",
                    ),
                ],
            },
        ),
    ]
