# Generated by Django 6.1.1 on 2026-09-25 09:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0029_vier_augen_vertretung"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionFileBlob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sha256", models.CharField(max_length=64, verbose_name="SHA-256")),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Größe (Bytes)"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="session/files/%Y/%m/",
                        verbose_name="Datei",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inhalt gelöscht am"
                    ),
                ),
                (
                    "purge_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Grund der Löschung"
                    ),
                ),
                (
                    "purged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Inhalt gelöscht von",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_blobs",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dateiinhalt",
                "verbose_name_plural": "Dateiinhalte",
                "db_table": "session_file_blobs",
            },
        ),
        migrations.CreateModel(
            name="SessionFileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Fassung")),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-Typ"
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Größe (Bytes)"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hinweis"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Erfasst am"
                    ),
                ),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="file_versions",
                        to="session.sessionfileblob",
                        verbose_name="Inhalt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Erfasst von",
                    ),
                ),
                (
                    "session_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="session.sessionfile",
                        verbose_name="Anlage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_versions",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anlagen-Fassung",
                "verbose_name_plural": "Anlagen-Fassungen",
                "db_table": "session_file_versions",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="SessionPaperVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Fassung")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("transition", "Workflow-Übergang"),
                            ("consultation", "Beratungsergebnis"),
                            ("manual", "Von Hand gesichert"),
                            ("backup", "Sicherung vor Wiederherstellung"),
                            ("restore", "Wiederherstellung"),
                        ],
                        max_length=20,
                        verbose_name="Anlass",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Bemerkung"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=50, verbose_name="Status der Vorlage"),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Vorheriger Status"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, verbose_name="Beschlossene Fassung"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(max_length=64, verbose_name="Fingerabdruck"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Betreff")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vorlagennummer"
                    ),
                ),
                (
                    "paper_type",
                    models.CharField(max_length=100, verbose_name="Vorlagenart"),
                ),
                ("is_public", models.BooleanField(verbose_name="Öffentlich")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Datum")),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Frist"),
                ),
                ("main_text", models.TextField(blank=True, verbose_name="Sachverhalt")),
                (
                    "resolution_text",
                    models.TextField(blank=True, verbose_name="Beschlussvorschlag"),
                ),
                (
                    "has_financial_impact",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Finanzielle Auswirkungen"
                    ),
                ),
                (
                    "financial_impact_note",
                    models.TextField(
                        blank=True,
                        verbose_name="Erläuterung der finanziellen Auswirkungen",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Gremien, Amt, Urheber und Bezug im Wortlaut der Fassung, dazu die Kennungen",
                        verbose_name="Weitere Angaben",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Gesichert am"
                    ),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paper_versions",
                        to="session.sessionagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Gesichert von",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="session.sessionpaper",
                        verbose_name="Vorlage",
                    ),
                ),
                (
                    "restored_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionpaperversion",
                        verbose_name="Wiederhergestellt aus",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_versions",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorlagen-Fassung",
                "verbose_name_plural": "Vorlagen-Fassungen",
                "db_table": "session_paper_versions",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="SessionPaperVersionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attachment_id", models.UUIDField(verbose_name="Anlage")),
                (
                    "file_version_number",
                    models.PositiveIntegerField(verbose_name="Fassung der Anlage"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-Typ"
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Größe (Bytes)"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                ("is_public", models.BooleanField(verbose_name="Öffentlich")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "blob",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="paper_version_files",
                        to="session.sessionfileblob",
                        verbose_name="Inhalt",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="session.sessionpaperversion",
                        verbose_name="Fassung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anlage einer Vorlagen-Fassung",
                "verbose_name_plural": "Anlagen einer Vorlagen-Fassung",
                "db_table": "session_paper_version_files",
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="sessionfileblob",
            index=models.Index(fields=["file"], name="session_blob_file_idx"),
        ),
        migrations.AddConstraint(
            model_name="sessionfileblob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purged_at__isnull", True)),
                fields=("tenant", "sha256"),
                name="uniq_session_file_blob_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionfileversion",
            constraint=models.UniqueConstraint(
                fields=("session_file", "number"),
                name="uniq_session_file_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionpaperversion",
            constraint=models.UniqueConstraint(
                fields=("paper", "number"), name="uniq_session_paper_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionpaperversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_resolved", True)),
                fields=("paper",),
                name="uniq_session_paper_resolved_version",
            ),
        ),
    ]
