# Generated by Django 6.1.1 on 2026-09-25 10:18

import django.utils.timezone
from django.db import migrations, models

# Standardrollen für die Protokollkontrolle (Stand dieser Migration, bewusst eingefroren)
KONTROLLROLLEN = [
    {
        "name": "Revision",
        "description": "Rechnungsprüfung: Protokoll einsehen, exportieren und auf Manipulation prüfen",
        "color": "#0f766e",
    },
    {
        "name": "Datenschutz",
        "description": "Datenschutzbeauftragte: Protokoll einsehen, exportieren und auf Manipulation prüfen",
        "color": "#0369a1",
    },
]


def kontrollrollen_anlegen(apps, schema_editor):
    """Issue #221: Kontrollrechte gehören nicht mehr zur Administrator-Vollmacht.

    - Bestehende Administrator-Rollen behalten die Protokoll-Ansicht als ausdrücklichen Haken
      (nichts ändert sich für laufende Mandanten; der Haken lässt sich jetzt abwählen).
    - Jeder bestehende Mandant bekommt die Rollen „Revision“ und „Datenschutz“, sofern es
      Rollen dieses Namens noch nicht gibt.
    """
    SessionRole = apps.get_model("session", "SessionRole")
    SessionTenant = apps.get_model("session", "SessionTenant")
    SessionRole.objects.filter(is_admin=True).update(can_view_audit_log=True)
    for tenant_id in SessionTenant.objects.values_list("id", flat=True):
        for rolle in KONTROLLROLLEN:
            if SessionRole.objects.filter(tenant_id=tenant_id, name=rolle["name"]).exists():
                continue
            SessionRole.objects.create(
                tenant_id=tenant_id,
                name=rolle["name"],
                description=rolle["description"],
                color=rolle["color"],
                priority=20,
                is_system_role=True,
                can_view_dashboard=True,
                can_view_meetings=False,
                can_view_papers=False,
                can_view_applications=False,
                can_view_protocols=False,
                can_access_oparl_api=False,
                can_view_audit_log=True,
                can_export_audit_log=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0030_fassungen"),
        ("common", "0005_protokoll_kettenkopf"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionauditlog",
            name="entry_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Eintrags-Hash",
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="on_behalf_of_ref",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Referenz „in Vertretung für“",
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="prev_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Vorgänger-Hash",
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="seq",
            field=models.BigIntegerField(
                blank=True, editable=False, null=True, verbose_name="Laufende Nummer"
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="user_ref",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="Benutzer-Referenz"
            ),
        ),
        migrations.AddField(
            model_name="sessionrole",
            name="can_export_audit_log",
            field=models.BooleanField(
                default=False, verbose_name="Audit-Log exportieren und prüfen"
            ),
        ),
        migrations.AlterField(
            model_name="sessionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Erstellt"),
                    ("update", "Geändert"),
                    ("delete", "Gelöscht"),
                    ("view", "Angesehen"),
                    ("download", "Heruntergeladen"),
                    ("approve", "Freigegeben"),
                    ("publish", "Veröffentlicht"),
                    ("invitation_sent", "Einladung versandt"),
                    ("withdraw", "Abgesetzt"),
                    ("replace", "Ersetzt"),
                    ("login", "Anmeldung"),
                    ("logout", "Abmeldung"),
                    ("login_failed", "Anmeldung fehlgeschlagen"),
                    ("vote", "Stimmabgabe erfasst"),
                    ("vote_result", "Abstimmungsergebnis festgestellt"),
                    ("cosign", "Mitzeichnung entschieden"),
                    ("allowance_created", "Entschädigung festgesetzt"),
                    ("allowance_approved", "Entschädigung genehmigt"),
                    ("allowance_paid", "Entschädigung ausgezahlt"),
                    ("allowance_cancelled", "Entschädigung storniert"),
                    ("roles_changed", "Rollen geändert"),
                    ("permissions_changed", "Rechte geändert"),
                    ("audit_view", "Protokoll eingesehen"),
                    ("audit_export", "Protokoll exportiert"),
                    ("audit_verify", "Protokoll geprüft"),
                    ("audit_archive", "Protokoll archiviert"),
                ],
                max_length=50,
                verbose_name="Aktion",
            ),
        ),
        migrations.AlterField(
            model_name="sessionauditlog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Zeitpunkt",
            ),
        ),
        migrations.RunPython(kontrollrollen_anlegen, migrations.RunPython.noop),
    ]
