# Generated by Django 6.1.1 on 2026-09-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0032_protokoll_indizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionapplication",
            name="submitted_via_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="session.sessionapitoken",
                verbose_name="Eingereicht mit API-Token",
            ),
        ),
    ]
