# Generated by Django 6.1.1 on 2026-09-25 13:17
#
# Niederschrift: Sperre nach Genehmigung, Berichtigung, Genehmigungsweg und öffentliche Fassung
# (Issue #318). Nur nullbare Felder, eine neue Tabelle und neue Auswahlwerte der Audit-Aktion
# (ohne Änderung an der Datenbank) – bestehende Tabellen werden nicht umgeschrieben.

import apps.common.encryption
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0033_einreichung_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionprotocol",
            name="approval_agenda_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocol_approvals",
                to="session.sessionagendaitem",
                verbose_name="Genehmigt unter TOP",
            ),
        ),
        migrations.AddField(
            model_name="sessionprotocol",
            name="public_file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_protocol",
                to="session.sessionfile",
                verbose_name="Öffentliche Fassung (Datei)",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="protocol_approval_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("follow_up", "Genehmigung in der Folgesitzung"),
                    ("direct", "Direkte Veröffentlichung ohne Genehmigungsschritt"),
                ],
                help_text="Leer: Genehmigung in der Folgesitzung",
                max_length=20,
                null=True,
                verbose_name="Genehmigungsweg der Niederschrift",
            ),
        ),
        migrations.AlterField(
            model_name="sessionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Erstellt"),
                    ("update", "Geändert"),
                    ("delete", "Gelöscht"),
                    ("view", "Angesehen"),
                    ("download", "Heruntergeladen"),
                    ("approve", "Freigegeben"),
                    ("publish", "Veröffentlicht"),
                    ("invitation_sent", "Einladung versandt"),
                    ("withdraw", "Abgesetzt"),
                    ("replace", "Ersetzt"),
                    ("login", "Anmeldung"),
                    ("logout", "Abmeldung"),
                    ("login_failed", "Anmeldung fehlgeschlagen"),
                    ("vote", "Stimmabgabe erfasst"),
                    ("vote_result", "Abstimmungsergebnis festgestellt"),
                    ("cosign", "Mitzeichnung entschieden"),
                    ("allowance_created", "Entschädigung festgesetzt"),
                    ("allowance_approved", "Entschädigung genehmigt"),
                    ("allowance_paid", "Entschädigung ausgezahlt"),
                    ("allowance_cancelled", "Entschädigung storniert"),
                    ("roles_changed", "Rollen geändert"),
                    ("permissions_changed", "Rechte geändert"),
                    ("audit_view", "Protokoll eingesehen"),
                    ("audit_export", "Protokoll exportiert"),
                    ("audit_verify", "Protokoll geprüft"),
                    ("audit_archive", "Protokoll archiviert"),
                    ("unpublish", "Veröffentlichung zurückgenommen"),
                    ("protocol_correction", "Niederschrift berichtigt"),
                    (
                        "protocol_correction_requested",
                        "Berichtigung der Niederschrift beantragt",
                    ),
                    (
                        "protocol_correction_rejected",
                        "Berichtigung der Niederschrift abgelehnt",
                    ),
                ],
                max_length=50,
                verbose_name="Aktion",
            ),
        ),
        migrations.CreateModel(
            name="SessionProtocolCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("item", "Tagesordnungspunkt"),
                            ("general", "Allgemeiner Teil"),
                            ("general_np", "Allgemeiner Teil (nichtöffentlich)"),
                        ],
                        max_length=20,
                        verbose_name="Gegenstand",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Erscheint mit Datum und Grund in der öffentlichen Niederschrift",
                        verbose_name="Betrifft den öffentlichen Teil",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Grund")),
                (
                    "reason_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Grund (nichtöffentlich, verschlüsselt)"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Änderungen (Anzeige)"
                    ),
                ),
                (
                    "payload_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Alte und neue Werte (verschlüsselt)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Zur Bestätigung"),
                            ("applied", "Wirksam"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Berichtigt am"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entschieden am"
                    ),
                ),
                (
                    "decision_note",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Vermerk zur Entscheidung",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Wirksam seit"
                    ),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_corrections",
                        to="session.sessionagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Bestätigt bzw. abgelehnt von",
                    ),
                ),
                (
                    "decided_on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Entschieden in Vertretung für",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="session.sessionprotocol",
                        verbose_name="Niederschrift",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Berichtigt von",
                    ),
                ),
                (
                    "requested_on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="session.sessionuser",
                        verbose_name="Berichtigt in Vertretung für",
                    ),
                ),
            ],
            options={
                "verbose_name": "Berichtigung der Niederschrift",
                "verbose_name_plural": "Berichtigungen der Niederschrift",
                "db_table": "session_protocol_corrections",
                "ordering": ["requested_at"],
                "indexes": [
                    models.Index(
                        fields=["protocol", "status"],
                        name="session_corr_protocol_status",
                    )
                ],
            },
        ),
    ]
