# Generated by Django 6.1.1 on 2026-09-25 14:35
#
# Mandantengruppe mit Leitstelle und gemeinsame Sitzungen mehrerer Gremien (Issue #317, Teil B).
# Nur neue Tabellen (Gruppe, Zugehörigkeit der Mandanten, Leitstellen-Mitgliedschaften und die
# Zuordnung weiterer Gremien zu einer Sitzung) – bestehende Tabellen werden nicht umgeschrieben.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0034_niederschrift_sperre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionTenantGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL-Kürzel"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mandantengruppe",
                "verbose_name_plural": "Mandantengruppen",
                "db_table": "session_tenant_groups",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="joint_organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gemeinsame Sitzung: Gremien, die zusätzlich zum federführenden Gremium tagen",
                related_name="joint_meetings",
                to="session.sessionorganization",
                verbose_name="Weitere beteiligte Gremien",
            ),
        ),
        migrations.CreateModel(
            name="SessionTenantGroupTenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_links",
                        to="session.sessiontenantgroup",
                        verbose_name="Mandantengruppe",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_link",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandant der Gruppe",
                "verbose_name_plural": "Mandanten der Gruppe",
                "db_table": "session_tenant_group_tenants",
                "ordering": ["tenant__name"],
            },
        ),
        migrations.AddField(
            model_name="sessiontenantgroup",
            name="tenants",
            field=models.ManyToManyField(
                blank=True,
                related_name="tenant_groups",
                through="session.SessionTenantGroupTenant",
                to="session.sessiontenant",
                verbose_name="Mandanten",
            ),
        ),
        migrations.CreateModel(
            name="SessionTenantGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            (
                                "leitstelle",
                                "Leitstelle (Arbeitsvorräte, Fristen, Sitzungen, Kennzahlen, Suche)",
                            ),
                            ("kennzahlen", "Kennzahlen (nur Zählwerte je Mandant)"),
                        ],
                        default="leitstelle",
                        max_length=20,
                        verbose_name="Gruppenrolle",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="z. B. Anlass der Freigabe",
                        max_length=255,
                        verbose_name="Vermerk",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="session.sessiontenantgroup",
                        verbose_name="Mandantengruppe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitstellen-Mitgliedschaft",
                "verbose_name_plural": "Leitstellen-Mitgliedschaften",
                "db_table": "session_tenant_group_memberships",
                "ordering": ["group__name", "user__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "user"),
                        name="uniq_session_tenant_group_member",
                    )
                ],
            },
        ),
    ]
