# Generated by Django 6.1.1 on 2026-09-25 14:42
#
# Mandant anlegen (Issue #317, Teil A): Körperschaftstyp und Amtlicher Gemeindeschlüssel am
# Session-Mandanten. Nur nullbare Felder – bestehende Tabellen werden nicht umgeschrieben.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0035_leitstelle_gemeinsame_sitzungen"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="ags",
            field=models.CharField(
                blank=True,
                help_text="8 Stellen für Gemeinden, 5 für Kreise, 2 oder 3 für Länder und Regierungsbezirke",
                max_length=8,
                null=True,
                verbose_name="Amtlicher Gemeindeschlüssel",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stadt", "Stadt"),
                    ("kreisfreie_stadt", "Kreisfreie Stadt"),
                    ("gemeinde", "Gemeinde"),
                    ("kreis", "Kreis bzw. Landkreis"),
                    ("bezirk", "Bezirk"),
                    ("gemeindeverband", "Gemeindeverband"),
                    ("regionalverband", "Regionalverband"),
                    ("zweckverband", "Zweckverband"),
                    ("sonstige", "Sonstige Körperschaft"),
                ],
                max_length=30,
                null=True,
                verbose_name="Körperschaftstyp",
            ),
        ),
    ]
