# Generated by Django 6.1.1 on 2026-09-26 11:22
#
# API-Token lesen nur Öffentliches: Beschriftung der Lese-Flags wie in der Oberfläche. Keine Datenänderung –
# bestehende Tokens behalten ihre Flags, erhalten aber unabhängig davon nie nichtöffentliche Daten.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0036_mandant_anlegen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionapitoken",
            name="can_read_meetings",
            field=models.BooleanField(
                default=True,
                help_text="Erlaubt das Lesen öffentlicher Sitzungsdaten – nie nichtöffentliche Sitzungen oder interne Notizen",
                verbose_name="Öffentliche Sitzungen lesen",
            ),
        ),
        migrations.AlterField(
            model_name="sessionapitoken",
            name="can_read_papers",
            field=models.BooleanField(
                default=True,
                help_text="Erlaubt das Lesen öffentlicher Vorlagen – nie nichtöffentliche Vorlagen oder deren Texte",
                verbose_name="Öffentliche Vorlagen lesen",
            ),
        ),
    ]
