# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-26 14:50
#
# Schlüsselwechsel: Während eines Wechsels bleibt der vorherige Mandantenschlüssel zum Lesen
# erhalten, bis alle Inhalte neu verschlüsselt sind. Keine Datenänderung.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0037_token_nur_oeffentlich"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="encryption_key_previous",
            field=models.BinaryField(
                blank=True,
                help_text="Nur während eines Schlüsselwechsels gesetzt, nur zum Lesen; mit dem Hauptschlüssel verschlüsselt",
                null=True,
                verbose_name="Vorheriger Verschlüsselungsschlüssel",
            ),
        ),
    ]
