# Generated by Django 6.0.6 on 2026-09-29 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0039_zugangstoken_als_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionExportCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Jahr")),
                (
                    "value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Zuletzt vergeben"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_counters",
                        to="session.sessiontenant",
                        verbose_name="Mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zählerstand Export-Referenz",
                "verbose_name_plural": "Zählerstände Export-Referenz",
                "db_table": "session_export_counters",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "year"),
                        name="uniq_session_export_counter_year",
                    )
                ],
            },
        ),
    ]
