# Generated by Django 6.0.6 on 2026-09-29 10:47
#
# Ende-TOPs kennzeichnen: Standard-TOPs am Schluss (z. B. „Verschiedenes“) bleiben hinter später
# ergänzten TOPs. Bisher hing das an hohen Order-Werten, die die erste Neunummerierung auf 1..n
# setzte; ab dem zweiten ergänzten TOP landete der neue Punkt hinter den Ende-TOPs.
#
# Abwärtskompatibel: neue Spalte mit Datenbank-Vorgabe (ein älteres Image legt TOPs weiter an).
# Die Datenübernahme ist idempotent und setzt nur die neue Kennzeichnung.

from django.db import migrations, models
from django.utils import timezone

#: Order-Basis der Ende-TOPs (textblock_service.END_ORDER_BASE), Stand dieser Migration
END_ORDER_BASE = 900000


def mark_end_items(apps, schema_editor):
    SessionAgendaItem = apps.get_model("session", "SessionAgendaItem")
    SessionStandardAgendaItem = apps.get_model("session", "SessionStandardAgendaItem")

    # Noch nicht neu nummerierte Tagesordnungen: Ende-TOPs stehen unverändert ab END_ORDER_BASE
    SessionAgendaItem.objects.filter(parent__isnull=True, order__gte=END_ORDER_BASE).update(is_end_item=True)

    # Bereits neu nummerierte, noch anstehende Sitzungen: TOPs ohne Vorlage mit dem Betreff eines
    # Standard-TOPs „am Ende“ (desselben Mandanten, für alle Gremien oder das Gremium der Sitzung)
    jetzt = timezone.now()
    vorlagen = SessionStandardAgendaItem.objects.filter(placement="end").values_list(
        "tenant_id", "organization_id", "name"
    )
    for tenant_id, organization_id, name in vorlagen:
        items = SessionAgendaItem.objects.filter(
            meeting__tenant_id=tenant_id,
            meeting__start__gte=jetzt,
            parent__isnull=True,
            paper__isnull=True,
            name=name,
            is_end_item=False,
        )
        if organization_id is not None:
            items = items.filter(meeting__organization_id=organization_id)
        items.update(is_end_item=True)


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0040_export_referenz_zaehler"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="is_end_item",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Standard-TOP am Schluss der Tagesordnung; später ergänzte TOPs werden davor eingereiht",
                verbose_name="Ende-TOP",
            ),
        ),
        migrations.RunPython(mark_end_items, migrations.RunPython.noop, elidable=True),
    ]
