# Generated by Django 6.0.6 on 2026-09-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0041_ende_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="insight_end_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paused", "Vorübergehend abgeschaltet"),
                    ("archived", "Als Archiv behalten"),
                    ("withdrawn", "Dauerhaft zurückgenommen"),
                ],
                db_default="",
                default="",
                help_text="Wie das Bürgerportal den Bestand zeigt, solange nicht veröffentlicht wird",
                max_length=20,
                verbose_name="Veröffentlichung im Bürgerportal beendet",
            ),
        ),
    ]
