# Generated by Django 6.0.6 on 2026-09-29 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0041_ende_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfile",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="session.sessionapplication",
                verbose_name="Antrag",
            ),
        ),
    ]
