# Generated by Django 6.0.6 on 2026-09-30 01:50
#
# Sitzungsformat und Landesprofil (Issue #138): Tabelle der Landesprofile, Landesprofil und Nachweis der
# örtlichen Rechtsgrundlage je Mandant, gesetzliche Ausschussart je Gremium, Format je Sitzung.
#
# Abwärtskompatibel: neue Tabelle, nullable Spalten bzw. Spalten mit Datenbank-Vorgabe – ein älteres
# Image legt Mandanten, Gremien und Sitzungen weiter an.

import apps.common.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0042_buergerportal_ende"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionStateProfile",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Länderkürzel",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Land")),
                (
                    "law",
                    models.CharField(max_length=255, verbose_name="Kommunalverfassung"),
                ),
                (
                    "hybrid_council",
                    models.CharField(
                        choices=[
                            ("regular", "zulässig (Regelbetrieb)"),
                            ("emergency", "nur in Notlagen"),
                            ("none", "nicht vorgesehen"),
                            ("unclear", "ungeklärt"),
                        ],
                        max_length=20,
                        verbose_name="Hybrid: Rat/Vertretung",
                    ),
                ),
                (
                    "hybrid_committees",
                    models.CharField(
                        choices=[
                            ("regular", "zulässig (Regelbetrieb)"),
                            ("emergency", "nur in Notlagen"),
                            ("none", "nicht vorgesehen"),
                            ("unclear", "ungeklärt"),
                        ],
                        max_length=20,
                        verbose_name="Hybrid: Ausschüsse",
                    ),
                ),
                (
                    "digital_council",
                    models.CharField(
                        choices=[
                            ("regular", "zulässig (Regelbetrieb)"),
                            ("emergency", "nur in Notlagen"),
                            ("none", "nicht vorgesehen"),
                            ("unclear", "ungeklärt"),
                        ],
                        max_length=20,
                        verbose_name="Digital: Rat/Vertretung",
                    ),
                ),
                (
                    "digital_committees",
                    models.CharField(
                        choices=[
                            ("regular", "zulässig (Regelbetrieb)"),
                            ("emergency", "nur in Notlagen"),
                            ("none", "nicht vorgesehen"),
                            ("unclear", "ungeklärt"),
                        ],
                        max_length=20,
                        verbose_name="Digital: Ausschüsse",
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("hauptsatzung", "Hauptsatzung"),
                            ("geschaeftsordnung", "Geschäftsordnung"),
                            ("beschluss", "Beschluss des Gremiums"),
                            ("unclear", "ungeklärt"),
                        ],
                        help_text="Worin die Kommune hybride Sitzungen zulassen muss",
                        max_length=20,
                        verbose_name="Voraussetzung im Regelbetrieb",
                    ),
                ),
                (
                    "chair_present",
                    models.CharField(
                        choices=[
                            ("required", "muss im Sitzungsraum anwesend sein"),
                            ("not_required", "darf zugeschaltet sein"),
                            ("unclear", "ungeklärt"),
                        ],
                        max_length=20,
                        verbose_name="Vorsitz",
                    ),
                ),
                (
                    "remote_elections",
                    models.CharField(
                        choices=[
                            ("allowed", "zulässig"),
                            ("excluded", "ausgeschlossen"),
                            ("conditional", "nur unter Bedingungen"),
                            ("unclear", "ungeklärt"),
                        ],
                        max_length=20,
                        verbose_name="Wahlen für Zugeschaltete",
                    ),
                ),
                (
                    "remote_secret_votes",
                    models.CharField(
                        choices=[
                            ("allowed", "zulässig"),
                            ("excluded", "ausgeschlossen"),
                            ("conditional", "nur unter Bedingungen"),
                            ("unclear", "ungeklärt"),
                        ],
                        max_length=20,
                        verbose_name="Geheime Abstimmungen für Zugeschaltete",
                    ),
                ),
                (
                    "excluded_committee_kinds",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ausschussarten (SessionOrganization.committee_kind), für die der Regelbetrieb nicht gilt",
                        verbose_name="Ausgenommene Ausschussarten",
                    ),
                ),
                (
                    "excluded_committee_rule",
                    models.CharField(
                        choices=[
                            ("regular", "zulässig (Regelbetrieb)"),
                            ("emergency", "nur in Notlagen"),
                            ("none", "nicht vorgesehen"),
                            ("unclear", "ungeklärt"),
                        ],
                        default="none",
                        help_text="z. B. NRW: Hauptausschuss nur in Notlagen hybrid (§ 47a statt § 58a GO NRW)",
                        max_length=20,
                        verbose_name="Regel für ausgenommene Ausschüsse",
                    ),
                ),
                (
                    "approved_systems_required",
                    models.BooleanField(
                        default=False,
                        verbose_name="Nur zugelassene Konferenz- und Abstimmungssysteme",
                    ),
                ),
                (
                    "public_registration_required",
                    models.BooleanField(
                        default=False,
                        verbose_name="Digitale Öffentlichkeit nur nach Anmeldung",
                    ),
                ),
                (
                    "norm_regular",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Norm (Regelbetrieb)"
                    ),
                ),
                (
                    "norm_emergency",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Norm (Notlage)"
                    ),
                ),
                (
                    "emergency_requirements",
                    models.TextField(
                        blank=True, verbose_name="Voraussetzungen in der Notlage"
                    ),
                ),
                (
                    "excluded_matters",
                    models.TextField(
                        blank=True,
                        verbose_name="Ausschlüsse (Sitzungen, Gegenstände, Wahlen)",
                    ),
                ),
                (
                    "public_rule",
                    models.TextField(blank=True, verbose_name="Öffentlichkeit"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Hinweise")),
                (
                    "sources",
                    models.JSONField(blank=True, default=list, verbose_name="Quellen"),
                ),
                ("as_of", models.DateField(verbose_name="Stand der Recherche")),
                (
                    "verification",
                    models.CharField(
                        choices=[
                            ("wortlaut", "Gesetzeswortlaut eingesehen"),
                            (
                                "teilweise",
                                "teilweise Wortlaut, teilweise Sekundärquellen",
                            ),
                            ("sekundaer", "nur Sekundärquellen"),
                        ],
                        max_length=20,
                        verbose_name="Prüftiefe",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Landesprofil",
                "verbose_name_plural": "Landesprofile",
                "db_table": "session_state_profiles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="format",
            field=models.CharField(
                choices=[
                    ("presence", "Präsenzsitzung"),
                    ("hybrid", "Hybride Sitzung"),
                    ("digital", "Digitale Sitzung"),
                ],
                db_default="presence",
                default="presence",
                max_length=20,
                verbose_name="Sitzungsformat",
            ),
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="format_reason",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Pflicht bei digitalen Sitzungen und bei hybriden Sitzungen, die das Landesrecht nur in Notlagen zulässt: Notlage und zugrunde liegender Beschluss",
                verbose_name="Begründung des Sitzungsformats",
            ),
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="public_access_note",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="z. B. „Anmeldung zum geschützten Zugang bis zwei Tage vor der Sitzung per E-Mail“",
                max_length=500,
                verbose_name="Hinweis für die Öffentlichkeit",
            ),
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="public_access_url",
            field=models.URLField(
                blank=True,
                db_default="",
                default="",
                help_text="Adresse des Livestreams bzw. der Anmeldeseite für den geschützten Zugang",
                max_length=500,
                verbose_name="Übertragung für die Öffentlichkeit",
            ),
        ),
        migrations.AddField(
            model_name="sessionmeeting",
            name="remote_access_encrypted",
            field=apps.common.encryption.EncryptedTextField(
                verbose_name="Zugangsweg für Zugeschaltete"
            ),
        ),
        migrations.AddField(
            model_name="sessionorganization",
            name="committee_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("main", "Hauptausschuss"),
                    ("finance", "Finanzausschuss"),
                    ("audit", "Rechnungsprüfungsausschuss"),
                ],
                db_default="",
                default="",
                help_text="Nur für Ausschüsse mit besonderen Regeln im Kommunalrecht (Sitzungsformat)",
                max_length=20,
                verbose_name="Gesetzliche Ausschussart",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="digital_public_registration_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Frist laut Geschäftsordnung, bis zu der sich Zuhörende für den geschützten Zugang anmelden",
                null=True,
                verbose_name="Anmeldefrist digitale Öffentlichkeit (Tage)",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="hybrid_basis_date",
            field=models.DateField(
                blank=True,
                help_text="Beschluss- oder Inkrafttretensdatum der Regelung",
                null=True,
                verbose_name="Datum der Rechtsgrundlage",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="hybrid_basis_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hauptsatzung", "Hauptsatzung"),
                    ("geschaeftsordnung", "Geschäftsordnung"),
                    ("beschluss", "Beschluss des Gremiums"),
                ],
                db_default="",
                default="",
                max_length=20,
                verbose_name="Örtliche Rechtsgrundlage",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="hybrid_basis_reference",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="z. B. „§ 7 Hauptsatzung, Amtsblatt 2024 Nr. 5“",
                max_length=255,
                verbose_name="Fundstelle",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="state_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Kommunalverfassungsrecht des Landes für hybride und digitale Sitzungen",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenants",
                to="session.sessionstateprofile",
                verbose_name="Landesprofil",
            ),
        ),
    ]
