# Generated by Django 6.0.6 on 2026-09-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0043_antrag_anhaenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionperson",
            name="contact_consent_date",
            field=models.DateField(blank=True, null=True, verbose_name="Einwilligung vom"),
        ),
        migrations.AddField(
            model_name="sessionperson",
            name="contact_consent_evidence",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="z. B. „Schriftliche Erklärung, abgelegt in der Mandatsakte“",
                max_length=255,
                verbose_name="Nachweis der Einwilligung",
            ),
        ),
        migrations.AddField(
            model_name="sessionperson",
            name="contact_publish",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="E-Mail-Adresse in der OParl-Schnittstelle und im Bürgerportal zeigen",
                verbose_name="Kontaktdaten veröffentlichen",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="oparl_public_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Leer: Die OParl-Schnittstelle ist nicht freigeschaltet und antwortet mit 404",
                null=True,
                verbose_name="OParl-Schnittstelle öffentlich seit",
            ),
        ),
    ]
