# Generated by Django 6.0.6 on 2026-09-30 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0045_landesprofile_laden"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionagendaitem",
            name="is_election",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Personalentscheidung, z. B. Wahl in ein Gremium oder Amt",
                verbose_name="Wahl",
            ),
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="participation_mode",
            field=models.CharField(
                choices=[("in_person", "Vor Ort"), ("remote", "Zugeschaltet")],
                db_default="in_person",
                default="in_person",
                max_length=10,
                verbose_name="Teilnahmeart",
            ),
        ),
        migrations.CreateModel(
            name="SessionAttendanceDisruption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.TimeField(verbose_name="Beginn")),
                (
                    "ended_at",
                    models.TimeField(
                        blank=True,
                        help_text="Leer: Die Störung dauert an",
                        null=True,
                        verbose_name="Ende",
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("connection", "Verbindung abgebrochen"),
                            ("audio", "Ton gestört"),
                            ("video", "Bild gestört"),
                            ("other", "Sonstige Ursache"),
                        ],
                        default="connection",
                        max_length=20,
                        verbose_name="Ursache",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Nur intern",
                        max_length=255,
                        verbose_name="Vermerk",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disruptions",
                        to="session.sessionattendance",
                        verbose_name="Anwesenheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Störungsvermerk",
                "verbose_name_plural": "Störungsvermerke",
                "db_table": "session_attendance_disruptions",
                "ordering": ["started_at", "created_at"],
            },
        ),
    ]
