# Generated by Django 6.0.6 on 2026-09-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0048_teilnahmeart"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="oparl_license",
            field=models.URLField(
                blank=True,
                db_default="",
                default="",
                help_text="URL der Lizenz, unter der die OParl-Schnittstelle die Daten anbietet; leer: keine Angabe",
                max_length=255,
                verbose_name="Lizenz der offenen Daten",
            ),
        ),
        migrations.AddField(
            model_name="sessiontenant",
            name="oparl_license_valid_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, seit dem die angegebene Lizenz gilt (OParl ``licenseValidSince``)",
                null=True,
                verbose_name="Lizenz gültig seit",
            ),
        ),
    ]
