# Generated by Django 6.0.6 on 2026-10-01 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0052_absage_abgleichen"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="dcat_contributor_id",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Kennung als Datenbereitsteller (http://dcat-ap.de/def/contributors/…), vergeben bei der Anmeldung bei GovData; erscheint im Datenkatalog an jedem Datensatz. Leer: keine Angabe",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^http://dcat-ap\\.de/def/contributors/[A-Za-z0-9_.-]+$",
                        "Bitte die Kennung aus der Liste von GovData angeben (http://dcat-ap.de/def/contributors/…).",
                    )
                ],
                verbose_name="Kennung bei GovData",
            ),
        ),
    ]
