# Generated by Django 6.0.6 on 2026-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0065_oeffentlichkeit_gremien"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontenant",
            name="hub_events",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Wie die Installation"),
                    ("aus", "Aus"),
                    ("schatten", "Schattenbetrieb"),
                    ("aktiv", "Aktiv"),
                ],
                db_default="",
                default="",
                help_text="Sitzungen, Tagesordnung und Ladung als Ereignisse melden; leer: wie die Installation (SESSION_EVENTS)",
                max_length=10,
                verbose_name="Ereignisse an die Datendrehscheibe",
            ),
        ),
    ]
