# Generated by Django 5.2.8 on 2026-01-12 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OParlBody",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("license", models.TextField(blank=True, null=True)),
                ("license_valid_since", models.DateTimeField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Körperschaft",
                "verbose_name_plural": "Körperschaften",
                "db_table": "oparl_bodies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OParlSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.TextField(unique=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("sync_config", models.JSONField(blank=True, default=dict)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OParl-Quelle",
                "verbose_name_plural": "OParl-Quellen",
                "db_table": "oparl_sources",
            },
        ),
        migrations.CreateModel(
            name="OParlMeeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "meeting_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cancelled", models.BooleanField(default=False)),
                ("start", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("location_address", models.TextField(blank=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="insight_core.oparlbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzung",
                "verbose_name_plural": "Sitzungen",
                "db_table": "oparl_meetings",
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="OParlAgendaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("number", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("public", models.BooleanField(default=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("resolution_text", models.TextField(blank=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="insight_core.oparlmeeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagesordnungspunkt",
                "verbose_name_plural": "Tagesordnungspunkte",
                "db_table": "oparl_agenda_items",
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="OParlOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "organization_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="insight_core.oparlbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gremium",
                "verbose_name_plural": "Gremien",
                "db_table": "oparl_organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OParlPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("paper_type", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, null=True)),
                ("locations", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="insight_core.oparlbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorgang",
                "verbose_name_plural": "Vorgänge",
                "db_table": "oparl_papers",
                "ordering": ["-date", "-oparl_created"],
            },
        ),
        migrations.CreateModel(
            name="OParlFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("access_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "download_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("local_path", models.TextField(blank=True, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="insight_core.oparlpaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datei",
                "verbose_name_plural": "Dateien",
                "db_table": "oparl_files",
            },
        ),
        migrations.CreateModel(
            name="OParlPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "family_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("given_name", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="insight_core.oparlbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
                "db_table": "oparl_persons",
                "ordering": ["family_name", "given_name"],
            },
        ),
        migrations.CreateModel(
            name="OParlMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("voting_right", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="insight_core.oparlorganization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="insight_core.oparlperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitgliedschaft",
                "verbose_name_plural": "Mitgliedschaften",
                "db_table": "oparl_memberships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bodies",
                to="insight_core.oparlsource",
            ),
        ),
    ]
