# Generated by Django 6.0.1 on 2026-01-13 06:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OParlConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("paper_external_id", models.TextField(blank=True, null=True)),
                ("meeting_external_id", models.TextField(blank=True, null=True)),
                ("agenda_item_external_id", models.TextField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("authoritative", models.BooleanField(default=False)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="insight_core.oparlbody",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="insight_core.oparlpaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beratung",
                "verbose_name_plural": "Beratungen",
                "db_table": "oparl_consultations",
            },
        ),
        migrations.CreateModel(
            name="OParlLegislativeTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legislative_terms",
                        to="insight_core.oparlbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wahlperiode",
                "verbose_name_plural": "Wahlperioden",
                "db_table": "oparl_legislative_terms",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="OParlLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(db_index=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("room", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("locality", models.CharField(blank=True, max_length=255, null=True)),
                ("geojson", models.JSONField(blank=True, null=True)),
                ("oparl_created", models.DateTimeField(blank=True, null=True)),
                ("oparl_modified", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="insight_core.oparlbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ort",
                "verbose_name_plural": "Orte",
                "db_table": "oparl_locations",
            },
        ),
    ]
