# Generated by Django 6.0.1 on 2026-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0002_add_location_consultation_legislativeterm"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Kurzer Anzeigename für das Frontend (z.B. 'Köln' statt 'Stadt Köln, kreisfreie Stadt')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo der Kommune (empfohlen: quadratisch, min. 200x200px)",
                null=True,
                upload_to="bodies/logos/",
            ),
        ),
    ]
