# Generated by Django 6.0.1 on 2026-01-13 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0003_add_body_display_name_and_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oparlbody",
            options={
                "ordering": ["name"],
                "verbose_name": "OParl Kommune",
                "verbose_name_plural": "OParl Kommunen",
            },
        ),
        migrations.AlterField(
            model_name="oparlbody",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Logo der Kommune (SVG, PNG, JPG, WebP). Format wird automatisch angepasst.",
                null=True,
                upload_to="bodies/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg", "png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
