# Generated by Django 6.0.1 on 2026-01-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0004_change_logo_to_filefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="agenda_item_list_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="file_list_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="meeting_list_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="membership_list_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="organization_list_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="paper_list_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="person_list_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlsource",
            name="last_full_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
