# Generated by Django 6.0.1 on 2026-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0005_add_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlmeeting",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, related_name="meetings", to="insight_core.oparlorganization"
            ),
        ),
    ]
