# Generated by Django 6.0.1 on 2026-01-17 19:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0006_add_meeting_organizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="Der Name wie er in Sitzungen verwendet wird (z.B. 'Hauptausschusszimmer')",
                        max_length=500,
                        verbose_name="Ortsbezeichnung",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="z.B. 51.9617867",
                        max_digits=10,
                        verbose_name="Breitengrad",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="z.B. 7.6281645",
                        max_digits=10,
                        verbose_name="Längengrad",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Vollständige Adresse (optional)",
                        null=True,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Zusätzliche Informationen zum Ort",
                        null=True,
                        verbose_name="Beschreibung",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_mappings",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orts-Zuordnung",
                "verbose_name_plural": "Orts-Zuordnungen",
                "db_table": "location_mappings",
                "ordering": ["body", "location_name"],
                "unique_together": {("body", "location_name")},
            },
        ),
    ]
