# Generated by Django 6.0.1 on 2026-01-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0007_add_location_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="bbox_east",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="bbox_north",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="bbox_south",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="bbox_west",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Breitengrad des Zentrums (z.B. 51.9606649 für Münster)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Längengrad des Zentrums (z.B. 7.6261347 für Münster)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="osm_relation_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="OpenStreetMap Relation ID (z.B. 62591 für Münster)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TileCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("z", models.PositiveIntegerField(db_index=True)),
                ("x", models.PositiveIntegerField(db_index=True)),
                ("y", models.PositiveIntegerField(db_index=True)),
                ("tile_data", models.BinaryField()),
                ("content_type", models.CharField(default="image/png", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fetched_from",
                    models.CharField(default="openstreetmap", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Tile Cache",
                "verbose_name_plural": "Tile Cache",
                "db_table": "tile_cache",
                "indexes": [models.Index(fields=["z", "x", "y"], name="tile_cache_z_82dee3_idx")],
                "unique_together": {("z", "x", "y")},
            },
        ),
    ]
