# Generated by Django 6.0.1 on 2026-02-03 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlfile",
            name="body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="insight_core.oparlbody",
            ),
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="file_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="insight_core.oparlmeeting",
            ),
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="sha256_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
