# Generated by Django 6.0.1 on 2026-02-04 22:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "insight_core",
            "0009_oparlfile_body_oparlfile_file_date_oparlfile_meeting_and_more",
        ),
        ("work", "0019_add_contact_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Organisation"),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("demo", "Demo anfragen"),
                            ("preise", "Preisanfrage"),
                            ("support", "Support"),
                            ("datenschutz", "Datenschutz"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="sonstiges",
                        max_length=50,
                        verbose_name="Betreff",
                    ),
                ),
                ("message", models.TextField(verbose_name="Nachricht")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Neu"),
                            ("read", "Gelesen"),
                            ("in_progress", "In Bearbeitung"),
                            ("replied", "Beantwortet"),
                            ("converted", "Zu Ticket konvertiert"),
                            ("closed", "Geschlossen"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Interne Notizen"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-Adresse"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "notification_sent",
                    models.BooleanField(default=False, verbose_name="Benachrichtigung gesendet"),
                ),
                (
                    "confirmation_sent",
                    models.BooleanField(default=False, verbose_name="Bestätigung gesendet"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "linked_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_requests",
                        to="work.supportticket",
                        verbose_name="Verknüpftes Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontaktanfrage",
                "verbose_name_plural": "Kontaktanfragen",
                "db_table": "contact_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
