# Generated by Django 6.0.1 on 2026-02-10 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0011_text_extraction_and_seo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "questioner_name",
                    models.CharField(max_length=200, verbose_name="Name"),
                ),
                (
                    "questioner_email",
                    models.EmailField(max_length=254, verbose_name="E-Mail"),
                ),
                (
                    "questioner_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Wohnort"
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Betreff")),
                ("question_text", models.TextField(verbose_name="Frage")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "E-Mail nicht bestätigt"),
                            ("pending", "Wartet auf Moderation"),
                            ("published", "Veröffentlicht"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Ablehnungsgrund"),
                ),
                ("answer_text", models.TextField(blank=True, verbose_name="Antwort")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answer_status",
                    models.CharField(
                        choices=[
                            ("none", "Keine Antwort"),
                            ("pending", "Antwort wartet auf Moderation"),
                            ("published", "Antwort veröffentlicht"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                ("answer_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("privacy_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_questions",
                        to="insight_core.oparlbody",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_questions",
                        to="insight_core.oparlperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öffentliche Frage",
                "verbose_name_plural": "Öffentliche Fragen",
                "db_table": "insight_public_questions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="insight_pub_recipie_b0eb3a_idx",
                    ),
                    models.Index(
                        fields=["body", "status", "-created_at"],
                        name="insight_pub_body_id_8caa16_idx",
                    ),
                    models.Index(
                        fields=["verification_token"],
                        name="insight_pub_verific_be103c_idx",
                    ),
                    models.Index(
                        fields=["answer_token"], name="insight_pub_answer__d412fc_idx"
                    ),
                ],
            },
        ),
    ]
