# Generated by Django 6.0.1 on 2026-02-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0012_public_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Kurze Beschreibung der Kommune für die Portalseite (2-3 Sätze, z.B. 'Willkommen im Ratsinformationssystem der Stadt Münster...')",
                null=True,
            ),
        ),
    ]
