# Generated by Django 6.0.1 on 2026-02-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0013_oparlbody_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Bild der Kommune für die Portalseite (z.B. Stadtansicht, Rathaus). Empfohlen: 1920×1080px, Querformat.",
                null=True,
                upload_to="bodies/heroes/",
            ),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="hero_image_credit",
            field=models.CharField(
                blank=True,
                help_text="Bildnachweis (z.B. 'Foto: Max Mustermann, CC BY-SA 4.0')",
                max_length=255,
                null=True,
            ),
        ),
    ]
