# Generated by Django 6.0.3 on 2026-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_core', '0019_insight_subscriptions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatusage',
            new_name='chat_usage_ip_addr_ce6c94_idx',
            old_name='chat_usage_ip_address_creat_idx',
        ),
        migrations.RenameIndex(
            model_name='chatusage',
            new_name='chat_usage_session_be847a_idx',
            old_name='chat_usage_session_key_crea_idx',
        ),
        migrations.AlterField(
            model_name='oparlfile',
            name='text_extraction_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('ocr_needed', 'KI-OCR benötigt'), ('skipped', 'Übersprungen')], db_index=True, default='pending', help_text='Status der Textextraktion', max_length=20, verbose_name='Extraktionsstatus'),
        ),
    ]
