# Generated by Django 5.2.11 on 2026-07-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0020_org_wide_meeting_prep_phase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="ags",
            field=models.CharField(
                blank=True,
                help_text="Amtlicher Gemeindeschlüssel (8-stellig, z.B. 05515000 für Münster)",
                max_length=8,
                null=True,
                verbose_name="AGS",
            ),
        ),
        migrations.AddField(
            model_name="oparlpaper",
            name="oparl_locations",
            field=models.ManyToManyField(
                blank=True,
                db_table="oparl_papers_locations",
                related_name="papers",
                to="insight_core.oparllocation",
                verbose_name="OParl-Orte",
            ),
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.BigIntegerField(help_text="OpenStreetMap Way-ID")),
                ("name", models.CharField(max_length=255, verbose_name="Straßenname")),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("geometry", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streets",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Straße",
                "verbose_name_plural": "Straßen",
                "db_table": "insight_streets",
                "indexes": [
                    models.Index(
                        fields=["body", "normalized_name"], name="idx_street_body_norm"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("body", "osm_id"), name="uniq_street_body_osm"
                    )
                ],
            },
        ),
    ]
