# Generated by Django 5.2.11 on 2026-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0021_street_gazetteer_paper_locations_ags"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlagendaitem",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlagendaitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlbody",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlconsultation",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlconsultation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparllegislativeterm",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparllegislativeterm",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparllocation",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparllocation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlmeeting",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlmeeting",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlmembership",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlmembership",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlorganization",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlorganization",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlpaper",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlpaper",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlperson",
            name="deleted",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Wurde vom Quellsystem als gelöscht markiert (OParl-Tombstone).",
                verbose_name="In Quelle gelöscht",
            ),
        ),
        migrations.AddField(
            model_name="oparlperson",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt, zu dem die Löschung in der Quelle erkannt wurde.",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
    ]
