# Generated by Django 6.0.6 on 2026-09-08 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0025_file_cache"),
        ("session", "0024_beschluss_tracking_veroeffentlichung"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_subscriptions",
                        to="session.sessionagendaitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beschluss-Abo",
                "verbose_name_plural": "Beschluss-Abos",
                "db_table": "insight_decision_subscriptions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agenda_item", "email"),
                        name="uniq_decision_subscription",
                    )
                ],
            },
        ),
    ]
