# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.0.6 on 2026-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0026_decision_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oparlbody",
            name="website",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="oparlfile",
            name="local_error",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=500,
                verbose_name="Cache-Fehler",
            ),
        ),
        migrations.AlterField(
            model_name="oparlfile",
            name="local_status",
            field=models.CharField(
                choices=[
                    ("none", "Nicht zwischengespeichert"),
                    ("ok", "Lokal vorhanden"),
                    ("missing", "Quelle liefert 404"),
                    ("error", "Fehler beim Abruf"),
                    ("too_large", "Zu groß für den Cache"),
                ],
                db_default="none",
                db_index=True,
                default="none",
                max_length=20,
                verbose_name="Lokale Kopie",
            ),
        ),
        migrations.AlterField(
            model_name="oparlorganization",
            name="website",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="oparlperson",
            name="photo_error",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="oparlperson",
            name="photo_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Noch nicht geprüft"),
                    ("ok", "Foto vorhanden"),
                    ("missing", "Kein Foto im RIS"),
                    ("error", "Fehler beim Abruf"),
                    ("manual", "Manuell hochgeladen"),
                ],
                db_default="unknown",
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="oparlsource",
            name="website",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
