# Generated by Django 6.0.6 on 2026-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0028_oparlbody_is_listed"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="oparlmeeting",
            index=models.Index(
                fields=["body", "start"], name="oparl_meeting_body_start"
            ),
        ),
        migrations.AddIndex(
            model_name="oparlpaper",
            index=models.Index(
                fields=["body", "-date", "-oparl_created"],
                name="oparl_paper_body_datum",
            ),
        ),
    ]
