# Generated by Django 6.1.1 on 2026-09-25 14:42
#
# Bürgerportal je Körperschaft (Issue #317): Akzentfarbe der Kommune im eigenen Einstieg. Die Spalte
# ist nullable, weil der Ingestor sie nicht kennt (Schema-Contract, docs/adr/20260909-…).

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0034_geo_automatik"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="accent_color",
            field=models.CharField(
                blank=True,
                help_text="Hexadezimal, z. B. #1e40af. Leer: Primärfarbe des Session-Mandanten, sonst mandari-Farben.",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Bitte eine Farbe im Format #1a2b3c angeben."
                    )
                ],
                verbose_name="Akzentfarbe im eigenen Portal",
            ),
        ),
    ]
