# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-26 18:13
"""
Bestätigungslink öffentlicher Fragen nur als Hash speichern (apps/common/tokens.py).

1. Die Spalte ``verification_token`` wird von UUID zu Text (64 Zeichen); PostgreSQL übernimmt die
   UUID dabei in der Form mit Bindestrichen, SQLite als 32 Hex-Zeichen.
2. Jede UUID wird in die Form aus den verschickten Links gebracht (klein, mit Bindestrichen) und
   gehasht. Bereits verschickte Bestätigungslinks funktionieren weiter, weil die Anwendung das Token
   aus dem Link ebenso hasht. Werte, die keine UUID sind (schon gehasht), bleiben unverändert.

Rückwärts bekommt jede Frage eine neue, zufällige UUID, damit die Spalte wieder UUIDs aufnehmen kann;
offene Bestätigungslinks werden dabei ungültig.
"""

import hashlib
import uuid

import apps.common.tokens
from django.db import migrations, models


def _as_uuid(value: str) -> uuid.UUID | None:
    try:
        return uuid.UUID(str(value))
    except ValueError:
        return None


def hash_tokens(apps, schema_editor):
    model = apps.get_model("insight_core", "PublicQuestion")
    changed = []
    for pk, value in list(model.objects.values_list("pk", "verification_token")):
        token = _as_uuid(value) if value and len(str(value)) != 64 else None
        if token is None:
            continue
        digest = hashlib.sha256(str(token).encode("utf-8")).hexdigest()
        changed.append(model(pk=pk, verification_token=digest))
    model.objects.bulk_update(changed, ["verification_token"], batch_size=500)


def new_uuids(apps, schema_editor):
    model = apps.get_model("insight_core", "PublicQuestion")
    changed = [
        model(pk=pk, verification_token=str(uuid.uuid4())) for pk in list(model.objects.values_list("pk", flat=True))
    ]
    model.objects.bulk_update(changed, ["verification_token"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0036_zusammenfassungen_nach_ruecknahme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicquestion",
            name="verification_token",
            field=models.CharField(
                default=apps.common.tokens.unusable_token_hash,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="Bestätigungs-Token (SHA-256)",
            ),
        ),
        migrations.RunPython(hash_tokens, new_uuids),
    ]
