# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.0.6 on 2026-09-29 22:02
"""
Amtliche Umringe von Bebauungsplänen (Issue #598).

Nur neue Tabellen (Quellen, zwischengespeicherte Umringe, Bezüge der Vorgänge) und eine neue Auswahl
„Amtlicher Umring“ für die Herkunft einer Verortung (keine Änderung am Datenbankschema). Abwärtskompatibel:
Ein älteres Image kennt die Tabellen nicht und liest sie nicht; Verortungen mit der neuen Herkunft zeigt
es als Rohwert an. Der Ingestor schreibt keine dieser Tabellen.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0037_zugangstoken_als_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperlocation",
            name="source",
            field=models.CharField(
                choices=[
                    ("oparl", "OParl-Ort"),
                    ("address_match", "Adresse (Straßenverzeichnis)"),
                    ("street_match", "Straße (Straßenverzeichnis)"),
                    ("ai", "KI-Extraktion"),
                    ("manual", "Manuell"),
                    ("plan_boundary", "Amtlicher Umring (Bebauungsplan)"),
                ],
                default="street_match",
                max_length=20,
                verbose_name="Herkunft",
            ),
        ),
        migrations.CreateModel(
            name="PlanBoundarySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z. B. „Land NRW – rechtskräftige Bebauungspläne“",
                        max_length=200,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ogc_api_features", "OGC API – Features (z. B. Land NRW)"),
                            ("wfs", "WFS 2.0 mit GeoJSON-Ausgabe"),
                        ],
                        default="ogc_api_features",
                        max_length=20,
                        verbose_name="Art des Dienstes",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="OGC API: Adresse der Objektliste einer Sammlung (…/collections/<id>/items). WFS: Adresse des Dienstes ohne Parameter.",
                        max_length=1000,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Wert für TYPENAMES, z. B. ms:bplan2",
                        max_length=200,
                        verbose_name="Ebene (nur WFS)",
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='z. B. {"gkz": "05515000"} (NRW) oder {"OUTPUTFORMAT": "GEOJSON"} (MapServer-WFS)',
                        verbose_name="Zusätzliche Abfrageparameter",
                    ),
                ),
                (
                    "property_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Nur Objekte mit einem dieser Werte übernehmen, z. B. {"planTypeName.code": [1000]}',
                        verbose_name="Filter auf Eigenschaften",
                    ),
                ),
                (
                    "number_property",
                    models.CharField(
                        default="plannr",
                        help_text="Land NRW: nr (mit Änderungsnummer), MapServer-WFS der Stadt Münster: plannr",
                        max_length=100,
                        verbose_name="Eigenschaft: Plannummer",
                    ),
                ),
                (
                    "title_property",
                    models.CharField(
                        blank=True,
                        default="name",
                        max_length=100,
                        verbose_name="Eigenschaft: Bezeichnung des Plans",
                    ),
                ),
                (
                    "link_property",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Land NRW: officialDocument, Stadt Münster: scanurl",
                        max_length=100,
                        verbose_name="Eigenschaft: Link zur Planseite",
                    ),
                ),
                (
                    "plan_status",
                    models.CharField(
                        choices=[
                            ("in_force", "Rechtskräftig"),
                            ("in_procedure", "Im Verfahren"),
                        ],
                        default="in_force",
                        max_length=20,
                        verbose_name="Planstand",
                    ),
                ),
                (
                    "attribution",
                    models.CharField(
                        help_text="Steht im Portal an Karte und Umring, z. B. „Land NRW, Datenlizenz Deutschland – Namensnennung – 2.0“",
                        max_length=300,
                        verbose_name="Quellenangabe",
                    ),
                ),
                (
                    "license_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Lizenz (Link)",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Liefern mehrere Quellen denselben Plan, gewinnt die kleinere Zahl.",
                        verbose_name="Rang",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "last_attempt_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Letzter Abruf"),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Letzter erfolgreicher Abruf",
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Letzter Fehler",
                    ),
                ),
                (
                    "feature_count",
                    models.PositiveIntegerField(default=0, verbose_name="Umringe"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_boundary_sources",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umring-Quelle (Bebauungspläne)",
                "verbose_name_plural": "Umring-Quellen (Bebauungspläne)",
                "db_table": "insight_plan_boundary_sources",
                "ordering": ["body__name", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlanBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(max_length=300, verbose_name="Kennung in der Quelle"),
                ),
                (
                    "plan_number",
                    models.CharField(max_length=100, verbose_name="Plannummer (Quelle)"),
                ),
                (
                    "number_key",
                    models.CharField(max_length=100, verbose_name="Plannummer (normalisiert)"),
                ),
                (
                    "change_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nummer der Änderung, sofern die Quelle Änderungen getrennt führt",
                        max_length=20,
                        verbose_name="Änderung",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "plan_status",
                    models.CharField(
                        choices=[
                            ("in_force", "Rechtskräftig"),
                            ("in_procedure", "Im Verfahren"),
                        ],
                        default="in_force",
                        max_length=20,
                        verbose_name="Planstand",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Planseite",
                    ),
                ),
                ("geometry", models.JSONField(verbose_name="Umring (GeoJSON, WGS84)")),
                ("bbox_south", models.FloatField()),
                ("bbox_north", models.FloatField()),
                ("bbox_west", models.FloatField()),
                ("bbox_east", models.FloatField()),
                (
                    "point_lat",
                    models.FloatField(verbose_name="Punkt im Umring (Breite)"),
                ),
                (
                    "point_lon",
                    models.FloatField(verbose_name="Punkt im Umring (Länge)"),
                ),
                (
                    "area_m2",
                    models.FloatField(blank=True, null=True, verbose_name="Fläche (m²)"),
                ),
                ("fetched_at", models.DateTimeField(verbose_name="Abgerufen am")),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_boundaries",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundaries",
                        to="insight_core.planboundarysource",
                        verbose_name="Quelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amtlicher Umring",
                "verbose_name_plural": "Amtliche Umringe",
                "db_table": "insight_plan_boundaries",
                "ordering": ["body__name", "number_key", "change_number"],
            },
        ),
        migrations.CreateModel(
            name="PaperPlanReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_key",
                    models.CharField(max_length=100, verbose_name="Plannummer (normalisiert)"),
                ),
                (
                    "number_label",
                    models.CharField(max_length=100, verbose_name="Plannummer (Titel)"),
                ),
                (
                    "change_number",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="Änderung"),
                ),
                (
                    "match",
                    models.CharField(
                        choices=[
                            ("change", "Umring der genannten Änderung"),
                            ("procedure", "Umring des laufenden Verfahrens"),
                            ("plan", "Umring des Plans"),
                            ("base_plan", "Umring des Ursprungsplans"),
                            ("none", "Kein Umring gefunden"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=12,
                        verbose_name="Zuordnung",
                    ),
                ),
                ("matched_at", models.DateTimeField(verbose_name="Zuordnung vom")),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_references",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_references",
                        to="insight_core.oparlpaper",
                        verbose_name="Vorgang",
                    ),
                ),
                (
                    "boundaries",
                    models.ManyToManyField(
                        blank=True,
                        db_table="insight_paper_plan_reference_boundaries",
                        related_name="paper_references",
                        to="insight_core.planboundary",
                        verbose_name="Umringe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bebauungsplan eines Vorgangs",
                "verbose_name_plural": "Bebauungspläne der Vorgänge",
                "db_table": "insight_paper_plan_references",
                "ordering": ["-matched_at"],
                "indexes": [
                    models.Index(
                        fields=["body", "number_key"],
                        name="idx_paperplanref_body_number",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("paper", "number_key", "change_number"),
                        name="uniq_paperplanref_paper_number",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="planboundary",
            index=models.Index(fields=["body", "number_key"], name="idx_planboundary_body_number"),
        ),
        migrations.AddIndex(
            model_name="planboundary",
            index=models.Index(
                fields=["body", "bbox_south", "bbox_north"],
                name="idx_planboundary_body_bbox",
            ),
        ),
        migrations.AddConstraint(
            model_name="planboundary",
            constraint=models.UniqueConstraint(fields=("source", "feature_key"), name="uniq_planboundary_source_key"),
        ),
    ]
