# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-30 01:36
"""
Verzeichnis der Kommune im Dokument-Cache festschreiben (Issue #373).

Bisher leitete der Cache den Verzeichnisnamen bei jedem Zugriff aus Slug bzw. Kurznamen ab. Ein neuer
Slug hätte neue Downloads in ein zweites Verzeichnis gelenkt und ``prune_file_cache`` mit dem neuen
Namen rechnen lassen. Die neue Spalte hält den Namen fest; diese Migration schreibt für jede bestehende
Kommune genau den Namen fest, den der Cache heute verwendet. Auf der Platte ändert sich nichts,
``OParlFile.local_path`` bleibt unverändert.

Abwärtskompatibel: Die Spalte ist nullable und nur Django bekannt (der Ingestor legt Kommunen ohne sie
an). Ein älteres Image ignoriert sie. Die Änderung am Slug betrifft nur Validierung und Hilfetext (kein SQL).

Die Datenmigration ist idempotent (nur leere Einträge) und ``elidable``: Auf einer frischen Datenbank
gibt es keine Kommunen, spätere schreibt ``file_cache.pin_body_dir`` beim ersten Ablegen fest.
"""

from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify

import insight_core.models

# Eingefrorene Kopie der bisherigen Ableitung aus insight_core/services/file_cache.py (body_dir_name)
_UMLAUTS = str.maketrans({"ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss", "Ä": "Ae", "Ö": "Oe", "Ü": "Ue"})
MAX_DIR_NAME = 255


def bisheriger_name(slug, short_name, name, pk) -> str:
    if slug:
        return str(slug)
    return slugify((short_name or name or "").translate(_UMLAUTS)) or str(pk)


def festschreiben(apps, schema_editor):
    OParlBody = apps.get_model("insight_core", "OParlBody")
    offen = OParlBody.objects.filter(Q(file_cache_dir__isnull=True) | Q(file_cache_dir=""))
    stapel = []
    for body in offen.only("id", "slug", "short_name", "name").iterator(chunk_size=500):
        name = bisheriger_name(body.slug, body.short_name, body.name, body.pk)
        if len(name) > MAX_DIR_NAME:
            continue  # Solch ein Verzeichnis ließ sich nie anlegen – nichts festzuhalten
        body.file_cache_dir = name
        stapel.append(body)
        if len(stapel) >= 500:
            OParlBody.objects.bulk_update(stapel, ["file_cache_dir"])
            stapel = []
    if stapel:
        OParlBody.objects.bulk_update(stapel, ["file_cache_dir"])


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0038_bebauungsplan_umringe"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="file_cache_dir",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Wird beim ersten Zwischenspeichern festgelegt und danach nicht mehr geändert.",
                max_length=255,
                null=True,
                verbose_name="Verzeichnis im Dokument-Cache",
            ),
        ),
        migrations.AlterField(
            model_name="oparlbody",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "URL-freundlicher Identifikator (z.B. 'muenster' für Münster): Bürgerportal unter "
                    "/insight/k/<slug>/ und Sitemap. Kleinbuchstaben, Ziffern und Bindestriche. Ändern macht "
                    "bisherige Links ungültig."
                ),
                max_length=100,
                null=True,
                unique=True,
                validators=[insight_core.models.validate_body_slug],
            ),
        ),
        migrations.RunPython(festschreiben, migrations.RunPython.noop, elidable=True),
    ]
