# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.0.6 on 2026-10-01 16:02
"""
Hinweis je Kommune im Bürgerportal (Issue #734), z. B. wenn die Kommune ihre Daten nicht mehr bereitstellt.

Abwärtskompatibel: Die Spalte hat einen Datenbank-Default (leerer Text). Der Ingestor und ein älteres Image
legen Kommunen ohne sie an; ein älteres Image ignoriert sie beim Lesen. Keine Datenmigration – der Text für
eine Kommune wird nach dem Deploy im Admin gesetzt.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0039_oparlbody_file_cache_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlbody",
            name="portal_notice",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text=(
                    "Wird auf Einstieg und Listenseiten der Kommune angezeigt, z. B. „Die Stadt hat die "
                    "Bereitstellung ihrer Daten über die OParl-Schnittstelle zum … beendet.“ Leer: kein Hinweis."
                ),
                max_length=1000,
                verbose_name="Hinweis im Bürgerportal",
            ),
        ),
    ]
