# Generated by Django 6.0.6 on 2026-10-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0040_oparlbody_portal_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlfile",
            name="local_size",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Größe der Kopie (Bytes)"),
        ),
        migrations.CreateModel(
            name="OParlFileAccessDay",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.DateField(verbose_name="Tag")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("hit", "Treffer (lokale Kopie)"),
                            ("miss", "Fehlzugriff (von der Quelle geholt)"),
                            (
                                "failed",
                                "Nicht ausgeliefert (Quelle nicht erreichbar, zu groß, gedrosselt)",
                            ),
                            ("blocked", "Gesperrt"),
                        ],
                        max_length=16,
                        verbose_name="Ergebnis",
                    ),
                ),
                (
                    "age_class",
                    models.CharField(
                        choices=[
                            ("d30", "jünger als 30 Tage"),
                            ("d365", "30 Tage bis 1 Jahr"),
                            ("y3", "1 bis 3 Jahre"),
                            ("older", "älter als 3 Jahre"),
                            ("unknown", "unbekannt"),
                        ],
                        max_length=16,
                        verbose_name="Alter des Dokuments",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="Abrufe"),
                ),
                (
                    "bytes",
                    models.BigIntegerField(default=0, verbose_name="Bytes (Dateigröße je Abruf)"),
                ),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_access_days",
                        to="insight_core.oparlbody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumentabrufe je Tag",
                "verbose_name_plural": "Dokumentabrufe je Tag",
                "db_table": "oparl_file_access_days",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "body", "outcome", "age_class"),
                        name="oparl_file_access_day_key",
                    )
                ],
            },
        ),
    ]
