# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.0.6 on 2026-10-03 16:32
"""
Anonyme Rückmeldung „War diese Seite hilfreich?“ im Bürgerportal: neue Tabelle, abwärtskompatibel
(ältere Images kennen sie nicht und lassen sie unberührt).
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0040_oparlbody_portal_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(db_index=True, max_length=50, verbose_name="Seitentyp"),
                ),
                (
                    "path",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Seite"),
                ),
                ("helpful", models.BooleanField(verbose_name="Hilfreich")),
                (
                    "comment",
                    models.TextField(blank=True, default="", max_length=500, verbose_name="Ergänzung"),
                ),
                (
                    "created_on",
                    models.DateField(auto_now_add=True, db_index=True, verbose_name="Tag"),
                ),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_feedback",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rückmeldung zu einer Seite",
                "verbose_name_plural": "Rückmeldungen zu Seiten",
                "db_table": "insight_page_feedback",
                "ordering": ["-created_on", "-id"],
            },
        ),
    ]
