# Generated by Django 6.0.6 on 2026-10-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0041_dateigroesse_zugriffsprotokoll"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlfile",
            name="content_purged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Nach dem Löschabgleich.",
                null=True,
                verbose_name="Kopie und Text gelöscht am",
            ),
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="source_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Mit der Quelle abgeglichen am"
            ),
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="source_missing_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Download-Adresse liefert 404/410: gesperrt, Kopie und Text werden nach der Frist gelöscht.",
                null=True,
                verbose_name="In der Quelle nicht mehr abrufbar seit",
            ),
        ),
    ]
