# Generated by Django 6.0.6 on 2026-10-03 17:39

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0042_loeschabgleich"),
    ]

    operations = [
        migrations.CreateModel(
            name="OParlFileBlob",
            fields=[
                (
                    "sha256",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("size", models.BigIntegerField(verbose_name="Größe (Bytes)")),
                (
                    "ref_count",
                    models.IntegerField(
                        db_default=0, default=0, verbose_name="Referenzen"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                        verbose_name="Abgelegt am",
                    ),
                ),
                (
                    "orphaned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ohne Referenz seit"
                    ),
                ),
                (
                    "remote_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Im Objektspeicher seit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dateiinhalt",
                "verbose_name_plural": "Dateiinhalte",
                "db_table": "oparl_file_blobs",
            },
        ),
        migrations.AddField(
            model_name="oparlfile",
            name="blob",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="files",
                to="insight_core.oparlfileblob",
                verbose_name="Inhalt in der Ablage",
            ),
        ),
    ]
