# Generated by Django 6.0.6 on 2026-10-07 04:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0052_quelle_aktualitaet"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonFraktion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=200, verbose_name="Fraktion"),
                ),
                (
                    "partei",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Partei"
                    ),
                ),
                (
                    "gueltig_ab",
                    models.DateField(blank=True, null=True, verbose_name="Gültig ab"),
                ),
                (
                    "gueltig_bis",
                    models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
                ),
                (
                    "quelle",
                    models.CharField(
                        choices=[
                            ("einblendung", "Einblendung der Live-Übertragung"),
                            ("hand", "Von Hand gepflegt"),
                            ("oparl", "Ratsinformationssystem (OParl)"),
                        ],
                        default="hand",
                        max_length=20,
                        verbose_name="Quelle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("bestaetigt", "Bestätigt"),
                            ("vorschlag", "Vorschlag"),
                            ("abgelehnt", "Abgelehnt"),
                        ],
                        default="bestaetigt",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "belege",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Wie oft die Einblendung einer Live-Übertragung diese Fraktion gezeigt hat.",
                        verbose_name="Lesungen",
                    ),
                ),
                (
                    "zuletzt_gesehen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt gelesen"
                    ),
                ),
                (
                    "angelegt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Angelegt"),
                ),
                (
                    "geaendert",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert"),
                ),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_fraktionen",
                        to="insight_core.oparlbody",
                        verbose_name="Körperschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: die Fraktion als Gremium im Ratsinformationssystem, falls es sie dort gibt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_fraktionen",
                        to="insight_core.oparlorganization",
                        verbose_name="Gremium im RIS",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fraktionen_lokal",
                        to="insight_core.oparlperson",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraktionszuordnung",
                "verbose_name_plural": "Fraktionszuordnungen",
                "db_table": "insight_person_fraktionen",
                "ordering": ["-geaendert"],
                "indexes": [
                    models.Index(
                        fields=["body", "status"], name="personfraktion_body_status"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("gueltig_bis__isnull", True), ("status", "bestaetigt")
                        ),
                        fields=("person", "body"),
                        name="personfraktion_eine_laufende",
                    ),
                    models.UniqueConstraint(
                        models.F("person"),
                        models.F("body"),
                        django.db.models.functions.text.Lower("bezeichnung"),
                        condition=models.Q(("status", "vorschlag")),
                        name="personfraktion_ein_vorschlag_je_bezeichnung",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("gueltig_ab__isnull", True),
                            ("gueltig_bis__isnull", True),
                            ("gueltig_bis__gte", models.F("gueltig_ab")),
                            _connector="OR",
                        ),
                        name="personfraktion_zeitraum",
                    ),
                ],
            },
        ),
    ]
