# Generated by Django 6.0.6 on 2026-10-07 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0053_person_fraktion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonFraktionBeleg",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wortmeldung",
                    models.UUIDField(
                        help_text="Kennung der Wortmeldung in hub.live",
                        unique=True,
                        verbose_name="Wortmeldung",
                    ),
                ),
                (
                    "angelegt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Verbucht"),
                ),
                (
                    "zuordnung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="belege_wortmeldungen",
                        to="insight_core.personfraktion",
                        verbose_name="Fraktionszuordnung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beleg einer Fraktionszuordnung",
                "verbose_name_plural": "Belege von Fraktionszuordnungen",
                "db_table": "insight_person_fraktion_belege",
            },
        ),
    ]
