# Generated by Django 6.1.1 on 2026-10-09 14:13
"""
Obergrenze des Dokument-Caches (Issue #961), nur additiv:

* ``local_accessed_at``: zuletzt über die Vorschau ausgeliefert (nullable, ohne Default; der Ingestor kennt die
  Spalte nicht und schreibt sie nie). Ein reines ``ADD COLUMN`` ohne Default, in PostgreSQL ohne Umschreiben.
* Status ``evicted`` („Verdrängt“) in den Auswahlwerten von ``local_status``; ändert nichts in der Datenbank.

Nummer 0056: ``0055`` ist für die Dokumentkette (#919) vorgesehen. Wird sie zuerst gemergt, hängt diese Migration
beim Rebase an ``0055_dokumentkette_abruf`` statt an ``0054``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0054_person_fraktion_beleg"),
    ]

    operations = [
        migrations.AddField(
            model_name="oparlfile",
            name="local_accessed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Zuletzt ausgeliefert am"),
        ),
        migrations.AlterField(
            model_name="oparlfile",
            name="local_status",
            field=models.CharField(
                choices=[
                    ("none", "Nicht zwischengespeichert"),
                    ("ok", "Lokal vorhanden"),
                    ("missing", "Quelle liefert 404"),
                    ("error", "Fehler beim Abruf"),
                    ("too_large", "Zu groß für den Cache"),
                    ("evicted", "Verdrängt (bei Bedarf neu abrufbar)"),
                ],
                db_default="none",
                db_index=True,
                default="none",
                max_length=20,
                verbose_name="Lokale Kopie",
            ),
        ),
    ]
