# Generated by Django 6.0.1 on 2026-02-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insight_core", "0014_hero_image_for_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Daemon pausieren/fortsetzen",
                        verbose_name="Sync aktiv",
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minuten zwischen inkrementellen Syncs",
                        verbose_name="Intervall (Minuten)",
                    ),
                ),
                (
                    "full_sync_hour",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Stunde (0–23) für den täglichen Full Sync",
                        verbose_name="Full-Sync-Stunde",
                    ),
                ),
                (
                    "max_concurrent",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Max. gleichzeitige Requests"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert"),
                ),
            ],
            options={
                "verbose_name": "Sync-Einstellung",
                "verbose_name_plural": "Sync-Einstellungen",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("incremental", "Inkrementell"),
                            ("full", "Vollständig"),
                        ],
                        max_length=20,
                        verbose_name="Sync-Typ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Läuft"),
                            ("success", "Erfolgreich"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gestartet"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Beendet"),
                ),
                (
                    "duration_seconds",
                    models.FloatField(blank=True, null=True, verbose_name="Dauer (s)"),
                ),
                (
                    "entities_synced",
                    models.IntegerField(default=0, verbose_name="Entitäten"),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="Fehler"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        help_text="admin, daemon, cli",
                        max_length=20,
                        verbose_name="Ausgelöst durch",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Entitäten-Zähler pro Typ",
                        verbose_name="Details",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leer = alle Quellen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="insight_core.oparlsource",
                        verbose_name="Quelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync-Protokoll",
                "verbose_name_plural": "Sync-Protokolle",
                "ordering": ["-started_at"],
            },
        ),
    ]
