# Generated by Django 6.0.6 on 2026-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_sync", "0001_sync_log_and_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncconfig",
            name="full_sync_hour",
            field=models.PositiveIntegerField(
                default=99,
                help_text="Stunde (0–23) für den täglichen Full Sync. Wert > 23 = deaktiviert.",
                verbose_name="Full-Sync-Stunde",
            ),
        ),
    ]
