# Generated by Django 6.0.6 on 2026-09-10 03:28

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("session", "0024_beschluss_tracking_veroeffentlichung"),
        ("tenants", "0020_eigene_absender_mail"),
        ("work", "0051_verwaltung_einreichung"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolStyle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Bezeichnung")),
                (
                    "protocol_type",
                    models.CharField(
                        choices=[
                            ("resolution", "Beschlussprotokoll"),
                            ("result", "Ergebnisprotokoll"),
                            ("summary", "Verlaufsprotokoll (zusammengefasst)"),
                            ("verbatim", "Wortprotokoll"),
                        ],
                        default="result",
                        max_length=30,
                        verbose_name="Protokollart",
                    ),
                ),
                (
                    "style_notes",
                    models.TextField(blank=True, verbose_name="Hinweise zur Form"),
                ),
                (
                    "example_protocol_ids",
                    models.JSONField(default=list, verbose_name="Beispielprotokolle"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Voreinstellung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_styles",
                        to="tenants.organization",
                        verbose_name="Organisation (Work)",
                    ),
                ),
                (
                    "session_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_styles",
                        to="session.sessiontenant",
                        verbose_name="Mandant (Session)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokollform",
                "verbose_name_plural": "Protokollformen",
                "db_table": "minutes_protocol_styles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Vorbereitet"),
                            ("recording", "Läuft"),
                            ("paused", "Pausiert"),
                            ("finished", "Beendet"),
                            ("processing", "In Verarbeitung"),
                            ("ready", "Entwurf liegt vor"),
                            ("purged", "Gelöscht"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Begonnen am"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Beendet am"
                    ),
                ),
                (
                    "notice_given_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Hinweis auf Aufzeichnung erteilt am",
                    ),
                ),
                (
                    "retention_until",
                    models.DateTimeField(verbose_name="Spätestens löschen am"),
                ),
                (
                    "purged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faction_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="work.factionmeeting",
                        verbose_name="Fraktionssitzung",
                    ),
                ),
                (
                    "session_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="session.sessionmeeting",
                        verbose_name="Sitzung (Session)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufzeichnung",
                "verbose_name_plural": "Aufzeichnungen",
                "db_table": "minutes_recordings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecordingSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Öffentlich"),
                            ("non_public", "Nichtöffentlich"),
                            ("excluded", "Von der Aufzeichnung ausgenommen"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Vertraulichkeit",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Beginn")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                (
                    "audio_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Audio-Objektschlüssel"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Dauer (s)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faction_agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recording_segments",
                        to="work.factionagendaitem",
                        verbose_name="TOP (Fraktion)",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="minutes.recording",
                        verbose_name="Aufzeichnung",
                    ),
                ),
                (
                    "session_agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recording_segments",
                        to="session.sessionagendaitem",
                        verbose_name="TOP (Session)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufzeichnungsabschnitt",
                "verbose_name_plural": "Aufzeichnungsabschnitte",
                "db_table": "minutes_recording_segments",
                "ordering": ["recording", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Entwurfstext"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Modell"),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Prompt-Version"
                    ),
                ),
                (
                    "processing_target",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Verarbeitungsziel"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Übernommen am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="minutes.protocolstyle",
                        verbose_name="Protokollform",
                    ),
                ),
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="minutes.recordingsegment",
                        verbose_name="Abschnitt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokollentwurf",
                "verbose_name_plural": "Protokollentwürfe",
                "db_table": "minutes_protocol_drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("granted_at", models.DateTimeField(verbose_name="Erteilt am")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Widerrufen am"
                    ),
                ),
                (
                    "consent_text_version",
                    models.CharField(
                        max_length=50, verbose_name="Fassung des Einwilligungstextes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_consents",
                        to="tenants.membership",
                        verbose_name="Mitglied (Work)",
                    ),
                ),
                (
                    "session_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_consents",
                        to="session.sessionperson",
                        verbose_name="Person (Session)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einwilligung Stimmprofil",
                "verbose_name_plural": "Einwilligungen Stimmprofil",
                "db_table": "minutes_speaker_consents",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("transcribe", "Transkription"),
                            ("diarize", "Sprechertrennung"),
                            ("draft", "Protokollentwurf"),
                        ],
                        max_length=20,
                        verbose_name="Schritt",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Wartet"),
                            ("running", "Läuft"),
                            ("succeeded", "Erfolgreich"),
                            ("failed", "Fehlgeschlagen"),
                            ("skipped", "Übersprungen"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Verfahren"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Modell"),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Prompt-Version"
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Versuche"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Fehler")),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="minutes.recordingsegment",
                        verbose_name="Abschnitt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verarbeitungsauftrag",
                "verbose_name_plural": "Verarbeitungsaufträge",
                "db_table": "minutes_transcription_jobs",
                "ordering": ["queued_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_ms", models.PositiveIntegerField(verbose_name="Beginn (ms)")),
                ("end_ms", models.PositiveIntegerField(verbose_name="Ende (ms)")),
                (
                    "text_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Text"),
                ),
                (
                    "speaker_label",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sprecher-Label"
                    ),
                ),
                (
                    "attribution_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Protokollführung"),
                            ("mic_channel", "Mikrofonkanal"),
                            ("speaker_list", "Rednerliste"),
                            ("voice_profile", "Stimmprofil"),
                            ("diarization", "Sprechertrennung"),
                        ],
                        max_length=20,
                        verbose_name="Herkunft der Zuordnung",
                    ),
                ),
                (
                    "attribution_confidence",
                    models.FloatField(default=0.0, verbose_name="Konfidenz"),
                ),
                (
                    "needs_confirmation",
                    models.BooleanField(default=True, verbose_name="Bestätigung nötig"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bestätigt am"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcript_segments",
                        to="tenants.membership",
                        verbose_name="Mitglied (Work)",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="minutes.recordingsegment",
                        verbose_name="Abschnitt",
                    ),
                ),
                (
                    "session_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcript_segments",
                        to="session.sessionperson",
                        verbose_name="Person (Session)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transkriptabschnitt",
                "verbose_name_plural": "Transkriptabschnitte",
                "db_table": "minutes_transcript_segments",
                "ordering": ["segment", "start_ms"],
            },
        ),
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "embedding_encrypted",
                    models.BinaryField(verbose_name="Stimmprofil (verschlüsselt)"),
                ),
                ("model_name", models.CharField(max_length=200, verbose_name="Modell")),
                (
                    "sample_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Anzahl Stimmproben"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profile",
                        to="minutes.speakerconsent",
                        verbose_name="Einwilligung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stimmprofil",
                "verbose_name_plural": "Stimmprofile",
                "db_table": "minutes_voice_profiles",
            },
        ),
        migrations.AddConstraint(
            model_name="recording",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("faction_meeting__isnull", True),
                        ("session_meeting__isnull", False),
                    ),
                    models.Q(
                        ("faction_meeting__isnull", False),
                        ("session_meeting__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="minutes_recording_exactly_one_meeting",
            ),
        ),
        migrations.AddIndex(
            model_name="recordingsegment",
            index=models.Index(
                fields=["recording", "order"], name="minutes_rec_recordi_b47651_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="speakerconsent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("membership__isnull", True), ("session_person__isnull", False)
                    ),
                    models.Q(
                        ("membership__isnull", False), ("session_person__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="minutes_consent_exactly_one_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptionjob",
            index=models.Index(
                fields=["status", "stage"], name="minutes_tra_status_648465_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["segment", "start_ms"], name="minutes_tra_segment_9982d3_idx"
            ),
        ),
    ]
