# Generated by Django 6.0.6 on 2026-09-10 10:24

import apps.minutes.orchestrator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Erst einschalten, wenn Zugangsdaten, Image und Worker bereitstehen. Aus = es wird nie eine VM erstellt.",
                        verbose_name="Rechenknoten aktiv",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        default="https://ccenter.centron.de/api/v1",
                        verbose_name="API-Basis-URL",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Client-ID"
                    ),
                ),
                (
                    "client_secret_encrypted",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Client-Secret"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="OAuth-Scope"
                    ),
                ),
                (
                    "project_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Projekt-ID"
                    ),
                ),
                (
                    "pool",
                    models.CharField(
                        blank=True,
                        help_text="Kennung des GPU-Pools, in dem die VM entsteht.",
                        max_length=100,
                        verbose_name="Pool",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="Standard: Ubuntu 24.04 (GPU-fähig). Alternativ ein eigenes, vorbereitetes Image.",
                        max_length=200,
                        verbose_name="Image",
                    ),
                ),
                (
                    "prepared_image",
                    models.BooleanField(
                        default=False,
                        help_text="Image enthält NVIDIA-Treiber, Docker und Container Toolkit. Verkürzt den Start von ~15 auf ~3 Minuten.",
                        verbose_name="Vorbereitetes Image",
                    ),
                ),
                (
                    "gpu_model",
                    models.CharField(
                        default="Quadro RTX 6000",
                        max_length=100,
                        verbose_name="GPU-Modell",
                    ),
                ),
                (
                    "cores",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="CPU-Kerne"
                    ),
                ),
                (
                    "memory_gb",
                    models.PositiveSmallIntegerField(
                        default=32, verbose_name="Arbeitsspeicher (GB)"
                    ),
                ),
                (
                    "disk_gb",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Nur für Modellgewichte. Audio und Transkripte liegen ausschließlich im RAM.",
                        verbose_name="Festplatte (GB)",
                    ),
                ),
                (
                    "ssh_public_key",
                    models.TextField(
                        blank=True,
                        help_text="Optional, nur zur Fehlersuche. Leer = kein SSH-Zugang hinterlegt.",
                        verbose_name="SSH-Schlüssel (öffentlich)",
                    ),
                ),
                (
                    "worker_image",
                    models.CharField(
                        default="ghcr.io/mandarioss/transcriber:latest",
                        max_length=300,
                        verbose_name="Worker-Container",
                    ),
                ),
                (
                    "mandari_url",
                    models.URLField(
                        blank=True,
                        help_text="Unter dieser Adresse holen sich Knoten ihre Aufträge. Leer = SITE_URL.",
                        verbose_name="mandari-Adresse für Knoten",
                    ),
                ),
                (
                    "s3_endpoint",
                    models.URLField(blank=True, verbose_name="S3-Endpunkt"),
                ),
                (
                    "s3_bucket",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="S3-Bucket"
                    ),
                ),
                (
                    "s3_access_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="S3-Access-Key"
                    ),
                ),
                (
                    "s3_secret_key_encrypted",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="S3-Secret-Key"
                    ),
                ),
                (
                    "max_nodes",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Höchstzahl gleichzeitiger Knoten"
                    ),
                ),
                (
                    "jobs_per_node",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Aufträge je Knoten"
                    ),
                ),
                (
                    "idle_minutes",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Leerlauf bis Abbau (Minuten)"
                    ),
                ),
                (
                    "provisioning_timeout_minutes",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Höchstdauer Bereitstellung (Minuten)"
                    ),
                ),
                (
                    "max_lifetime_hours",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Höchstlaufzeit je Knoten (Stunden)"
                    ),
                ),
                (
                    "billing_boundary_minute",
                    models.PositiveSmallIntegerField(
                        default=55,
                        help_text="centron rechnet stundenweise ab. Leerlaufende Knoten werden erst ab dieser Minute der laufenden Stunde gelöscht.",
                        verbose_name="Löschfenster ab Minute",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GPU-Rechenknoten",
                "verbose_name_plural": "GPU-Rechenknoten",
                "db_table": "minutes_compute_settings",
            },
        ),
        migrations.CreateModel(
            name="GpuNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Hostname"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (
                                apps.minutes.orchestrator.NodeState["REQUESTED"],
                                "Angefordert",
                            ),
                            (
                                apps.minutes.orchestrator.NodeState["PROVISIONING"],
                                "Wird bei centron erstellt",
                            ),
                            (
                                apps.minutes.orchestrator.NodeState["BOOTING"],
                                "Wird eingerichtet",
                            ),
                            (apps.minutes.orchestrator.NodeState["READY"], "Bereit"),
                            (apps.minutes.orchestrator.NodeState["BUSY"], "Arbeitet"),
                            (
                                apps.minutes.orchestrator.NodeState["DELETING"],
                                "Wird gelöscht",
                            ),
                            (
                                apps.minutes.orchestrator.NodeState["DELETED"],
                                "Gelöscht",
                            ),
                            (
                                apps.minutes.orchestrator.NodeState["FAILED"],
                                "Fehlgeschlagen",
                            ),
                        ],
                        default=apps.minutes.orchestrator.NodeState["REQUESTED"],
                        max_length=20,
                        verbose_name="Zustand",
                    ),
                ),
                (
                    "gpu_model",
                    models.CharField(
                        max_length=100, verbose_name="Angefordertes GPU-Modell"
                    ),
                ),
                (
                    "detected_gpu",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Erkannte GPU"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-Adresse"
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Angefordert am"
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bereit seit"
                    ),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letztes Lebenszeichen"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letzte Arbeit"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Fehler")),
            ],
            options={
                "verbose_name": "GPU-Knoten",
                "verbose_name_plural": "GPU-Knoten",
                "db_table": "minutes_gpu_nodes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["state"], name="minutes_gpu_state_f9a676_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="transcriptionjob",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="minutes.gpunode",
                verbose_name="Knoten",
            ),
        ),
    ]
