# Generated by Django 6.0.6 on 2026-09-30 05:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleState",
            fields=[
                (
                    "name",
                    models.TextField(
                        primary_key=True, serialize=False, verbose_name="Zeitplan"
                    ),
                ),
                (
                    "last_slot",
                    models.DateTimeField(verbose_name="zuletzt geplanter Termin"),
                ),
                (
                    "last_task_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="letzter Auftrag"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="aktualisiert am",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeitplan-Stand",
                "verbose_name_plural": "Zeitplan-Stände",
                "db_table": "events_schedule",
            },
        ),
    ]
