# Generated by Django 6.0.6 on 2026-10-07 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insight_core", "0052_quelle_aktualitaet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("geplant", "geplant"),
                            ("live", "läuft"),
                            ("beendet", "beendet"),
                            ("nicht_uebertragen", "nicht übertragen"),
                        ],
                        db_index=True,
                        default="geplant",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="begonnen am"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="beendet am"
                    ),
                ),
                (
                    "offline_since",
                    models.DateTimeField(
                        blank=True,
                        help_text="Aussetzer während der Übertragung",
                        null=True,
                        verbose_name="ohne Übertragung seit",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="letzte Abfrage"
                    ),
                ),
                (
                    "last_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ohne Bild-Adressen",
                        verbose_name="letzter Status",
                    ),
                ),
                (
                    "stream",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="aufgelöste Kennung, HLS- und Player-Adresse",
                        verbose_name="Stream",
                    ),
                ),
                (
                    "debounce",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Kandidaten für TOP und Person",
                        verbose_name="Entprellung",
                    ),
                ),
                (
                    "frames_read",
                    models.PositiveIntegerField(
                        default=0, verbose_name="gelesene Bilder"
                    ),
                ),
                (
                    "frames_without_overlay",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Bilder ohne Einblendung"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="insight_core.oparlmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Übertragung",
                "verbose_name_plural": "Übertragungen",
                "db_table": "hub_live_uebertragung",
            },
        ),
        migrations.CreateModel(
            name="BroadcastSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="TOP-Nummer")),
                (
                    "title_read",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="gelesener Titel",
                    ),
                ),
                (
                    "title_similarity",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Ähnlichkeit zum Titel im RIS",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("einblendung", "Einblendung"), ("hand", "von Hand")],
                        default="einblendung",
                        max_length=20,
                        verbose_name="Quelle",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="begonnen am")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="beendet am"
                    ),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="insight_core.oparlagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="hub_live.broadcast",
                    ),
                ),
            ],
            options={
                "verbose_name": "TOP-Abschnitt",
                "verbose_name_plural": "TOP-Abschnitte",
                "db_table": "hub_live_abschnitt",
                "ordering": ["started_at"],
            },
        ),
        migrations.AddField(
            model_name="broadcast",
            name="current_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hub_live.broadcastsection",
                verbose_name="TOP jetzt",
            ),
        ),
        migrations.CreateModel(
            name="BroadcastSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Code des Adapters, z. B. 3q oder hls",
                        max_length=32,
                        verbose_name="Anbieter",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="z. B. Embed-ID des Players oder Adresse der HLS-Playlist",
                        max_length=1000,
                        verbose_name="Kennung beim Anbieter",
                    ),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Seite der Übertragung",
                    ),
                ),
                (
                    "overlay_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Lage der Felder, Balken, Funktionsbezeichnungen",
                        verbose_name="Einblendungsprofil",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="aktiv")),
                (
                    "interval_seconds",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Takt der Einzelbilder (Sekunden)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="insight_core.oparlorganization",
                        verbose_name="Gremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "Übertragungsquelle",
                "verbose_name_plural": "Übertragungsquellen",
                "db_table": "hub_live_quelle",
            },
        ),
        migrations.CreateModel(
            name="BroadcastLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("at", models.DateTimeField(db_index=True, verbose_name="Zeit")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("abfrage", "Statusabfrage"),
                            ("lesung", "Lesung"),
                            ("zustand", "Zustandswechsel"),
                            ("fehler", "Fehler"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Daten"),
                ),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hub_live.broadcast",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="hub_live.broadcastsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokolleintrag",
                "verbose_name_plural": "Protokoll",
                "db_table": "hub_live_protokoll",
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="broadcast",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="broadcasts",
                to="hub_live.broadcastsource",
                verbose_name="Quelle",
            ),
        ),
        migrations.CreateModel(
            name="BroadcastSpeech",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_read",
                    models.CharField(max_length=200, verbose_name="gelesener Name"),
                ),
                (
                    "faction_read",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="gelesene Fraktion",
                    ),
                ),
                (
                    "function_read",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="gelesene Funktion",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="begonnen am")),
                (
                    "assignment",
                    models.CharField(
                        choices=[
                            ("eindeutig", "eindeutig"),
                            ("unsicher", "unsicher"),
                            ("keine", "keine"),
                        ],
                        default="keine",
                        max_length=20,
                        verbose_name="Zuordnung",
                    ),
                ),
                (
                    "readings",
                    models.PositiveIntegerField(
                        default=1, verbose_name="gleiche Lesungen"
                    ),
                ),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speeches",
                        to="hub_live.broadcast",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="insight_core.oparlperson",
                        verbose_name="Person",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speeches",
                        to="hub_live.broadcastsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wortmeldung",
                "verbose_name_plural": "Wortmeldungen",
                "db_table": "hub_live_wortmeldung",
                "ordering": ["started_at"],
            },
        ),
        migrations.AddField(
            model_name="broadcast",
            name="current_speech",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hub_live.broadcastspeech",
                verbose_name="am Wort",
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcastsource",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="hub_live_quelle_gremium"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastlog",
            index=models.Index(
                fields=["broadcast", "at"], name="hub_live_protokoll_uebertr"
            ),
        ),
        migrations.AddConstraint(
            model_name="broadcast",
            constraint=models.UniqueConstraint(
                fields=("source", "meeting"), name="hub_live_uebertragung_sitzung"
            ),
        ),
    ]
