# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Ereignisse in derselben Transaktion wie die Datenänderung (Issue #513), gegen PostgreSQL.

Braucht ``INGESTOR_TEST_DATABASE_URL`` (in der CI gesetzt; lokal ohne Datenbank übersprungen). Die
Tests legen ein eigenes Schema an und entfernen es wieder; vorhandene Tabellen der Datenbank fassen
sie nicht an. Die Tabellen entstehen aus der Beschreibung des Ingestors. Dass diese zur Tabelle aus
den Django-Migrationen passt, prüft der Schema-Vertrag (``mandari/insight_core/schema_contract.py``);
``seq``, ``xid`` und ``recorded_at`` kommen hier wie dort aus der Datenbank.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import uuid
from collections.abc import AsyncIterator, Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import pytest
from mandari_oparl.ids import canonical_id
from sqlalchemy import text
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker, create_async_engine

from src.storage import database, events, ris_events
from src.storage.database import DatabaseStorage
from src.storage.models import Base, OParlAgendaItem, OParlPaper
from src.sync.processor import OParlProcessor

DATABASE_URL = os.environ.get("INGESTOR_TEST_DATABASE_URL", "")
SCHEMA = f"ingestor_test_{uuid.uuid4().hex[:12]}"

BASE = "https://ris.example.org/oparl"
BODY = f"{BASE}/body/1"
MEETING = f"{BASE}/meeting/1"
PAPER = f"{BASE}/paper/1"
ITEM = f"{BASE}/agendaitem/1"
FILE = f"{BASE}/file/1"
CONSULTATION = f"{BASE}/consultation/1"
ORG = f"{BASE}/organization/1"
LOCATION = f"{BASE}/location/1"

pytestmark = pytest.mark.integration


def _engine() -> AsyncEngine:
    url = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://", 1)
    return create_async_engine(url, connect_args={"server_settings": {"search_path": SCHEMA}})


async def _schema_anlegen() -> None:
    engine = _engine()
    async with engine.begin() as conn:
        await conn.execute(text(f'CREATE SCHEMA "{SCHEMA}"'))
        await conn.run_sync(Base.metadata.create_all)
        # Was in der Installation die Django-Migration der Ereignistechnik anlegt und der Ingestor
        # nicht kennt: Folgenummer, Transaktionskennung, Erfassungszeit.
        await conn.execute(
            text(
                "ALTER TABLE events_event"
                " ADD COLUMN seq bigint NULL UNIQUE,"
                " ADD COLUMN recorded_at timestamptz NOT NULL DEFAULT now(),"
                " ADD COLUMN xid xid8 NOT NULL DEFAULT pg_current_xact_id()"
            )
        )
        # Zwischentabellen, die nur Django beschreibt (M2M); der Ingestor schreibt sie mit SQL.
        for tabelle, von, nach in (
            (
                "oparl_meetings_organizations",
                "oparlmeeting_id uuid NOT NULL REFERENCES oparl_meetings (id)",
                "oparlorganization_id uuid NOT NULL REFERENCES oparl_organizations (id)",
            ),
            (
                "oparl_papers_locations",
                "oparlpaper_id uuid NOT NULL REFERENCES oparl_papers (id)",
                "oparllocation_id uuid NOT NULL REFERENCES oparl_locations (id)",
            ),
        ):
            await conn.execute(
                text(
                    f"CREATE TABLE {tabelle} ("
                    " id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    f" {von}, {nach},"
                    f" UNIQUE ({von.split()[0]}, {nach.split()[0]}))"
                )
            )
    await engine.dispose()


async def _schema_entfernen() -> None:
    engine = _engine()
    async with engine.begin() as conn:
        await conn.execute(text(f'DROP SCHEMA IF EXISTS "{SCHEMA}" CASCADE'))
    await engine.dispose()


@pytest.fixture(scope="module")
def schema() -> Iterator[None]:
    if not DATABASE_URL:
        if os.environ.get("CI"):
            pytest.fail("INGESTOR_TEST_DATABASE_URL fehlt: In der CI müssen diese Tests laufen.")
        pytest.skip("braucht PostgreSQL (INGESTOR_TEST_DATABASE_URL)")
    asyncio.run(_schema_anlegen())
    yield
    asyncio.run(_schema_entfernen())


async def _speicher(events_enabled: bool) -> DatabaseStorage:
    storage = DatabaseStorage(
        DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://", 1), events_enabled=events_enabled
    )
    # Eigenes Schema der Tests statt der Tabellen der Datenbank
    await storage._engine.dispose()
    storage._engine = _engine()
    storage._session_factory = async_sessionmaker(storage._engine, class_=AsyncSession, expire_on_commit=False)
    return storage


@pytest.fixture
async def storage(schema: None) -> AsyncIterator[DatabaseStorage]:
    speicher = await _speicher(events_enabled=True)
    async with speicher._engine.begin() as conn:
        tabellen = ", ".join(f'"{tabelle.name}"' for tabelle in Base.metadata.sorted_tables)
        await conn.execute(text(f"TRUNCATE {tabellen} CASCADE"))
    yield speicher
    await speicher.close()


class Bestand:
    """Eine Quelle mit einer Kommune und Hilfen, um Objekte wie der Abgleich zu schreiben."""

    def __init__(self, storage: DatabaseStorage) -> None:
        self.storage = storage
        self.processor = OParlProcessor()
        self.source_id: uuid.UUID
        self.body_id: uuid.UUID

    async def anlegen(self) -> Bestand:
        self.source_id = await self.storage.upsert_source(f"{BASE}/system", "Musterstadt")
        body = self.processor.process_body(
            {"id": BODY, "type": "https://schema.oparl.org/1.1/Body", "name": "Musterstadt"}, BODY
        )
        self.body_id = await self.storage.upsert_body(body, self.source_id)
        return self

    async def paper(self, **felder: Any) -> uuid.UUID:
        daten: dict[str, Any] = {
            "id": PAPER,
            "type": "https://schema.oparl.org/1.1/Paper",
            "name": "Mehr Bänke im Park",
            "paperType": "Antrag",
            "modified": "2026-09-01T10:00:00+02:00",
        }
        daten.update(felder)
        return await self.storage.upsert_paper(self.processor.process_paper(daten, BODY), self.body_id)

    async def meeting(self, **felder: Any) -> uuid.UUID:
        daten: dict[str, Any] = {
            "id": MEETING,
            "type": "https://schema.oparl.org/1.1/Meeting",
            "name": "Rat",
            "start": "2026-10-01T17:00:00+02:00",
            "modified": "2026-09-01T10:00:00+02:00",
        }
        daten.update(felder)
        return await self.storage.upsert_meeting(self.processor.process_meeting(daten, BODY), self.body_id)

    async def gremium(self) -> uuid.UUID:
        daten = {"id": ORG, "type": "https://schema.oparl.org/1.1/Organization", "name": "Rat"}
        return await self.storage.upsert_organization(self.processor.process_organization(daten, BODY), self.body_id)

    async def ort(self) -> uuid.UUID:
        return await self.storage.upsert_location(self.processor.process_location(ort(), BODY), self.body_id)

    async def ereignisse(self) -> list[dict[str, Any]]:
        async with self.storage.get_session() as session:
            result = await session.execute(text("SELECT *, xid::text AS xid_text FROM events_event ORDER BY id"))
            return [dict(row._mapping) for row in result]

    async def wert(self, sql: str, **parameter: Any) -> Any:
        async with self.storage.get_session() as session:
            return (await session.execute(text(sql), parameter)).scalar()


@pytest.fixture
async def bestand(storage: DatabaseStorage) -> Bestand:
    return await Bestand(storage).anlegen()


def top(**felder: Any) -> dict[str, Any]:
    daten: dict[str, Any] = {
        "id": ITEM,
        "type": "https://schema.oparl.org/1.1/AgendaItem",
        "number": "1",
        "name": "Mehr Bänke im Park",
        "public": True,
    }
    daten.update(felder)
    return daten


def datei(**felder: Any) -> dict[str, Any]:
    daten: dict[str, Any] = {
        "id": FILE,
        "type": "https://schema.oparl.org/1.1/File",
        "name": "Anlage 1",
        "accessUrl": f"{FILE}/download",
    }
    daten.update(felder)
    return daten


def ort(**felder: Any) -> dict[str, Any]:
    daten: dict[str, Any] = {
        "id": LOCATION,
        "type": "https://schema.oparl.org/1.1/Location",
        "description": "Stadtpark",
    }
    daten.update(felder)
    return daten


# --- Schalter ----------------------------------------------------------------------------------------


async def test_ohne_schalter_schreibt_der_ingestor_kein_ereignis(bestand: Bestand) -> None:
    aus = await _speicher(events_enabled=False)
    try:
        body = bestand.processor.process_body(
            {"id": BODY, "type": "https://schema.oparl.org/1.1/Body", "name": "Musterstadt"}, BODY
        )
        body_id = await aus.upsert_body(body, bestand.source_id)
        await aus.upsert_paper(bestand.processor.process_paper({"id": PAPER, "name": "Bänke"}, BODY), body_id)
        await aus.upsert_paper(bestand.processor.process_paper({"id": PAPER, "name": "Mehr Bänke"}, BODY), body_id)
        assert await aus.mark_entity_deleted("paper", PAPER) is not None
    finally:
        await aus.close()
    assert await bestand.wert("SELECT count(*) FROM oparl_papers") == 1
    # Markiert mit Grund (Issue #524)
    assert await bestand.wert("SELECT deletion_reason FROM oparl_papers") == "quelle_geloescht"
    assert await bestand.ereignisse() == []


async def test_eingeschaltet_ohne_journal_bricht_der_start_ab(bestand: Bestand) -> None:
    """Ohne die Tabelle nähme jedes gescheiterte Ereignis seinen Upsert mit zurück."""
    await bestand.storage.initialize()
    async with bestand.storage._engine.begin() as conn:
        await conn.execute(text("ALTER TABLE events_event RENAME TO events_event_fehlt"))
    try:
        with pytest.raises(RuntimeError, match="events_event fehlt"):
            await bestand.storage.initialize()
        aus = await _speicher(events_enabled=False)
        try:
            await aus.initialize()
        finally:
            await aus.close()
    finally:
        async with bestand.storage._engine.begin() as conn:
            await conn.execute(text("ALTER TABLE events_event_fehlt RENAME TO events_event"))


async def test_ausgenommene_quelle_schreibt_keine_ereignisse(bestand: Bestand, monkeypatch: pytest.MonkeyPatch) -> None:
    """``sync_config["events_enabled"] = false`` nimmt eine Quelle aus; die übrigen melden weiter."""
    speicher = bestand.storage
    nachbar_quelle = await speicher.upsert_source(f"{BASE}/nachbar/system", "Nachbarstadt")
    nachbar_url = f"{BASE}/nachbar/body/1"
    nachbar = bestand.processor.process_body(
        {"id": nachbar_url, "type": "https://schema.oparl.org/1.1/Body", "name": "Nachbarstadt"}, nachbar_url
    )
    nachbar_id = await speicher.upsert_body(nachbar, nachbar_quelle)
    await speicher.update_source_sync_config(bestand.source_id, {database.SYNC_CONFIG_EVENTS_KEY: False})
    speicher.clear_uuid_caches()

    gelesen: list[str] = []
    original = speicher._prior

    async def prior(session: AsyncSession, model: type, external_id: str) -> ris_events.Prior | None:
        gelesen.append(external_id)
        return await original(session, model, external_id)

    monkeypatch.setattr(speicher, "_prior", prior)
    await bestand.meeting(agendaItem=[top()], invitation=datei())
    await bestand.paper(consultation=[{"id": CONSULTATION, "type": "https://schema.oparl.org/1.1/Consultation"}])
    await bestand.paper(name="Mehr Bänke")
    assert await speicher.mark_entity_deleted("agendaitem", ITEM) is not None
    assert await speicher.mark_entity_deleted("paper", PAPER) is not None
    # Wie ausgeschaltet: geschrieben wird, aber ohne Ereignis und ohne Abfrage des bisherigen Stands.
    assert await bestand.ereignisse() == []
    assert gelesen == []
    assert await bestand.wert("SELECT name FROM oparl_papers") == "Mehr Bänke"

    # Die Quelle der Nachbarstadt ist nicht ausgenommen.
    nachbar_vorlage = f"{BASE}/nachbar/paper/1"
    await speicher.upsert_paper(
        bestand.processor.process_paper({"id": nachbar_vorlage, "name": "Radweg"}, nachbar_url), nachbar_id
    )
    (ereignis,) = await bestand.ereignisse()
    assert (ereignis["type"], ereignis["tenant_ref"]) == ("ris.paper.released", f"source:{nachbar_quelle}")
    assert gelesen == [nachbar_vorlage]

    # Ausnahme aufgehoben: gilt ab dem nächsten Zyklus; gemeldet wird nur, was sich von da an ändert.
    await speicher.update_source_sync_config(bestand.source_id, {})
    speicher.clear_uuid_caches()
    await bestand.meeting(agendaItem=[top()], invitation=datei())
    await bestand.meeting(name="Rat (Sondersitzung)", agendaItem=[top()], invitation=datei())
    assert [(e["type"], e["payload"].get("changed")) for e in (await bestand.ereignisse())[1:]] == [
        ("ris.agendaitem.changed", None),  # war als gelöscht markiert und ist wieder da
        ("ris.meeting.changed", ["name"]),
    ]
    # Wieder geliefert: Markierung samt Grund aufgehoben (Issue #524)
    assert await bestand.wert("SELECT deleted FROM oparl_agenda_items") is False
    assert await bestand.wert("SELECT deletion_reason FROM oparl_agenda_items") is None


async def test_metrik_zaehlt_ereignisse_je_typ_und_kommune(bestand: Bestand, monkeypatch: pytest.MonkeyPatch) -> None:
    gezaehlt: list[tuple[str, str]] = []
    monkeypatch.setattr(
        database.metrics, "record_event_published", lambda typ, quelle, count=1: gezaehlt.append((typ, quelle))
    )
    await bestand.paper()
    await bestand.paper()
    await bestand.paper(name="Mehr Bänke")
    assert gezaehlt == [("ris.paper.released", "Musterstadt"), ("ris.paper.changed", "Musterstadt")]


# --- Upsert und Ereignis in einer Transaktion -------------------------------------------------------------


async def test_neue_vorlage_ereignis_in_der_transaktion_des_upserts(bestand: Bestand) -> None:
    vorher = datetime.now(UTC) - timedelta(seconds=5)
    paper_id = await bestand.paper()

    (ereignis,) = await bestand.ereignisse()
    assert paper_id == canonical_id(PAPER)
    assert (ereignis["type"], ereignis["version"]) == ("ris.paper.released", 1)
    assert (ereignis["aggregate_type"], ereignis["aggregate_id"]) == ("Paper", paper_id)
    assert ereignis["tenant_ref"] == f"source:{bestand.source_id}"
    assert ereignis["body_id"] == bestand.body_id
    assert (ereignis["visibility"], ereignis["operation"]) == ("oeffentlich", "upsert")
    assert ereignis["actor_ref"] == "system:ingestor"
    assert ereignis["causation_id"] is None
    assert ereignis["payload"] == {"paper": str(paper_id)}
    # Zeitpunkt laut Quelle (modified), erfasst wird beim Abgleich
    assert ereignis["occurred_at"] == datetime.fromisoformat("2026-09-01T10:00:00+02:00")
    assert ereignis["recorded_at"] >= vorher
    # Der Ingestor vergibt keine Folgenummer.
    assert ereignis["seq"] is None
    # Dieselbe Transaktion hat die Vorlage und das Ereignis geschrieben.
    assert await bestand.wert("SELECT xmin::text FROM oparl_papers WHERE id = :id", id=paper_id) == ereignis["xid_text"]


async def test_scheitert_das_ereignis_bleibt_auch_die_aenderung_aus(
    bestand: Bestand, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Beides oder nichts: Ein Ereignis, das sich nicht schreiben lässt, nimmt den Upsert mit zurück."""

    def ungueltig(paper_id: uuid.UUID, raw: Any, prior: Any, **_: Any) -> list[ris_events.Draft]:
        return [
            ris_events.Draft("ris.paper.released", "Paper", paper_id, {"paper": str(paper_id)}, visibility="geheim")
        ]

    monkeypatch.setattr(ris_events, "paper_events", ungueltig)
    with pytest.raises(events.InvalidEventError):
        await bestand.paper()

    assert await bestand.wert("SELECT count(*) FROM oparl_papers") == 0
    assert await bestand.ereignisse() == []


async def test_scheitert_der_commit_gibt_es_weder_aenderung_noch_ereignis(
    bestand: Bestand, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Das Ereignis steht schon in der Transaktion; bricht sie vor dem Commit ab, ist es nie sichtbar."""
    geschrieben: list[int] = []
    original = events.publish_many

    async def schreiben_und_abbrechen(session: AsyncSession, neue: Any) -> list[uuid.UUID]:
        await original(session, neue)
        anzahl = (await session.execute(text("SELECT count(*) FROM events_event"))).scalar()
        geschrieben.append(int(anzahl or 0))
        raise RuntimeError("Abbruch vor dem Commit")

    monkeypatch.setattr(events, "publish_many", schreiben_und_abbrechen)
    with pytest.raises(RuntimeError, match="Abbruch"):
        await bestand.paper()

    # In der Transaktion war das Ereignis geschrieben, außerhalb ist nichts davon zu sehen.
    assert geschrieben == [1]
    assert await bestand.wert("SELECT count(*) FROM oparl_papers") == 0
    assert await bestand.ereignisse() == []


async def test_publish_in_der_sitzung_der_datenaenderung(bestand: Bestand) -> None:
    """Die Hilfe selbst: Änderung und Ereignis in einer Sitzung, festgeschrieben vom Aufrufer."""
    tenant = f"source:{bestand.source_id}"
    paper_id = uuid.uuid4()
    async with bestand.storage.get_session() as session:
        await session.execute(text("UPDATE oparl_bodies SET short_name = 'MS' WHERE id = :id"), {"id": bestand.body_id})
        event_id = await events.publish(
            session,
            "ris.paper.changed",
            aggregate_type="Paper",
            aggregate_id=paper_id,
            tenant_ref=tenant,
            body_id=bestand.body_id,
            visibility="oeffentlich",
            payload={"paper": str(paper_id), "changed": ["name"]},
        )
        await session.rollback()
    assert await bestand.ereignisse() == []
    assert await bestand.wert("SELECT short_name FROM oparl_bodies") is None

    async with bestand.storage.get_session() as session:
        await session.execute(text("UPDATE oparl_bodies SET short_name = 'MS' WHERE id = :id"), {"id": bestand.body_id})
        event_id = await events.publish(
            session,
            "ris.paper.changed",
            aggregate_type="Paper",
            aggregate_id=paper_id,
            tenant_ref=tenant,
            visibility="oeffentlich",
            payload={"paper": str(paper_id), "changed": ["name"]},
        )
        await session.commit()
    (ereignis,) = await bestand.ereignisse()
    assert ereignis["event_id"] == event_id
    assert await bestand.wert("SELECT short_name FROM oparl_bodies") == "MS"


# --- Zuordnungen in der Transaktion des Ereignisses ----------------------------------------------------------

GREMIEN_DER_SITZUNG = "SELECT {} FROM oparl_meetings_organizations WHERE oparlmeeting_id = :id"
ORTE_DER_VORLAGE = "SELECT {} FROM oparl_papers_locations WHERE oparlpaper_id = :id"


async def test_gremien_der_sitzung_in_der_transaktion_des_ereignisses(bestand: Bestand) -> None:
    """Wer auf das Ereignis hin nachliest, sieht die Sitzung mit ihren Gremien: eine Transaktion, kein Nachlauf."""
    org_id = await bestand.gremium()
    meeting_id = await bestand.meeting(organization=[ORG])

    gremium, ereignis = await bestand.ereignisse()
    assert gremium["type"] == "ris.organization.changed"
    assert ereignis["type"] == "ris.meeting.scheduled"
    assert ereignis["payload"] == {"meeting": str(meeting_id), "organizations": [str(org_id)]}
    assert await bestand.wert(GREMIEN_DER_SITZUNG.format("oparlorganization_id"), id=meeting_id) == org_id
    assert await bestand.wert(GREMIEN_DER_SITZUNG.format("xmin::text"), id=meeting_id) == ereignis["xid_text"]
    sitzung = await bestand.wert("SELECT xmin::text FROM oparl_meetings WHERE id = :id", id=meeting_id)
    assert sitzung == ereignis["xid_text"]

    # Geänderte Sitzung: Auch die neu geschriebene Zuordnung trägt die Transaktion des Ereignisses.
    await bestand.meeting(organization=[ORG], name="Rat (Sondersitzung)")
    geaendert = (await bestand.ereignisse())[-1]
    assert (geaendert["type"], geaendert["payload"]["changed"]) == ("ris.meeting.changed", ["name"])
    assert await bestand.wert(GREMIEN_DER_SITZUNG.format("count(*)"), id=meeting_id) == 1
    assert await bestand.wert(GREMIEN_DER_SITZUNG.format("xmin::text"), id=meeting_id) == geaendert["xid_text"]

    # Vollabgleich ohne Änderung: gleiche Zuordnung, kein Ereignis
    await bestand.meeting(organization=[ORG], name="Rat (Sondersitzung)")
    assert len(await bestand.ereignisse()) == 3


async def test_scheitert_das_ereignis_bleibt_auch_die_zuordnung_der_gremien_aus(
    bestand: Bestand, monkeypatch: pytest.MonkeyPatch
) -> None:
    await bestand.gremium()

    async def abbrechen(session: AsyncSession, neue: Any) -> list[uuid.UUID]:
        raise RuntimeError("Abbruch vor dem Commit")

    monkeypatch.setattr(events, "publish_many", abbrechen)
    with pytest.raises(RuntimeError, match="Abbruch"):
        await bestand.meeting(organization=[ORG])
    assert await bestand.wert("SELECT count(*) FROM oparl_meetings") == 0
    assert await bestand.wert("SELECT count(*) FROM oparl_meetings_organizations") == 0


async def test_gremium_erst_spaeter_im_bestand_meldet_die_sitzung(bestand: Bestand) -> None:
    """Die Quelle liefert dieselbe Sitzung, aber ihr Gremium lässt sich erst im zweiten Abgleich zuordnen."""
    meeting_id = await bestand.meeting(organization=[ORG])
    assert await bestand.wert("SELECT count(*) FROM oparl_meetings_organizations") == 0

    org_id = await bestand.gremium()
    await bestand.meeting(organization=[ORG])
    _, _, ereignis = await bestand.ereignisse()
    assert ereignis["type"] == "ris.meeting.changed"
    assert ereignis["payload"] == {
        "meeting": str(meeting_id),
        "changed": ["organization"],
        "cancelled": False,
        "organizations": [str(org_id)],
    }
    assert await bestand.wert(GREMIEN_DER_SITZUNG.format("xmin::text"), id=meeting_id) == ereignis["xid_text"]

    await bestand.meeting(organization=[ORG])
    assert len(await bestand.ereignisse()) == 3


async def test_orte_der_vorlage_in_der_transaktion_des_ereignisses(bestand: Bestand) -> None:
    """Der eingebettete Ort steht vor der Vorlage im Bestand; Zuordnung und Ereignis teilen die Transaktion."""
    paper_id = await bestand.paper(location=[ort()])

    (ereignis,) = await bestand.ereignisse()
    assert ereignis["type"] == "ris.paper.released"
    assert await bestand.wert(ORTE_DER_VORLAGE.format("oparllocation_id"), id=paper_id) == canonical_id(LOCATION)
    assert await bestand.wert(ORTE_DER_VORLAGE.format("xmin::text"), id=paper_id) == ereignis["xid_text"]

    # Vollabgleich ohne Änderung: Die Zuordnung besteht, kein Ereignis
    await bestand.paper(location=[ort()])
    assert len(await bestand.ereignisse()) == 1
    assert await bestand.wert(ORTE_DER_VORLAGE.format("count(*)"), id=paper_id) == 1


async def test_ort_erst_spaeter_im_bestand_meldet_die_vorlage(bestand: Bestand) -> None:
    paper_id = await bestand.paper(location=[LOCATION])
    assert await bestand.wert("SELECT count(*) FROM oparl_papers_locations") == 0

    await bestand.ort()
    await bestand.paper(location=[LOCATION])
    _, ereignis = await bestand.ereignisse()
    assert ereignis["type"] == "ris.paper.changed"
    assert ereignis["payload"] == {"paper": str(paper_id), "changed": ["location"]}
    assert await bestand.wert(ORTE_DER_VORLAGE.format("xmin::text"), id=paper_id) == ereignis["xid_text"]

    await bestand.paper(location=[LOCATION])
    assert len(await bestand.ereignisse()) == 2


async def test_ohne_tabelle_der_ortszuordnung_bleiben_vorlage_und_ereignis(bestand: Bestand) -> None:
    """Fehlt die Zwischentabelle (Migration nicht eingespielt), entfällt nur die Zuordnung."""
    async with bestand.storage._engine.begin() as conn:
        await conn.execute(text("ALTER TABLE oparl_papers_locations RENAME TO oparl_papers_locations_fehlt"))
    try:
        paper_id = await bestand.paper(location=[ort()])
    finally:
        async with bestand.storage._engine.begin() as conn:
            await conn.execute(text("ALTER TABLE oparl_papers_locations_fehlt RENAME TO oparl_papers_locations"))

    (ereignis,) = await bestand.ereignisse()
    assert ereignis["type"] == "ris.paper.released"
    assert await bestand.wert("SELECT xmin::text FROM oparl_papers WHERE id = :id", id=paper_id) == ereignis["xid_text"]
    assert await bestand.wert("SELECT count(*) FROM oparl_locations") == 1


async def test_scheitert_die_ortszuordnung_gibt_es_weder_vorlage_noch_ereignis(bestand: Bestand) -> None:
    """Jeder andere Fehler nimmt den Upsert mit zurück: nie eine Vorlage mit Ereignis, aber ohne Zuordnung."""
    async with bestand.storage._engine.begin() as conn:
        await conn.execute(text("ALTER TABLE oparl_papers_locations ADD CONSTRAINT nie CHECK (false) NOT VALID"))
    try:
        with pytest.raises(IntegrityError):
            await bestand.paper(location=[ort()])
    finally:
        async with bestand.storage._engine.begin() as conn:
            await conn.execute(text("ALTER TABLE oparl_papers_locations DROP CONSTRAINT nie"))

    assert await bestand.wert("SELECT count(*) FROM oparl_papers") == 0
    assert await bestand.ereignisse() == []


# --- Nur echte Änderungen -----------------------------------------------------------------------------------


async def test_vollabgleich_ohne_aenderung_schreibt_kein_ereignis(bestand: Bestand) -> None:
    await bestand.paper()
    await bestand.paper()
    await bestand.paper(modified="2026-09-30T00:00:00+02:00")
    assert [e["type"] for e in await bestand.ereignisse()] == ["ris.paper.released"]
    # Der Upsert selbst läuft wie bisher: Der neue Zeitstempel der Quelle steht in der Zeile.
    assert await bestand.wert("SELECT raw_json->>'modified' FROM oparl_papers") == "2026-09-30T00:00:00+02:00"


async def test_andere_reihenfolge_der_quelle_schreibt_kein_ereignis(bestand: Bestand) -> None:
    """
    Befund aus dem Betrieb (Issue #553): Die Quelle sortiert Teilnehmer und eingebettete Listen bei
    jedem Abruf anders. Das ist keine Änderung; erst eine andere Menge ist eine.
    """
    personen = [f"{BASE}/person/{nummer}" for nummer in (254, 274, 330, 1285)]
    punkte = [top(), top(id=f"{BASE}/agendaitem/2", number="2", name="Haushalt")]
    meeting_id = await bestand.meeting(participant=personen, agendaItem=punkte, auxiliaryFile=[datei()])
    beratungen = [{"id": f"{BASE}/consultation/{i}", "role": "Vorberatung", "meeting": MEETING} for i in (1, 2)]
    await bestand.paper(consultation=beratungen, keyword=["Park", "Bänke"])
    vorher = len(await bestand.ereignisse())

    await bestand.meeting(participant=personen[::-1], agendaItem=punkte[::-1], auxiliaryFile=[datei()], keyword=[])
    await bestand.paper(consultation=beratungen[::-1], keyword=["Bänke", "Park", "Park"])
    assert len(await bestand.ereignisse()) == vorher
    # Der Upsert selbst läuft wie bisher: Die Zeile trägt die Reihenfolge des letzten Abrufs.
    assert await bestand.wert("SELECT raw_json->'participant'->>0 FROM oparl_meetings") == personen[-1]

    await bestand.meeting(participant=personen[1:], agendaItem=punkte, auxiliaryFile=[datei()])
    ereignis = (await bestand.ereignisse())[-1]
    assert ereignis["type"] == "ris.meeting.changed"
    assert ereignis["payload"]["meeting"] == str(meeting_id)
    assert ereignis["payload"]["changed"] == ["participant"]


async def test_geaenderte_vorlage_nennt_die_felder(bestand: Bestand) -> None:
    paper_id = await bestand.paper()
    await bestand.paper(name="Mehr Bänke", reference="A/1", modified="2026-09-02T09:00:00+02:00")

    _, ereignis = await bestand.ereignisse()
    assert ereignis["type"] == "ris.paper.changed"
    assert ereignis["payload"] == {"paper": str(paper_id), "changed": ["name", "reference"]}
    assert ereignis["occurred_at"] == datetime.fromisoformat("2026-09-02T09:00:00+02:00")


async def test_zeitpunkt_in_der_zukunft_wird_nicht_uebernommen(bestand: Bestand) -> None:
    vorher = datetime.now(UTC) - timedelta(seconds=5)
    await bestand.paper(modified="2099-01-01T00:00:00+00:00")
    (ereignis,) = await bestand.ereignisse()
    assert vorher <= ereignis["occurred_at"] <= datetime.now(UTC) + timedelta(seconds=5)


# --- Sitzung mit eingebetteten Objekten ------------------------------------------------------------------------


async def test_sitzung_mit_tagesordnung_und_datei(bestand: Bestand) -> None:
    meeting_id = await bestand.meeting(agendaItem=[top()], invitation=datei())

    ereignisse = await bestand.ereignisse()
    assert [e["type"] for e in ereignisse] == ["ris.meeting.scheduled", "ris.agendaitem.changed", "ris.file.changed"]
    sitzung, punkt, anlage = ereignisse
    assert sitzung["payload"] == {"meeting": str(meeting_id)}
    assert punkt["payload"] == {
        "agenda_item": str(canonical_id(ITEM)),
        "meeting": str(meeting_id),
        "change": "added",
    }
    assert anlage["payload"] == {"file": str(canonical_id(FILE)), "change": "added", "meeting": str(meeting_id)}
    assert {e["tenant_ref"] for e in ereignisse} == {f"source:{bestand.source_id}"}
    assert {e["body_id"] for e in ereignisse} == {bestand.body_id}
    # Jedes Objekt wird wie bisher in seiner eigenen Transaktion geschrieben, mit seinem Ereignis.
    assert len({e["xid_text"] for e in ereignisse}) == 3

    # Zweiter Abgleich ohne Änderung, einmal eingebettet, einmal aus der eigenen Liste (mit Rückverweis)
    await bestand.meeting(agendaItem=[top()], invitation=datei())
    einzeln = bestand.processor.process_agenda_item(top(meeting=MEETING), BODY)
    await bestand.storage.upsert_agenda_item(einzeln, meeting_id)
    assert len(await bestand.ereignisse()) == 3


async def test_nichtoeffentlicher_punkt_und_wechsel_der_sichtbarkeit(bestand: Bestand) -> None:
    meeting_id = await bestand.meeting(agendaItem=[top()])
    await bestand.meeting(agendaItem=[top(public=False, name="Personalangelegenheit")])

    ereignisse = await bestand.ereignisse()
    assert [(e["type"], e["visibility"], e["operation"]) for e in ereignisse] == [
        ("ris.meeting.scheduled", "oeffentlich", "upsert"),
        ("ris.agendaitem.changed", "oeffentlich", "upsert"),
        ("ris.meeting.changed", "oeffentlich", "upsert"),
        ("ris.object.depublished", "oeffentlich", "delete"),
        ("ris.agendaitem.changed", "nichtoeffentlich", "upsert"),
    ]
    ruecknahme, aenderung = ereignisse[3:]
    assert ruecknahme["payload"] == {
        "object_type": "AgendaItem",
        "object": str(canonical_id(ITEM)),
        "reason": "nichtoeffentlich",
    }
    assert aenderung["payload"] == {
        "agenda_item": str(canonical_id(ITEM)),
        "meeting": str(meeting_id),
        "change": "changed",
        "changed": ["name", "public"],
    }
    # Beide Ereignisse stehen in der Transaktion des Upserts.
    assert ruecknahme["xid_text"] == aenderung["xid_text"]
    # Kein Inhalt im Journal, auch nicht der Titel
    assert "Personalangelegenheit" not in repr(ereignisse)


# --- Vorlage mit Beratung und Datei ----------------------------------------------------------------------------


async def test_vorlage_mit_beratung_und_datei(bestand: Bestand) -> None:
    beratung = {
        "id": CONSULTATION,
        "type": "https://schema.oparl.org/1.1/Consultation",
        "role": "Vorberatung",
        "meeting": MEETING,
        "agendaItem": ITEM,
    }
    paper_id = await bestand.paper(consultation=[beratung], mainFile=datei())

    ereignisse = {e["type"]: e for e in await bestand.ereignisse()}
    assert set(ereignisse) == {"ris.paper.released", "ris.consultation.changed", "ris.file.changed"}
    assert ereignisse["ris.consultation.changed"]["payload"] == {
        "consultation": str(canonical_id(CONSULTATION)),
        "paper": str(paper_id),
        "change": "added",
        "meeting": str(canonical_id(MEETING)),
        "agenda_item": str(canonical_id(ITEM)),
    }
    assert ereignisse["ris.file.changed"]["payload"] == {
        "file": str(canonical_id(FILE)),
        "change": "added",
        "paper": str(paper_id),
    }

    await bestand.paper(consultation=[beratung], mainFile=datei(name="Anlage 1 (neu)"))
    neu = (await bestand.ereignisse())[3:]
    assert [(e["type"], e["payload"].get("change")) for e in neu] == [
        ("ris.paper.changed", None),
        ("ris.file.changed", "renamed"),
    ]
    assert neu[0]["payload"]["changed"] == ["mainFile"]


async def test_datei_erst_einzeln_dann_an_der_vorlage(bestand: Bestand) -> None:
    """Die Quelle liefert dasselbe Objekt, aber die Datei hängt erstmals an einer Vorlage."""
    einzeln = bestand.processor.process_file(datei(), BODY)
    file_id = await bestand.storage.upsert_file(einzeln, bestand.body_id)
    paper_id = await bestand.paper(mainFile=datei())

    ereignisse = await bestand.ereignisse()
    assert [(e["type"], e["payload"].get("change")) for e in ereignisse] == [
        ("ris.file.changed", "added"),
        ("ris.paper.released", None),
        ("ris.file.changed", "added"),
    ]
    assert ereignisse[0]["payload"] == {"file": str(file_id), "change": "added"}
    assert ereignisse[2]["payload"] == {"file": str(file_id), "change": "added", "paper": str(paper_id)}
    assert await bestand.wert("SELECT paper_id FROM oparl_files WHERE id = :id", id=file_id) == paper_id
    zeile = await bestand.wert("SELECT xmin::text FROM oparl_files WHERE id = :id", id=file_id)
    assert zeile == ereignisse[2]["xid_text"]

    # Weitere Abgleiche, eingebettet wie einzeln: Die Zuordnung ist bekannt.
    await bestand.paper(mainFile=datei())
    await bestand.storage.upsert_file(einzeln, bestand.body_id)
    assert len(await bestand.ereignisse()) == 3


# --- Löschmarkierung ----------------------------------------------------------------------------------------------


async def test_loeschmarkierung_meldet_die_ruecknahme_in_derselben_transaktion(bestand: Bestand) -> None:
    paper_id = await bestand.paper()
    geloescht_am = datetime.fromisoformat("2026-09-03T12:00:00+02:00")
    assert await bestand.storage.mark_entity_deleted("paper", PAPER, modified=geloescht_am) == paper_id

    _, ereignis = await bestand.ereignisse()
    assert (ereignis["type"], ereignis["operation"], ereignis["visibility"]) == (
        "ris.object.depublished",
        "delete",
        "oeffentlich",
    )
    assert (ereignis["aggregate_type"], ereignis["aggregate_id"]) == ("Paper", paper_id)
    assert ereignis["payload"] == {"object_type": "Paper", "object": str(paper_id), "reason": "quelle_geloescht"}
    assert ereignis["occurred_at"] == geloescht_am
    assert ereignis["tenant_ref"] == f"source:{bestand.source_id}"
    assert await bestand.wert("SELECT xmin::text FROM oparl_papers WHERE id = :id", id=paper_id) == ereignis["xid_text"]

    # Schon markiert: keine zweite Meldung
    assert await bestand.storage.mark_entity_deleted("paper", PAPER) is None
    assert len(await bestand.ereignisse()) == 2

    # Die Quelle liefert das Objekt wieder: Es ist erneut veröffentlicht.
    await bestand.paper()
    assert [e["type"] for e in await bestand.ereignisse()][2:] == ["ris.paper.released"]


async def test_loeschmarkierung_eines_tagesordnungspunkts_findet_die_kommune_ueber_die_sitzung(
    bestand: Bestand,
) -> None:
    await bestand.meeting(agendaItem=[top()])
    bestand.storage.clear_uuid_caches()
    assert await bestand.storage.mark_entity_deleted("agendaitem", ITEM) == canonical_id(ITEM)

    ereignis = (await bestand.ereignisse())[-1]
    assert ereignis["payload"] == {
        "object_type": "AgendaItem",
        "object": str(canonical_id(ITEM)),
        "reason": "quelle_geloescht",
    }
    assert (ereignis["tenant_ref"], ereignis["body_id"]) == (f"source:{bestand.source_id}", bestand.body_id)


async def test_loeschmarkierung_eines_nichtoeffentlichen_punkts_wird_nicht_oeffentlich_gemeldet(
    bestand: Bestand,
) -> None:
    """Öffentliche Empfänger haben den Punkt nie gesehen; seine Kennung steht in keinem öffentlichen Ereignis."""
    meeting_id = await bestand.meeting(agendaItem=[top(public=False, name="Personalangelegenheit")])
    assert await bestand.storage.mark_entity_deleted("agendaitem", ITEM) == canonical_id(ITEM)

    ereignisse = await bestand.ereignisse()
    assert [(e["type"], e["visibility"], e["operation"]) for e in ereignisse] == [
        ("ris.meeting.scheduled", "oeffentlich", "upsert"),
        ("ris.agendaitem.changed", "nichtoeffentlich", "upsert"),
        ("ris.agendaitem.changed", "nichtoeffentlich", "delete"),
    ]
    geloescht = ereignisse[-1]
    assert geloescht["payload"] == {
        "agenda_item": str(canonical_id(ITEM)),
        "meeting": str(meeting_id),
        "change": "deleted",
    }
    zeile = await bestand.wert("SELECT xmin::text FROM oparl_agenda_items WHERE id = :id", id=canonical_id(ITEM))
    assert zeile == geloescht["xid_text"]
    oeffentlich = [e for e in ereignisse if e["visibility"] == "oeffentlich"]
    assert str(canonical_id(ITEM)) not in repr(oeffentlich)


async def test_loeschmarkierung_von_gremium_person_und_mitgliedschaft(bestand: Bestand) -> None:
    """Gremien und Personen melden Neues (#821), Mitgliedschaften nicht; alle drei melden ihre Rücknahme."""
    org_url, person_url, mitgliedschaft_url = f"{BASE}/organization/1", f"{BASE}/person/1", f"{BASE}/membership/1"
    verarbeiter = bestand.processor
    organisation = {"id": org_url, "type": "https://schema.oparl.org/1.1/Organization", "name": "Rat"}
    person = {"id": person_url, "type": "https://schema.oparl.org/1.1/Person", "name": "Ratsmitglied"}
    mitgliedschaft = {
        "id": mitgliedschaft_url,
        "type": "https://schema.oparl.org/1.1/Membership",
        "person": person_url,
        "organization": org_url,
    }
    await bestand.storage.upsert_organization(verarbeiter.process_organization(organisation, BODY), bestand.body_id)
    await bestand.storage.upsert_person(verarbeiter.process_person(person, BODY), bestand.body_id)
    assert await bestand.storage.upsert_membership(
        verarbeiter.process_membership(mitgliedschaft, BODY), bestand.body_id
    )
    # Für Änderungen an Mitgliedschaften gibt es noch keinen Vertrag.
    assert [(e["type"], e["payload"]["change"]) for e in await bestand.ereignisse()] == [
        ("ris.organization.changed", "added"),
        ("ris.person.changed", "added"),
    ]

    for typ, url in (("membership", mitgliedschaft_url), ("person", person_url), ("organization", org_url)):
        assert await bestand.storage.mark_entity_deleted(typ, url) == canonical_id(url)

    ereignisse = (await bestand.ereignisse())[2:]
    assert [e["payload"]["object_type"] for e in ereignisse] == ["Membership", "Person", "Organization"]
    assert {e["type"] for e in ereignisse} == {"ris.object.depublished"}
    assert {e["body_id"] for e in ereignisse} == {bestand.body_id}


async def test_gremium_und_person_melden_neu_geaendert_und_wieder_geliefert(bestand: Bestand) -> None:
    """``ris.organization.changed`` und ``ris.person.changed`` (#821): fachlicher Vergleich wie bei den übrigen."""
    verarbeiter = bestand.processor
    person_url = f"{BASE}/person/1"
    mitglieder = [f"{BASE}/membership/1", f"{BASE}/membership/2"]

    async def gremium(**felder: Any) -> uuid.UUID:
        daten = {"id": ORG, "type": "https://schema.oparl.org/1.1/Organization", "name": "Rat", **felder}
        return await bestand.storage.upsert_organization(verarbeiter.process_organization(daten, BODY), bestand.body_id)

    async def person(**felder: Any) -> uuid.UUID:
        daten = {"id": person_url, "type": "https://schema.oparl.org/1.1/Person", "name": "Ratsmitglied", **felder}
        return await bestand.storage.upsert_person(verarbeiter.process_person(daten, BODY), bestand.body_id)

    org_id = await gremium(membership=mitglieder, modified="2026-09-01T10:00:00+02:00")
    person_id = await person(familyName="Muster")
    # Andere Reihenfolge, leere Werte, neuer Zeitstempel: keine Änderung
    await gremium(membership=mitglieder[::-1], website="", modified="2026-09-30T10:00:00+02:00")
    await person(familyName="Muster", title=[])
    assert len(await bestand.ereignisse()) == 2

    await gremium(membership=mitglieder, name="Rat der Stadt", modified="2026-10-01T09:00:00+02:00")
    await person(familyName="Beispiel", title=["Dr."])
    *_, umbenannt, geaendert = await bestand.ereignisse()
    assert (umbenannt["type"], umbenannt["aggregate_type"], umbenannt["aggregate_id"]) == (
        "ris.organization.changed",
        "Organization",
        org_id,
    )
    assert umbenannt["payload"] == {"organization": str(org_id), "change": "changed", "changed": ["name"]}
    assert umbenannt["occurred_at"] == datetime.fromisoformat("2026-10-01T09:00:00+02:00")
    assert geaendert["payload"] == {"person": str(person_id), "change": "changed", "changed": ["familyName", "title"]}
    assert {e["visibility"] for e in (umbenannt, geaendert)} == {"oeffentlich"}
    assert {e["tenant_ref"] for e in (umbenannt, geaendert)} == {f"source:{bestand.source_id}"}

    # Nach der Löschmarkierung wieder geliefert: für Empfänger wieder neu
    await bestand.storage.mark_entity_deleted("organization", ORG)
    await gremium(membership=mitglieder, name="Rat der Stadt")
    *_, depubliziert, wieder = await bestand.ereignisse()
    assert depubliziert["type"] == "ris.object.depublished"
    assert wieder["payload"] == {"organization": str(org_id), "change": "added"}


async def test_texterkennung_meldet_den_text_in_derselben_transaktion(bestand: Bestand) -> None:
    """``ris.file.text_extracted`` (#821): nur mit Text, ``intern``, in der Transaktion des Speicherns."""
    file_id = await bestand.storage.upsert_file(bestand.processor.process_file(datei(), BODY), bestand.body_id)
    vorher = len(await bestand.ereignisse())

    await bestand.storage.update_file_text(file_id, status="failed", error="Download failed")
    await bestand.storage.update_file_text(file_id, method="none", status="completed")
    assert len(await bestand.ereignisse()) == vorher

    await bestand.storage.update_file_text(file_id, text_content="Beschluss zum Radweg", method="pypdf")
    ereignis = (await bestand.ereignisse())[-1]
    assert (ereignis["type"], ereignis["aggregate_type"], ereignis["aggregate_id"]) == (
        "ris.file.text_extracted",
        "File",
        file_id,
    )
    assert (ereignis["visibility"], ereignis["body_id"]) == ("intern", bestand.body_id)
    assert ereignis["payload"] == {"file": str(file_id), "method": "pypdf", "characters": 20}
    zeile = await bestand.wert("SELECT xmin::text FROM oparl_files WHERE id = :id", id=file_id)
    assert zeile == ereignis["xid_text"]


async def test_scheitert_das_ereignis_der_texterkennung_bleibt_der_text_aus(
    bestand: Bestand, monkeypatch: pytest.MonkeyPatch
) -> None:
    file_id = await bestand.storage.upsert_file(bestand.processor.process_file(datei(), BODY), bestand.body_id)

    async def abbrechen(session: AsyncSession, neue: Any) -> list[uuid.UUID]:
        raise RuntimeError("Abbruch vor dem Commit")

    monkeypatch.setattr(events, "publish_many", abbrechen)
    with pytest.raises(RuntimeError, match="Abbruch"):
        await bestand.storage.update_file_text(file_id, text_content="Beschluss zum Radweg", method="pypdf")
    assert await bestand.wert("SELECT text_content FROM oparl_files WHERE id = :id", id=file_id) is None


# --- Korrelation und Nebenläufigkeit ----------------------------------------------------------------------------


async def test_ereignisse_eines_abgleichs_tragen_dieselbe_korrelation(bestand: Bestand) -> None:
    vorgang = events.start_correlation()
    await bestand.meeting(agendaItem=[top()])
    await bestand.paper()
    assert {e["correlation_id"] for e in await bestand.ereignisse()} == {vorgang}


async def test_gleichzeitige_abgleiche_desselben_objekts_melden_die_aenderung_einmal(bestand: Bestand) -> None:
    """
    Der Vergleich gilt für genau den Stand, den der Upsert überschreibt (Zeilensperre bis zum Commit).

    Zwei Abgleiche schreiben gleichzeitig dieselbe neue Fassung. Der zweite wartet, bis der erste
    festgeschrieben hat, und findet die Vorlage dann schon geändert vor. Ohne Sperre vergliche er mit
    dem alten Stand und meldete dieselbe Änderung ein zweites Mal.
    """
    await bestand.paper()
    neu = {
        "id": PAPER,
        "type": "https://schema.oparl.org/1.1/Paper",
        "name": "Neue Fassung",
        "paperType": "Antrag",
        "modified": "2026-09-01T10:00:00+02:00",
    }
    erster = bestand.storage.get_session()
    async with erster:
        # Der erste Abgleich hat den bisherigen Stand gelesen und hält die Zeile.
        assert await bestand.storage._prior(erster, OParlPaper, PAPER) is not None
        zweiter = asyncio.create_task(bestand.paper(name="Neue Fassung"))
        await asyncio.sleep(0.5)
        assert not zweiter.done(), "Der zweite Abgleich muss auf die Zeilensperre warten"
        await erster.execute(
            text(
                "UPDATE oparl_papers SET name = 'Neue Fassung', raw_json = cast(:roh AS jsonb) WHERE external_id = :id"
            ),
            {"roh": json.dumps(neu), "id": PAPER},
        )
        await erster.commit()
    await zweiter

    # Nur die Anlage der Vorlage steht im Journal: Der zweite Abgleich fand nichts mehr zu ändern.
    assert [e["type"] for e in await bestand.ereignisse()] == ["ris.paper.released"]
    assert await bestand.wert("SELECT name FROM oparl_papers") == "Neue Fassung"


async def test_gleichzeitige_abgleiche_desselben_neuen_objekts_melden_es_einmal(bestand: Bestand) -> None:
    """
    Ein neues Objekt hat noch keine Zeile, die sich sperren ließe; dafür gilt eine Sperre auf die Kennung.

    Der erste Abgleich hat festgestellt, dass es die Vorlage noch nicht gibt. Der zweite wartet, bis
    der erste festgeschrieben hat, und findet die Vorlage dann vor. Ohne die Sperre sähen beide
    keinen bisherigen Stand und meldeten die Vorlage beide als neu.
    """
    daten = {
        "id": PAPER,
        "type": "https://schema.oparl.org/1.1/Paper",
        "name": "Mehr Bänke im Park",
        "paperType": "Antrag",
        "modified": "2026-09-01T10:00:00+02:00",
    }
    erster = bestand.storage.get_session()
    async with erster:
        assert await bestand.storage._prior(erster, OParlPaper, PAPER) is None
        zweiter = asyncio.create_task(bestand.paper())
        await asyncio.sleep(0.5)
        assert not zweiter.done(), "Der zweite Abgleich muss warten, bis der erste festgeschrieben hat"
        await erster.execute(
            pg_insert(OParlPaper).values(
                id=canonical_id(PAPER), external_id=PAPER, body_id=bestand.body_id, name=daten["name"], raw_json=daten
            )
        )
        await erster.commit()
    await zweiter

    # Der zweite Abgleich fand die Vorlage unverändert vor: kein zweites "neu".
    assert await bestand.ereignisse() == []
    assert await bestand.wert("SELECT count(*) FROM oparl_papers") == 1

    # Dasselbe mit vollständigen Abgleichen nebeneinander, auch für eingebettete Objekte
    beratung = {"id": CONSULTATION, "type": "https://schema.oparl.org/1.1/Consultation", "role": "Vorberatung"}
    await asyncio.gather(
        bestand.meeting(agendaItem=[top()]),
        bestand.meeting(agendaItem=[top()]),
        bestand.paper(name="Neue Fassung", consultation=[beratung]),
        bestand.paper(name="Neue Fassung", consultation=[beratung]),
    )
    assert sorted(e["type"] for e in await bestand.ereignisse()) == [
        "ris.agendaitem.changed",
        "ris.consultation.changed",
        "ris.meeting.scheduled",
        "ris.paper.changed",
    ]


async def test_upsert_wartet_nicht_auf_offene_einfuegungen_mit_bezug_auf_das_objekt(bestand: Bestand) -> None:
    """
    Die Sperre auf den bisherigen Stand ist so stark wie der Upsert selbst (``FOR NO KEY UPDATE``).

    Eine andere Transaktion fügt gerade einen Tagesordnungspunkt zur Sitzung ein und hält dafür die
    Schlüsselsperre der Sitzung. Der Abgleich der Sitzung ändert keinen Schlüssel und muss darauf
    nicht warten. Mit ``FOR UPDATE`` stünde er, bis die andere Transaktion endet.
    """
    meeting_id = await bestand.meeting()
    async with bestand.storage.get_session() as offen:
        await offen.execute(
            pg_insert(OParlAgendaItem).values(id=uuid.uuid4(), external_id=ITEM, meeting_id=meeting_id, raw_json={})
        )
        await asyncio.wait_for(bestand.meeting(name="Rat (Sondersitzung)"), timeout=5)
        await offen.rollback()

    assert [e["type"] for e in await bestand.ereignisse()] == ["ris.meeting.scheduled", "ris.meeting.changed"]


# --- Umgezogene Quelle (Issue #733) ------------------------------------------------------------------------------


async def test_umgezogene_quelle_behaelt_kennungen_und_verweise(bestand: Bestand) -> None:
    """
    Nach einem Umzug (neue Adressen im Bestand, Basis der Kennungen festgeschrieben) aktualisiert der Abgleich
    die Objekte, statt sie neu anzulegen; Ereignisse nennen die Kennungen von vorher.
    """
    alt, neu = f"{BASE}/", "https://neu.example.org/oparl/"
    sitzung = await bestand.meeting()
    vorlage = await bestand.paper()
    # Umzug der Adressen wie ``manage.py move_session_sources`` (Kennungen bleiben)
    async with bestand.storage.get_session() as session:
        for tabelle in ("oparl_bodies", "oparl_meetings", "oparl_papers"):
            await session.execute(
                text(
                    f"UPDATE {tabelle}"
                    " SET external_id = CAST(:neu AS text) || substr(external_id, CAST(:ab AS integer))"
                    " WHERE starts_with(external_id, CAST(:alt AS text))"
                ),
                {"neu": neu, "ab": len(alt) + 1, "alt": alt},
            )
        await session.commit()
    bestand.storage.id_bases.add(neu, alt)
    prozessor = OParlProcessor(bestand.storage.id_bases)

    beratung = {
        "id": f"{neu}consultation/1",
        "type": "https://schema.oparl.org/1.1/Consultation",
        "meeting": f"{neu}meeting/1",
        "agendaItem": f"{neu}agendaitem/1",
    }
    daten = {
        "id": f"{neu}paper/1",
        "type": "https://schema.oparl.org/1.1/Paper",
        "name": "Mehr Bänke im Park",
        "paperType": "Antrag",
        "modified": "2026-09-01T10:00:00+02:00",
        "consultation": [beratung],
    }
    assert (
        await bestand.storage.upsert_paper(prozessor.process_paper(daten, f"{neu}body/1"), bestand.body_id) == vorlage
    )

    assert await bestand.wert("SELECT count(*) FROM oparl_papers") == 1
    assert await bestand.wert("SELECT external_id FROM oparl_papers") == f"{neu}paper/1"
    ereignis = next(e for e in await bestand.ereignisse() if e["type"] == "ris.consultation.changed")
    assert ereignis["aggregate_id"] == canonical_id(CONSULTATION)
    assert ereignis["payload"] == {
        "consultation": str(canonical_id(CONSULTATION)),
        "paper": str(vorlage),
        "change": "added",
        "meeting": str(sitzung),
        "agenda_item": str(canonical_id(ITEM)),
    }


# --- Eingebettete Beratungen ohne Sitzung und Tagesordnungspunkt (ALLRIS) ------------------------------


async def test_eingebettete_beratung_ohne_bezuege_behaelt_sitzung_und_top(bestand: Bestand) -> None:
    """ALLRIS bettet Beratungen in Vorlagen ohne Sitzung und TOP ein; die Beratungsliste liefert beides."""
    paper_id = await bestand.paper()
    await bestand.meeting(agendaItem=[top()])
    aus_der_liste = bestand.processor.process_consultation(
        {
            "id": CONSULTATION,
            "type": "https://schema.oparl.org/1.1/Consultation",
            "paper": PAPER,
            "meeting": MEETING,
            "agendaitem": ITEM,
            "role": "Vorberatung",
        },
        BODY,
    )
    await bestand.storage.upsert_consultation(aus_der_liste, bestand.body_id, paper_id)

    # Abgleich der Vorlage mit der eingebetteten Beratung: ohne Sitzung und TOP, neue Rolle
    await bestand.paper(
        consultation=[{"id": CONSULTATION, "type": "https://schema.oparl.org/1.1/Consultation", "role": "Entscheidung"}]
    )

    zeile = "SELECT {} FROM oparl_consultations WHERE external_id = :e"
    assert await bestand.wert(zeile.format("agenda_item_external_id"), e=CONSULTATION) == ITEM
    assert await bestand.wert(zeile.format("meeting_external_id"), e=CONSULTATION) == MEETING
    assert await bestand.wert(zeile.format("paper_external_id"), e=CONSULTATION) == PAPER
    assert await bestand.wert(zeile.format("role"), e=CONSULTATION) == "Entscheidung"


# --- Dateigröße (Issue #786) ---------------------------------------------------------------------------------------


async def test_abgleich_ohne_groesse_behaelt_die_vorhandene(bestand: Bestand) -> None:
    """Liefert die Quelle keine Größe, überschreibt der Abgleich eine vorhandene nicht mit NULL."""
    file_id = await bestand.storage.upsert_file(bestand.processor.process_file(datei(size=4711), BODY), bestand.body_id)
    assert await bestand.wert("SELECT size FROM oparl_files WHERE id = :id", id=file_id) == 4711

    await bestand.storage.upsert_file(bestand.processor.process_file(datei(), BODY), bestand.body_id)
    assert await bestand.wert("SELECT size FROM oparl_files WHERE id = :id", id=file_id) == 4711

    await bestand.storage.upsert_file(bestand.processor.process_file(datei(size=815), BODY), bestand.body_id)
    assert await bestand.wert("SELECT size FROM oparl_files WHERE id = :id", id=file_id) == 815


# --- Löschabgleich (Issue #787) -------------------------------------------------------------------------------------


async def test_in_der_quelle_fehlende_datei_wird_weder_erkannt_noch_indexiert(bestand: Bestand) -> None:
    """Liefert die Download-Adresse 404/410 (von Django gesperrt), lässt der Ingestor Text und Suche aus."""
    paper_id = await bestand.paper()
    file_id = await bestand.storage.upsert_file(bestand.processor.process_file(datei(), BODY), bestand.body_id)

    async def setzen(sql: str) -> None:
        async with bestand.storage.get_session() as session:
            await session.execute(text(f"UPDATE oparl_files SET {sql} WHERE id = :id"), {"id": file_id})
            await session.commit()

    async def dateien_mit_text() -> list[uuid.UUID]:
        return [f.id async for seite in bestand.storage.iter_files_with_text(bestand.body_id) for f in seite]

    async def vorgaenge_mit_text() -> list[uuid.UUID]:
        zeilen = await bestand.storage.get_files_with_text_for_papers(bestand.body_id, [paper_id])
        return [zeile.paper_id for zeile in zeilen]

    await setzen(f"text_content = 'Text', text_extraction_status = 'completed', paper_id = '{paper_id}'")
    assert await dateien_mit_text() == [file_id]
    assert await vorgaenge_mit_text() == [paper_id]

    # Gesperrt: Der Text bleibt bis zum Löschen nach Frist, wird aber weder als Datei noch im Vorgang indexiert
    await setzen("source_missing_since = now()")
    assert await dateien_mit_text() == []
    assert await vorgaenge_mit_text() == []

    await setzen("text_extraction_status = 'pending'")
    assert await bestand.storage.get_pending_files(bestand.body_id) == []


# --- Ablage nach SHA-256 (Issue #788) -------------------------------------------------------------------------------


async def test_ablage_zaehlt_referenzen_und_gibt_alte_frei(bestand: Bestand, tmp_path: Path) -> None:
    """Gleicher Inhalt liegt einmal in der Ablage; neue Fassungen geben die alte Referenz frei."""
    root = tmp_path / "sha256"
    (root / "tmp").mkdir(parents=True)

    def spool(inhalt: bytes) -> tuple[str, Path]:
        quelle = root / "tmp" / f"{uuid.uuid4().hex}.part"
        quelle.write_bytes(inhalt)
        return hashlib.sha256(inhalt).hexdigest(), quelle

    erste = await bestand.storage.upsert_file(bestand.processor.process_file(datei(), BODY), bestand.body_id)
    zweite = await bestand.storage.upsert_file(
        bestand.processor.process_file(datei(id=f"{FILE}-2", accessUrl=f"{FILE}-2/download"), BODY), bestand.body_id
    )
    # Die erste Datei liegt noch im bisherigen Layout je Kommune
    alt = tmp_path / "kommune" / "2026" / "erste.pdf"
    alt.parent.mkdir(parents=True)
    alt.write_bytes(b"alt")
    async with bestand.storage.get_session() as session:
        await session.execute(
            text("UPDATE oparl_files SET local_path = :p, local_status = 'ok' WHERE id = :id"),
            {"p": str(alt), "id": erste},
        )
        await session.commit()

    sha_a, quelle = spool(b"%PDF-1.4 Inhalt A")
    ziel_a = root / sha_a[:2] / sha_a
    assert await bestand.storage.attach_file_blob(erste, sha_a, 17, quelle, ziel_a)
    sha_a2, quelle2 = spool(b"%PDF-1.4 Inhalt A")
    assert await bestand.storage.attach_file_blob(zweite, sha_a2, 17, quelle2, ziel_a)

    assert ziel_a.read_bytes() == b"%PDF-1.4 Inhalt A"
    assert not quelle.exists() and not quelle2.exists()
    assert not alt.exists(), "Kopie im alten Layout ist nach dem Umzug weg"
    assert await bestand.wert("SELECT ref_count FROM oparl_file_blobs WHERE sha256 = :s", s=sha_a) == 2
    assert await bestand.wert("SELECT local_path FROM oparl_files WHERE id = :id", id=erste) == str(ziel_a)
    assert await bestand.wert("SELECT local_size FROM oparl_files WHERE id = :id", id=erste) == 17

    # Erneut derselbe Inhalt: keine zweite Referenz
    sha_a3, quelle3 = spool(b"%PDF-1.4 Inhalt A")
    assert await bestand.storage.attach_file_blob(erste, sha_a3, 17, quelle3, ziel_a)
    assert await bestand.wert("SELECT ref_count FROM oparl_file_blobs WHERE sha256 = :s", s=sha_a) == 2

    # Neue Fassung der ersten Datei: A verliert eine Referenz, B bekommt eine
    sha_b, quelle_b = spool(b"%PDF-1.4 Inhalt B geschwaerzt")
    assert await bestand.storage.attach_file_blob(erste, sha_b, 29, quelle_b, root / sha_b[:2] / sha_b)
    assert await bestand.wert("SELECT ref_count FROM oparl_file_blobs WHERE sha256 = :s", s=sha_a) == 1
    assert await bestand.wert("SELECT ref_count FROM oparl_file_blobs WHERE sha256 = :s", s=sha_b) == 1

    # Auch die zweite wechselt: A ist verwaist, die Datei bleibt bis zum Aufräumen (Django) liegen
    sha_b2, quelle_b2 = spool(b"%PDF-1.4 Inhalt B geschwaerzt")
    assert await bestand.storage.attach_file_blob(zweite, sha_b2, 29, quelle_b2, root / sha_b[:2] / sha_b)
    assert await bestand.wert("SELECT ref_count FROM oparl_file_blobs WHERE sha256 = :s", s=sha_a) == 0
    assert await bestand.wert("SELECT orphaned_at IS NOT NULL FROM oparl_file_blobs WHERE sha256 = :s", s=sha_a)
    assert ziel_a.exists()


async def test_ablage_rechte_und_geteilter_pfad_ohne_referenz(bestand: Bestand, tmp_path: Path) -> None:
    """Abgelegte Inhalte sind lesbar (0644); ein Pfad unter sha256/ ohne Referenz wird nie gelöscht."""
    import stat

    root = tmp_path / "sha256"
    (root / "tmp").mkdir(parents=True)

    def spool(inhalt: bytes) -> tuple[str, Path]:
        quelle = root / "tmp" / f"{uuid.uuid4().hex}.part"
        quelle.write_bytes(inhalt)
        os.chmod(quelle, 0o600)
        return hashlib.sha256(inhalt).hexdigest(), quelle

    erste = await bestand.storage.upsert_file(bestand.processor.process_file(datei(), BODY), bestand.body_id)
    zweite = await bestand.storage.upsert_file(
        bestand.processor.process_file(datei(id=f"{FILE}-2", accessUrl=f"{FILE}-2/download"), BODY), bestand.body_id
    )
    sha_a, quelle = spool(b"%PDF-1.4 Inhalt A")
    ziel_a = root / sha_a[:2] / sha_a
    assert await bestand.storage.attach_file_blob(erste, sha_a, 17, quelle, ziel_a)
    if os.name != "nt":
        assert stat.S_IMODE(ziel_a.stat().st_mode) == 0o644

    # Die zweite Datei zeigt ohne Referenz auf den Inhalt der ersten (Absturz, alter Code)
    async with bestand.storage.get_session() as session:
        await session.execute(
            text("UPDATE oparl_files SET local_path = :p, local_status = 'ok' WHERE id = :id"),
            {"p": str(ziel_a), "id": zweite},
        )
        await session.commit()
    sha_b, quelle_b = spool(b"%PDF-1.4 Inhalt B")
    assert await bestand.storage.attach_file_blob(zweite, sha_b, 17, quelle_b, root / sha_b[:2] / sha_b)
    assert ziel_a.exists(), "geteilter Inhalt bleibt"
    assert await bestand.wert("SELECT ref_count FROM oparl_file_blobs WHERE sha256 = :s", s=sha_a) == 1
