# Generated by Django 6.0.1 on 2026-01-18 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "codename",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("category", models.CharField(max_length=50, verbose_name="Kategorie")),
            ],
            options={
                "verbose_name": "Berechtigung",
                "verbose_name_plural": "Berechtigungen",
                "ordering": ["category", "codename"],
            },
        ),
        migrations.CreateModel(
            name="PartyGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL-Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="parties/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#6366f1", max_length=7, verbose_name="Primärfarbe"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Einstellungen"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tenants.partygroup",
                        verbose_name="Übergeordnete Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parteigruppe",
                "verbose_name_plural": "Parteigruppen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL-Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organizations/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#6366f1", max_length=7, verbose_name="Primärfarbe"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#8b5cf6", max_length=7, verbose_name="Sekundärfarbe"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Kontakt-E-Mail"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                ("smtp_host", models.CharField(blank=True, max_length=200)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_username", models.CharField(blank=True, max_length=200)),
                ("smtp_password_encrypted", models.BinaryField(blank=True, null=True)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("smtp_from_email", models.EmailField(blank=True, max_length=254)),
                ("smtp_from_name", models.CharField(blank=True, max_length=200)),
                (
                    "encryption_key",
                    models.BinaryField(
                        blank=True,
                        help_text="Encrypted with master key, used for tenant data",
                        null=True,
                        verbose_name="Verschlüsselungsschlüssel",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Einstellungen"
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False,
                        help_text="Alle Mitglieder müssen 2FA aktivieren",
                        verbose_name="2FA erforderlich",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        help_text="OParl-Body für RIS-Daten (z.B. Stadt Münster)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_organizations",
                        to="insight_core.oparlbody",
                        verbose_name="Kommune/Region",
                    ),
                ),
                (
                    "oparl_organizations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Verknüpfte Gremien im RIS (z.B. Fraktion, Ausschüsse)",
                        related_name="work_organizations",
                        to="insight_core.oparlorganization",
                        verbose_name="OParl-Gremien",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eigentümer",
                    ),
                ),
                (
                    "party_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Übergeordnete Parteistruktur (z.B. Volt NRW)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="tenants.partygroup",
                        verbose_name="Parteigruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisationen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Hat alle Berechtigungen",
                        verbose_name="Administrator",
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="Kann nicht gelöscht werden",
                        verbose_name="Systemrolle",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Höhere Priorität bei Konflikten",
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(default=False, verbose_name="2FA erforderlich"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6b7280", max_length=7, verbose_name="Farbe"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="tenants.permission",
                        verbose_name="Berechtigungen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rolle",
                "verbose_name_plural": "Rollen",
                "ordering": ["-priority", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Persönliche Nachricht in der Einladungs-E-Mail",
                        verbose_name="Nachricht",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Gültig bis")),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eingeladen von",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invitations",
                        to="tenants.role",
                        verbose_name="Rollen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einladung",
                "verbose_name_plural": "Einladungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Beigetreten"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitation_accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Einladung angenommen"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eingeladen von",
                    ),
                ),
                (
                    "oparl_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verknüpfung zur Person im RIS",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_memberships",
                        to="insight_core.oparlperson",
                        verbose_name="OParl-Person",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "denied_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Explizit verweigert, auch wenn Rolle sie hat",
                        related_name="denied_memberships",
                        to="tenants.permission",
                        verbose_name="Verweigerte Berechtigungen",
                    ),
                ),
                (
                    "individual_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Zusätzlich zu Rollenberechtigungen",
                        related_name="individual_memberships",
                        to="tenants.permission",
                        verbose_name="Individuelle Berechtigungen",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="memberships",
                        to="tenants.role",
                        verbose_name="Rollen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitgliedschaft",
                "verbose_name_plural": "Mitgliedschaften",
                "ordering": ["-joined_at"],
                "unique_together": {("user", "organization")},
            },
        ),
    ]
