# Generated by Django 6.0.1 on 2026-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        ("tenants", "0003_make_owner_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="oparl_committees",
            field=models.ManyToManyField(
                blank=True,
                help_text="OParl-Gremien deren Sitzungen angezeigt werden",
                related_name="work_memberships",
                to="insight_core.oparlorganization",
                verbose_name="Zugewiesene Gremien",
            ),
        ),
    ]
