# Generated by Django 6.0.1 on 2026-01-24 15:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_membership_oparl_committees"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="administration_email",
            field=models.EmailField(
                blank=True,
                help_text="Standard-E-Mail für Anträge an die Verwaltung",
                max_length=254,
                verbose_name="Verwaltungs-E-Mail",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="coalition_name",
            field=models.CharField(
                blank=True,
                help_text="z.B. 'Ampel', 'Rot-Grün'",
                max_length=200,
                verbose_name="Koalitionsname",
            ),
        ),
        migrations.CreateModel(
            name="CouncilParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "short_name",
                    models.CharField(max_length=20, verbose_name="Kurzname"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-Mail für Antragsversand",
                        max_length=254,
                        verbose_name="E-Mail",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Ansprechpartner"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "color",
                    models.CharField(default="#6b7280", max_length=7, verbose_name="Farbe"),
                ),
                (
                    "is_coalition_member",
                    models.BooleanField(default=False, verbose_name="Koalitionspartner"),
                ),
                (
                    "coalition_order",
                    models.IntegerField(default=0, verbose_name="Reihenfolge in Koalition"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="council_parties",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ratsfraktion",
                "verbose_name_plural": "Ratsfraktionen",
                "ordering": ["coalition_order", "name"],
                "unique_together": {("organization", "short_name")},
            },
        ),
    ]
