# Generated by Django 6.0.1 on 2026-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_add_coalition_and_email_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_sworn_in",
            field=models.BooleanField(
                default=False,
                help_text="Zugang zu nicht-öffentlichen Inhalten nach Verpflichtungserklärung",
                verbose_name="Vereidigt",
            ),
        ),
    ]
