# Generated by Django 6.0 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_add_is_sworn_in_to_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ai_api_key_encrypted",
            field=models.BinaryField(
                blank=True,
                help_text="Wird tenant-spezifisch AES-256-GCM verschlüsselt gespeichert.",
                null=True,
                verbose_name="KI API Key (verschlüsselt)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_base_url",
            field=models.URLField(
                blank=True,
                help_text="Optional für OpenAI-kompatible Endpunkte. Bei Nebius wird standardmäßig https://api.tokenfactory.nebius.com/v1/ genutzt.",
                verbose_name="KI API Base URL",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Erlaubt KI-Chat und KI-Aktionen im Dokumenten-Editor.",
                verbose_name="KI im DMS aktiviert",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_model",
            field=models.CharField(
                default="openai/gpt-oss-120b",
                help_text="Standard fuer Work: openai/gpt-oss-120b (Nebius).",
                max_length=100,
                verbose_name="KI-Modell",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("nebius", "Nebius TokenFactory (Standard)"),
                    ("ovh", "OVHcloud AI Endpoints"),
                    ("ionos", "IONOS AI Model Hub"),
                ],
                default="nebius",
                max_length=20,
                verbose_name="KI-Anbieter",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_token_limit_daily",
            field=models.PositiveIntegerField(default=250000, verbose_name="Token-Limit pro Tag"),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_token_limit_monthly",
            field=models.PositiveIntegerField(default=3000000, verbose_name="Token-Limit pro Monat"),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_token_limit_weekly",
            field=models.PositiveIntegerField(default=1000000, verbose_name="Token-Limit pro Woche"),
        ),
    ]
