# Generated by Django 5.2.11 on 2026-03-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_add_ai_provider_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="ai_api_key_encrypted",
            field=models.BinaryField(
                blank=True,
                help_text="Wird tenant-spezifisch AES-256-GCM verschluesselt gespeichert.",
                null=True,
                verbose_name="KI API Key (verschluesselt)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="ai_base_url",
            field=models.URLField(
                blank=True,
                help_text="Optional fuer OpenAI-kompatible Endpunkte. Bei Nebius wird standardmaessig https://api.tokenfactory.nebius.com/v1/ genutzt.",
                verbose_name="KI API Base URL",
            ),
        ),
    ]
