# Generated by Django 6.0.3 on 2026-03-24 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_organization_registration_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='z.B. Ratsbüro, OB-Büro', max_length=200, verbose_name='Bezeichnung')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_contacts', to='tenants.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Verwaltungskontakt',
                'verbose_name_plural': 'Verwaltungskontakte',
                'ordering': ['order', 'label'],
            },
        ),
    ]
