# Generated by Django 6.0.6 on 2026-07-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0020_org_wide_meeting_prep_phase1"),
        ("tenants", "0011_organization_saas_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="bodies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Alle verknüpften OParl-Bodies (inkl. der primären Kommune)",
                related_name="linked_work_organizations",
                to="insight_core.oparlbody",
                verbose_name="Kommunen/Regionen",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Parteien/Parteigruppen, denen die Organisation angehört",
                related_name="member_organizations",
                to="tenants.partygroup",
                verbose_name="Parteien",
            ),
        ),
        migrations.AddField(
            model_name="partygroup",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="z.B. SPD, B90/Grüne, Volt",
                max_length=20,
                verbose_name="Kürzel",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="body",
            field=models.ForeignKey(
                blank=True,
                help_text="Primärer OParl-Body für RIS-Daten (z.B. Stadt Münster)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_organizations",
                to="insight_core.oparlbody",
                verbose_name="Primäre Kommune/Region",
            ),
        ),
    ]
