# Generated by Django 6.0.6 on 2026-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0020_org_wide_meeting_prep_phase1"),
        ("tenants", "0013_backfill_bodies_parties"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="followed_organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vom Mitglied selbst gewählte Gremien für personalisierte Ansichten",
                related_name="following_memberships",
                to="insight_core.oparlorganization",
                verbose_name="Meine Gremien",
            ),
        ),
    ]
