# Generated by Django 6.0.6 on 2026-07-09 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_membership_followed_organizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Rot"),
                            ("orange", "Orange"),
                            ("amber", "Gelb"),
                            ("green", "Grün"),
                            ("teal", "Türkis"),
                            ("blue", "Blau"),
                            ("indigo", "Indigo"),
                            ("purple", "Lila"),
                            ("pink", "Rosa"),
                            ("gray", "Grau"),
                        ],
                        default="blue",
                        max_length=20,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sortierung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thema",
                "verbose_name_plural": "Themen",
                "ordering": ["sort_order", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="expertise_topics",
            field=models.ManyToManyField(
                blank=True,
                help_text="Themen, in denen dieses Mitglied Fachwissen hat",
                related_name="experts",
                to="tenants.topic",
                verbose_name="Fachgebiete",
            ),
        ),
    ]
