# Generated by Django 6.0.6 on 2026-07-10 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0020_org_wide_meeting_prep_phase1"),
        ("tenants", "0016_ai_token_limit_monthly_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_guest",
            field=models.BooleanField(
                default=False,
                help_text="Gast-Zugang: sieht ausschließlich explizit freigegebene Dokumente, hat keine Rollen und keine Berechtigungen. Zählt gegen das Gast-Limit.",
                verbose_name="Gast",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="guest_limit",
            field=models.PositiveIntegerField(
                default=25,
                help_text="Maximale aktive Gast-Zugänge (Standard 25, per Addon erweiterbar)",
                verbose_name="Gast-Limit",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="bodies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Weitere OParl-Bodies, deren Ratsinformationen die Organisation einsehen kann",
                related_name="linked_work_organizations",
                to="insight_core.oparlbody",
                verbose_name="Weitere Kommunen (RIS-Zugriff)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="body",
            field=models.ForeignKey(
                blank=True,
                help_text="Heimat-Kommune der Organisation (Pflicht bei aktiven Organisationen)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_organizations",
                to="insight_core.oparlbody",
                verbose_name="Stadt/Kommune",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="member_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximale aktive Mitglieder laut Plan (leer = unbegrenzt). Gäste zählen nicht mit.",
                null=True,
                verbose_name="Mitglieder-Limit",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="party_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Partei, der die Organisation angehört (Pflicht bei aktiven Organisationen)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="tenants.partygroup",
                verbose_name="Partei",
            ),
        ),
    ]
