# Generated by Django 5.2.11 on 2026-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_backfill_party_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="publish_protocols",
            field=models.BooleanField(
                default=False,
                help_text="Expliziter Opt-in: genehmigte Fraktionsprotokolle erscheinen in der öffentlichen Protokollansicht des Bürgerportals (nur Ö-Teile).",
                verbose_name="Protokolle veröffentlichen",
            ),
        ),
    ]
