# Generated by Django 5.2.11 on 2026-07-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_einladung_und_protokoll_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="mail_sender_mode",
            field=models.CharField(
                choices=[
                    ("mandari", "mandari-Standardversand"),
                    ("smtp", "Eigenes SMTP der Organisation"),
                ],
                default="mandari",
                help_text="Fraktions-Mails über eigenes SMTP oder den mandari-Standard versenden",
                max_length=10,
                verbose_name="Versandweg",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="smtp_fallback_to_mandari",
            field=models.BooleanField(
                default=True,
                help_text="Deaktiviert: Der Versand schlägt bei SMTP-Fehlern sichtbar fehl",
                verbose_name="Bei SMTP-Fehler auf mandari-Versand zurückfallen",
            ),
        ),
    ]
