# Generated by Django 6.0.1 on 2026-01-18 20:12

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaItemNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Nur ich"),
                            ("organization", "Meine Organisation"),
                            ("party", "Partei-weit"),
                            ("regional", "Regional (gleiche Kommune)"),
                        ],
                        default="organization",
                        max_length=20,
                        verbose_name="Sichtbarkeit",
                    ),
                ),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Inhalt"),
                ),
                (
                    "is_decision",
                    models.BooleanField(
                        default=False,
                        help_text="Markiert diese Notiz als offiziellen Fraktionsbeschluss",
                        verbose_name="Als Beschluss markiert",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Angeheftet"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_notes",
                        to="insight_core.oparlagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_notes",
                        to="tenants.membership",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_notes",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "TOP-Notiz",
                "verbose_name_plural": "TOP-Notizen",
                "ordering": ["-is_pinned", "-is_decision", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FactionMeeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("start", models.DateTimeField(verbose_name="Beginn")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=500, verbose_name="Ort"),
                ),
                (
                    "is_virtual",
                    models.BooleanField(default=False, verbose_name="Online-Sitzung"),
                ),
                ("video_link", models.URLField(blank=True, verbose_name="Video-Link")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("planned", "Geplant"),
                            ("invited", "Eingeladen"),
                            ("ongoing", "Läuft"),
                            ("completed", "Abgeschlossen"),
                            ("cancelled", "Abgesagt"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invitation_sent",
                    models.BooleanField(
                        default=False, verbose_name="Einladung versendet"
                    ),
                ),
                (
                    "invitation_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Einladung versendet am"
                    ),
                ),
                (
                    "protocol_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Protokoll"),
                ),
                (
                    "protocol_approved",
                    models.BooleanField(
                        default=False, verbose_name="Protokoll genehmigt"
                    ),
                ),
                ("protocol_approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_faction_meetings",
                        to="tenants.membership",
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faction_meetings",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "protocol_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_protocols",
                        to="tenants.membership",
                        verbose_name="Genehmigt von",
                    ),
                ),
                (
                    "related_meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Öffentliche Sitzung die in dieser Fraktionssitzung vorbereitet wird",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faction_preparations",
                        to="insight_core.oparlmeeting",
                        verbose_name="Vorbereitete Sitzung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraktionssitzung",
                "verbose_name_plural": "Fraktionssitzungen",
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="FactionAgendaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="TOP-Nr.")),
                ("title", models.CharField(max_length=500, verbose_name="Titel")),
                (
                    "description_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Beschreibung"
                    ),
                ),
                (
                    "decision_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Beschluss"),
                ),
                (
                    "has_decision",
                    models.BooleanField(
                        default=False, verbose_name="Beschluss gefasst"
                    ),
                ),
                (
                    "votes_for",
                    models.PositiveIntegerField(default=0, verbose_name="Ja-Stimmen"),
                ),
                (
                    "votes_against",
                    models.PositiveIntegerField(default=0, verbose_name="Nein-Stimmen"),
                ),
                (
                    "votes_abstain",
                    models.PositiveIntegerField(default=0, verbose_name="Enthaltungen"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faction_items",
                        to="insight_core.oparlagendaitem",
                        verbose_name="Öffentlicher TOP",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="work.factionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraktions-TOP",
                "verbose_name_plural": "Fraktions-TOPs",
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="FactionMeetingSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="z.B. 'Wöchentliche Fraktionssitzung'",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("weekly", "Wöchentlich"),
                            ("biweekly", "Alle 2 Wochen"),
                            ("monthly", "Monatlich"),
                            ("monthly_first", "Jeden 1. im Monat"),
                            ("monthly_last", "Jeden letzten im Monat"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Wiederholung",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Montag"),
                            (1, "Dienstag"),
                            (2, "Mittwoch"),
                            (3, "Donnerstag"),
                            (4, "Freitag"),
                            (5, "Samstag"),
                            (6, "Sonntag"),
                        ],
                        verbose_name="Wochentag",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Uhrzeit")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Dauer (Minuten)"
                    ),
                ),
                (
                    "default_location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Standard-Ort"
                    ),
                ),
                (
                    "default_video_link",
                    models.URLField(blank=True, verbose_name="Standard-Video-Link"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_schedules",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzungsplan",
                "verbose_name_plural": "Sitzungspläne",
                "ordering": ["weekday", "time"],
            },
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings",
                to="work.factionmeetingschedule",
                verbose_name="Sitzungsplan",
            ),
        ),
        migrations.CreateModel(
            name="MeetingPreparation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notes_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        help_text="Persönliche Notizen zur Sitzung",
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "is_prepared",
                    models.BooleanField(default=False, verbose_name="Vorbereitet"),
                ),
                (
                    "prepared_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vorbereitet am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_preparations",
                        to="insight_core.oparlmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_preparations",
                        to="tenants.membership",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_preparations",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzungsvorbereitung",
                "verbose_name_plural": "Sitzungsvorbereitungen",
                "ordering": ["-meeting__start"],
            },
        ),
        migrations.CreateModel(
            name="AgendaItemPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("for", "Zustimmung"),
                            ("against", "Ablehnung"),
                            ("abstain", "Enthaltung"),
                            ("discuss", "Diskussionsbedarf"),
                            ("defer", "Vertagen"),
                            ("none", "Keine Position"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Position",
                    ),
                ),
                (
                    "notes_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        help_text="Persönliche Notizen zur Position",
                        verbose_name="Begründung",
                    ),
                ),
                (
                    "speech_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notizen für den Redebeitrag",
                        verbose_name="Redenotizen",
                    ),
                ),
                (
                    "estimated_speech_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Geschätzte Redezeit (Sekunden)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_positions",
                        to="insight_core.oparlagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="work.meetingpreparation",
                        verbose_name="Vorbereitung",
                    ),
                ),
            ],
            options={
                "verbose_name": "TOP-Position",
                "verbose_name_plural": "TOP-Positionen",
                "ordering": ["agenda_item__number"],
            },
        ),
        migrations.CreateModel(
            name="Motion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "motion_type",
                    models.CharField(
                        choices=[
                            ("motion", "Antrag"),
                            ("inquiry", "Anfrage"),
                            ("statement", "Stellungnahme"),
                            ("amendment", "Änderungsantrag"),
                        ],
                        default="motion",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titel")),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Öffentliche Kurzfassung",
                        verbose_name="Zusammenfassung",
                    ),
                ),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Inhalt"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("review", "In Prüfung"),
                            ("approved", "Freigegeben"),
                            ("submitted", "Eingereicht"),
                            ("completed", "Erledigt"),
                            ("rejected", "Abgelehnt"),
                            ("archived", "Archiviert"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "yjs_document",
                    models.BinaryField(
                        blank=True,
                        help_text="Binary state for real-time collaboration",
                        null=True,
                        verbose_name="Yjs-Dokument",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eingereicht am"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_motions",
                        to="tenants.membership",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motions",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "parent_motion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="work.motion",
                        verbose_name="Bezugsantrag",
                    ),
                ),
                (
                    "related_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_motions",
                        to="insight_core.oparlmeeting",
                        verbose_name="Ziel-Sitzung",
                    ),
                ),
                (
                    "related_paper",
                    models.ForeignKey(
                        blank=True,
                        help_text="OParl-Vorlage wenn eingereicht",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_motions",
                        to="insight_core.oparlpaper",
                        verbose_name="Verknüpfter Vorgang",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antrag",
                "verbose_name_plural": "Anträge",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MotionComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "selection_start",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Auswahl Start"
                    ),
                ),
                (
                    "selection_end",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Auswahl Ende"
                    ),
                ),
                (
                    "selected_text",
                    models.TextField(blank=True, verbose_name="Ausgewählter Text"),
                ),
                ("content", models.TextField(verbose_name="Kommentar")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erledigt am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_comments",
                        to="tenants.membership",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="work.motion",
                        verbose_name="Antrag",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="work.motioncomment",
                        verbose_name="Antwort auf",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to="tenants.membership",
                        verbose_name="Erledigt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragskommentar",
                "verbose_name_plural": "Antragskommentare",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MotionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="motions/documents/%Y/%m/", verbose_name="Datei"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Dateiname"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME-Typ"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dateigröße (Bytes)"
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Extrahierter Text"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="work.motion",
                        verbose_name="Antrag",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to="tenants.membership",
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragsdokument",
                "verbose_name_plural": "Antragsdokumente",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MotionRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Version")),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Inhalt"),
                ),
                (
                    "change_summary",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Änderungszusammenfassung",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_revisions",
                        to="tenants.membership",
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="work.motion",
                        verbose_name="Antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragsversion",
                "verbose_name_plural": "Antragsversionen",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="MotionShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("user", "Einzelner Benutzer"),
                            ("role", "Rolle"),
                            ("organization", "Organisation"),
                            ("party_group", "Parteigruppe"),
                            ("regional", "Regional (OParl Body)"),
                        ],
                        max_length=20,
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("view", "Lesen"),
                            ("comment", "Kommentieren"),
                            ("edit", "Bearbeiten"),
                            ("admin", "Verwalten"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Berechtigung",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optionale Nachricht an den Empfänger",
                        verbose_name="Nachricht",
                    ),
                ),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_motions",
                        to="insight_core.oparlbody",
                        verbose_name="OParl Body",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_motion_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="work.motion",
                        verbose_name="Antrag",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_motions",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "party_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_motions",
                        to="tenants.partygroup",
                        verbose_name="Parteigruppe",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_shares",
                        to="tenants.role",
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragsfreigabe",
                "verbose_name_plural": "Antragsfreigaben",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MotionTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "html_template",
                    models.TextField(
                        help_text="HTML mit Platzhaltern wie {{title}}, {{content}}, {{date}}",
                        verbose_name="HTML-Vorlage",
                    ),
                ),
                (
                    "signature_block",
                    models.TextField(blank=True, verbose_name="Signaturblock"),
                ),
                (
                    "is_shared_party",
                    models.BooleanField(
                        default=False, verbose_name="Partei-weit teilen"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Standard-Vorlage"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_templates",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragsvorlage",
                "verbose_name_plural": "Antragsvorlagen",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="motion",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motions",
                to="work.motiontemplate",
                verbose_name="Vorlage",
            ),
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Betreff")),
                (
                    "description_encrypted",
                    apps.common.encryption.EncryptedTextField(
                        verbose_name="Beschreibung"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Fehler melden"),
                            ("feature", "Feature-Wunsch"),
                            ("question", "Frage"),
                            ("account", "Konto/Zugang"),
                            ("other", "Sonstiges"),
                        ],
                        default="question",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niedrig"),
                            ("normal", "Normal"),
                            ("high", "Hoch"),
                            ("urgent", "Dringend"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("in_progress", "In Bearbeitung"),
                            ("waiting", "Wartet auf Antwort"),
                            ("resolved", "Gelöst"),
                            ("closed", "Geschlossen"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelöst am"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geschlossen am"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Zugewiesen an",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tickets",
                        to="tenants.membership",
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support-Ticket",
                "verbose_name_plural": "Support-Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicketMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Nachricht"),
                ),
                (
                    "is_internal",
                    models.BooleanField(default=False, verbose_name="Interne Notiz"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_messages",
                        to="tenants.membership",
                        verbose_name="Autor (Mitglied)",
                    ),
                ),
                (
                    "author_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor (Support)",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="work.supportticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket-Nachricht",
                "verbose_name_plural": "Ticket-Nachrichten",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicketAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="support/attachments/%Y/%m/", verbose_name="Datei"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Dateiname"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME-Typ"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dateigröße (Bytes)"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="work.supportticket",
                        verbose_name="Ticket",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="work.supportticketmessage",
                        verbose_name="Nachricht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket-Anhang",
                "verbose_name_plural": "Ticket-Anhänge",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Hoch"),
                            ("medium", "Mittel"),
                            ("low", "Niedrig"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erledigt am"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Fällig am"),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erinnerung"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="tenants.membership",
                        verbose_name="Zugewiesen an",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="tenants.membership",
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "related_agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_tasks",
                        to="insight_core.oparlagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "related_faction_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="work.factionmeeting",
                        verbose_name="Fraktionssitzung",
                    ),
                ),
                (
                    "related_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_tasks",
                        to="insight_core.oparlmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "related_motion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="work.motion",
                        verbose_name="Antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufgabe",
                "verbose_name_plural": "Aufgaben",
                "ordering": ["is_completed", "-priority", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="Kommentar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to="tenants.membership",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="work.task",
                        verbose_name="Aufgabe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufgabenkommentar",
                "verbose_name_plural": "Aufgabenkommentare",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FactionAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Eingeladen"),
                            ("confirmed", "Zugesagt"),
                            ("declined", "Abgesagt"),
                            ("tentative", "Vielleicht"),
                            ("present", "Anwesend"),
                            ("absent", "Abwesend"),
                            ("excused", "Entschuldigt"),
                        ],
                        default="invited",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True,
                        help_text="Begründung bei Absage",
                        verbose_name="Nachricht",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Antwort am"
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eingecheckt um"
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ausgecheckt um"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faction_attendances",
                        to="tenants.membership",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="work.factionmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anwesenheit",
                "verbose_name_plural": "Anwesenheiten",
                "ordering": ["membership__user__last_name"],
                "unique_together": {("meeting", "membership")},
            },
        ),
        migrations.CreateModel(
            name="FactionMeetingException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_date",
                    models.DateField(verbose_name="Ursprüngliches Datum"),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("cancelled", "Abgesagt"),
                            ("rescheduled", "Verschoben"),
                            ("special", "Sondertermin"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=500, verbose_name="Grund"),
                ),
                (
                    "new_date",
                    models.DateField(blank=True, null=True, verbose_name="Neues Datum"),
                ),
                (
                    "new_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Neue Uhrzeit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="work.factionmeetingschedule",
                        verbose_name="Sitzungsplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ausnahme",
                "verbose_name_plural": "Ausnahmen",
                "ordering": ["-original_date"],
                "unique_together": {("schedule", "original_date")},
            },
        ),
        migrations.AddIndex(
            model_name="factionmeeting",
            index=models.Index(
                fields=["organization", "start"], name="work_factio_organiz_25e8d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factionmeeting",
            index=models.Index(
                fields=["organization", "status"], name="work_factio_organiz_8441c3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingpreparation",
            unique_together={("membership", "meeting")},
        ),
        migrations.AlterUniqueTogether(
            name="agendaitemposition",
            unique_together={("preparation", "agenda_item")},
        ),
        migrations.AlterUniqueTogether(
            name="motionrevision",
            unique_together={("motion", "version")},
        ),
        migrations.AddIndex(
            model_name="motion",
            index=models.Index(
                fields=["organization", "status"], name="work_motion_organiz_e072cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="motion",
            index=models.Index(
                fields=["organization", "motion_type"],
                name="work_motion_organiz_00e96c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["organization", "status"], name="work_suppor_organiz_390d92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["assigned_to", "status"], name="work_suppor_assigne_3923f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organization", "is_completed"],
                name="work_task_organiz_455760_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "is_completed"],
                name="work_task_assigne_e94637_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["due_date"], name="work_task_due_dat_a634a8_idx"
            ),
        ),
    ]
