# Generated by Django 6.0.1 on 2026-01-22 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_populate_permissions"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="E-Mail-Benachrichtigungen aktiviert"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push-Benachrichtigungen aktiviert"
                    ),
                ),
                (
                    "type_settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Typ-Einstellungen"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Ruhezeiten aktiviert"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        default="22:00",
                        null=True,
                        verbose_name="Ruhezeit Start",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        default="07:00",
                        null=True,
                        verbose_name="Ruhezeit Ende",
                    ),
                ),
                (
                    "email_digest",
                    models.CharField(
                        choices=[
                            ("instant", "Sofort"),
                            ("daily", "Täglich"),
                            ("weekly", "Wöchentlich"),
                            ("never", "Nie"),
                        ],
                        default="instant",
                        max_length=20,
                        verbose_name="E-Mail-Zusammenfassung",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="tenants.membership",
                        verbose_name="Mitgliedschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benachrichtigungseinstellung",
                "verbose_name_plural": "Benachrichtigungseinstellungen",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("meeting_reminder", "Sitzungserinnerung"),
                            ("meeting_updated", "Sitzung aktualisiert"),
                            ("meeting_cancelled", "Sitzung abgesagt"),
                            ("task_assigned", "Aufgabe zugewiesen"),
                            ("task_due_soon", "Aufgabe fällig"),
                            ("task_completed", "Aufgabe erledigt"),
                            ("task_comment", "Kommentar zur Aufgabe"),
                            ("motion_shared", "Antrag geteilt"),
                            ("motion_comment", "Kommentar zum Antrag"),
                            ("motion_status", "Antragsstatus geändert"),
                            ("faction_reminder", "Fraktionssitzung"),
                            ("faction_updated", "Fraktionssitzung aktualisiert"),
                            ("member_joined", "Neues Mitglied"),
                            ("role_changed", "Rolle geändert"),
                            ("system", "Systemnachricht"),
                            ("announcement", "Ankündigung"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="Typ",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("message", models.TextField(verbose_name="Nachricht")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Link"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Gelesen")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gelesen am"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="E-Mail gesendet"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="E-Mail gesendet am"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadaten"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to="tenants.membership",
                        verbose_name="Auslöser",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenants.membership",
                        verbose_name="Empfänger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benachrichtigung",
                "verbose_name_plural": "Benachrichtigungen",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="work_notifi_recipie_cd2da5_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type"],
                        name="work_notifi_recipie_129670_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="work_notifi_created_94f741_idx"
                    ),
                ],
            },
        ),
    ]
