# Generated by Django 6.0.1 on 2026-01-23 02:32

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        ("tenants", "0003_make_owner_nullable"),
        ("work", "0002_add_notification_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactionDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "votes_yes",
                    models.PositiveIntegerField(default=0, verbose_name="Ja-Stimmen"),
                ),
                (
                    "votes_no",
                    models.PositiveIntegerField(default=0, verbose_name="Nein-Stimmen"),
                ),
                (
                    "votes_abstain",
                    models.PositiveIntegerField(default=0, verbose_name="Enthaltungen"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("accepted", "Angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("postponed", "Vertagt"),
                            ("modified", "Geändert angenommen"),
                        ],
                        max_length=20,
                        verbose_name="Ergebnis",
                    ),
                ),
                (
                    "decision_text",
                    models.TextField(
                        blank=True,
                        help_text="Nur ausfüllen wenn abweichend vom TOP",
                        verbose_name="Beschlusstext",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Anmerkungen")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Abstimmungsergebnis",
                "verbose_name_plural": "Abstimmungsergebnisse",
            },
        ),
        migrations.CreateModel(
            name="FactionProtocolEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("speech", "Wortbeitrag"),
                            ("decision", "Beschluss"),
                            ("action", "Aufgabe"),
                            ("note", "Notiz"),
                            ("vote", "Abstimmung"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Inhalt"),
                ),
                (
                    "action_due_date",
                    models.DateField(blank=True, null=True, verbose_name="Fällig bis"),
                ),
                (
                    "action_completed",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Protokolleintrag",
                "verbose_name_plural": "Protokolleinträge",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    "status",
                    "position",
                    "-priority",
                    "due_date",
                    "-created_at",
                ],
                "verbose_name": "Aufgabe",
                "verbose_name_plural": "Aufgaben",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Zu erledigen"),
                    ("in_progress", "In Bearbeitung"),
                    ("done", "Erledigt"),
                ],
                default="todo",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("urgent", "Dringend"),
                    ("high", "Hoch"),
                    ("medium", "Mittel"),
                    ("low", "Niedrig"),
                ],
                default="medium",
                max_length=10,
                verbose_name="Priorität",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organization", "status"], name="work_task_organiz_cde1eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="work_task_assigne_736ca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status", "position"], name="work_task_status_cdeaf7_idx"),
        ),
        migrations.AddField(
            model_name="factiondecision",
            name="agenda_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision",
                to="work.factionagendaitem",
                verbose_name="TOP",
            ),
        ),
        migrations.AddField(
            model_name="factiondecision",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recorded_decisions",
                to="tenants.membership",
                verbose_name="Erfasst von",
            ),
        ),
        migrations.AddField(
            model_name="factionprotocolentry",
            name="action_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocol_actions",
                to="tenants.membership",
                verbose_name="Verantwortlich",
            ),
        ),
        migrations.AddField(
            model_name="factionprotocolentry",
            name="agenda_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocol_entries",
                to="work.factionagendaitem",
                verbose_name="TOP",
            ),
        ),
        migrations.AddField(
            model_name="factionprotocolentry",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_protocol_entries",
                to="tenants.membership",
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="factionprotocolentry",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocol_entries",
                to="work.factionmeeting",
                verbose_name="Sitzung",
            ),
        ),
        migrations.AddField(
            model_name="factionprotocolentry",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protocol_speeches",
                to="tenants.membership",
                verbose_name="Redner",
            ),
        ),
    ]
