# Generated by Django 6.0.1 on 2026-01-23 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0003_add_task_status_and_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="help-circle",
                        max_length=50,
                        verbose_name="Icon (Lucide)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Farbe"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sortierung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KB-Kategorie",
                "verbose_name_plural": "KB-Kategorien",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("slug", models.SlugField(max_length=200, verbose_name="Slug")),
                (
                    "excerpt",
                    models.TextField(blank=True, verbose_name="Kurzbeschreibung"),
                ),
                ("content", models.TextField(verbose_name="Inhalt (Markdown)")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Veröffentlicht"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Hervorgehoben"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Aufrufe"),
                ),
                (
                    "helpful_yes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hilfreich: Ja"
                    ),
                ),
                (
                    "helpful_no",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hilfreich: Nein"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Tags (kommagetrennt)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Veröffentlicht am"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="work.knowledgebasecategory",
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "KB-Artikel",
                "verbose_name_plural": "KB-Artikel",
                "ordering": ["-is_featured", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_helpful", models.BooleanField(verbose_name="War hilfreich")),
                ("comment", models.TextField(blank=True, verbose_name="Kommentar")),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Session-Key"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_feedback",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="work.knowledgebasearticle",
                        verbose_name="Artikel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikel-Feedback",
                "verbose_name_plural": "Artikel-Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgebasearticle",
            index=models.Index(
                fields=["is_published", "category"],
                name="work_knowle_is_publ_79a9bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebasearticle",
            index=models.Index(fields=["tags"], name="work_knowle_tags_14bc0e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgebasearticle",
            unique_together={("category", "slug")},
        ),
    ]
