# Generated by Django 6.0.1 on 2026-01-23 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        ("tenants", "0003_make_owner_nullable"),
        ("work", "0005_initial_knowledge_base_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(max_length=100, verbose_name="Kurzname")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="file-text", max_length=50, verbose_name="Icon (Lucide)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Farbe"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Dokument muss vor Einreichung freigegeben werden",
                        verbose_name="Freigabe erforderlich",
                    ),
                ),
                (
                    "is_submittable",
                    models.BooleanField(
                        default=True,
                        help_text="Kann offiziell eingereicht werden",
                        verbose_name="Einreichbar",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Standard-Typ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sortierung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dokumenttyp",
                "verbose_name_plural": "Dokumenttypen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationLetterhead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="motions/letterheads/%Y/%m/", verbose_name="PDF-Datei"
                    ),
                ),
                (
                    "content_margin_top",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Abstand vom oberen Rand zum Textbereich",
                        verbose_name="Abstand oben (mm)",
                    ),
                ),
                (
                    "content_margin_left",
                    models.PositiveIntegerField(
                        default=25, verbose_name="Abstand links (mm)"
                    ),
                ),
                (
                    "content_margin_right",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Abstand rechts (mm)"
                    ),
                ),
                (
                    "content_margin_bottom",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Abstand unten (mm)"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Arial", max_length=100, verbose_name="Schriftart"
                    ),
                ),
                (
                    "font_size",
                    models.PositiveIntegerField(
                        default=11, verbose_name="Schriftgröße (pt)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Standard-Briefkopf"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Briefkopf",
                "verbose_name_plural": "Briefköpfe",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="motion",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumente",
            },
        ),
        migrations.AlterModelOptions(
            name="motiontemplate",
            options={
                "ordering": ["-is_default", "name"],
                "verbose_name": "Dokumentvorlage",
                "verbose_name_plural": "Dokumentvorlagen",
            },
        ),
        migrations.RemoveIndex(
            model_name="motion",
            name="work_motion_organiz_00e96c_idx",
        ),
        migrations.RemoveField(
            model_name="motiontemplate",
            name="html_template",
        ),
        migrations.AddField(
            model_name="motiontemplate",
            name="content_template",
            field=models.TextField(
                blank=True,
                help_text="Vorausgefüllter Inhalt für neue Dokumente",
                verbose_name="Inhaltsvorlage",
            ),
        ),
        migrations.AddField(
            model_name="motiontemplate",
            name="structure_hints",
            field=models.TextField(
                blank=True,
                help_text="Hinweise für die KI-Unterstützung (z.B. Abschnitte, Formatierung)",
                verbose_name="Strukturhinweise",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="motion_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("motion", "Antrag"),
                    ("inquiry", "Anfrage"),
                    ("statement", "Stellungnahme"),
                    ("amendment", "Änderungsantrag"),
                ],
                default="motion",
                max_length=20,
                verbose_name="Typ (legacy)",
            ),
        ),
        migrations.AddField(
            model_name="motiontype",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="motion_types",
                to="tenants.organization",
                verbose_name="Organisation",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motions",
                to="work.motiontype",
                verbose_name="Dokumenttyp",
            ),
        ),
        migrations.AddField(
            model_name="motiontemplate",
            name="motion_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Vorlage nur für diesen Typ verfügbar (leer = alle Typen)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="work.motiontype",
                verbose_name="Dokumenttyp",
            ),
        ),
        migrations.AddField(
            model_name="organizationletterhead",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="letterheads",
                to="tenants.organization",
                verbose_name="Organisation",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="letterhead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motions",
                to="work.organizationletterhead",
                verbose_name="Briefkopf",
            ),
        ),
        migrations.AddField(
            model_name="motiontemplate",
            name="letterhead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="work.organizationletterhead",
                verbose_name="Briefkopf",
            ),
        ),
        migrations.AddIndex(
            model_name="motion",
            index=models.Index(
                fields=["organization", "document_type"],
                name="work_motion_organiz_be2ff4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="motiontype",
            unique_together={("organization", "slug")},
        ),
    ]
