# Generated by Django 6.0.1 on 2026-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0006_add_motion_types_and_letterheads"),
    ]

    operations = [
        migrations.AddField(
            model_name="motion",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt der Löschung (30 Tage Papierkorb)",
                null=True,
                verbose_name="Gelöscht am",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("review", "In Prüfung"),
                    ("approved", "Freigegeben"),
                    ("submitted", "Eingereicht"),
                    ("completed", "Erledigt"),
                    ("rejected", "Abgelehnt"),
                    ("archived", "Archiviert"),
                    ("deleted", "Gelöscht"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
