# Generated by Django 6.0.1 on 2026-01-23 13:11

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        ("tenants", "0004_membership_oparl_committees"),
        ("work", "0007_motion_deleted_at_alter_motion_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendaitemposition",
            name="estimated_speech_duration",
        ),
        migrations.RemoveField(
            model_name="agendaitemposition",
            name="speech_notes",
        ),
        migrations.AddField(
            model_name="agendaitemposition",
            name="discussion_note",
            field=models.TextField(
                blank=True,
                help_text="Notiz für die Fraktionsdiskussion (für alle sichtbar)",
                verbose_name="Diskussionsnotiz",
            ),
        ),
        migrations.AddField(
            model_name="agendaitemposition",
            name="is_final",
            field=models.BooleanField(
                default=False,
                help_text="Position als endgültig markieren",
                verbose_name="Endgültig",
            ),
        ),
        migrations.AlterField(
            model_name="agendaitemposition",
            name="notes_encrypted",
            field=apps.common.encryption.EncryptedTextField(
                help_text="Persönliche Notizen (nur für Sie sichtbar)",
                verbose_name="Private Notiz",
            ),
        ),
        migrations.AlterField(
            model_name="agendaitemposition",
            name="position",
            field=models.CharField(
                choices=[
                    ("open", "Noch offen"),
                    ("for", "Zustimmung"),
                    ("against", "Ablehnung"),
                    ("abstain", "Enthaltung"),
                    ("defer", "Vertagen"),
                    ("refer", "Überweisen"),
                    ("amended", "Mit Änderungen"),
                    ("info", "Zur Kenntnis"),
                ],
                default="open",
                max_length=20,
                verbose_name="Position",
            ),
        ),
        migrations.CreateModel(
            name="AgendaDocumentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_documents",
                        to="tenants.membership",
                        verbose_name="Hinzugefügt von",
                    ),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_document_links",
                        to="insight_core.oparlagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumentenlink",
                "verbose_name_plural": "Dokumentenlinks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgendaSpeechNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Titel"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Text für den Teleprompter", verbose_name="Redetext"
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Geschätzte Dauer (Sekunden)"
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, verbose_name="Mit Organisation teilen"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_speech_notes",
                        to="insight_core.oparlagendaitem",
                        verbose_name="Tagesordnungspunkt",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speech_notes",
                        to="tenants.membership",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_speech_notes",
                        to="insight_core.oparlmeeting",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speech_notes",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Redebeitrag",
                "verbose_name_plural": "Redebeiträge",
                "ordering": ["-created_at"],
                "unique_together": {("author", "agenda_item")},
            },
        ),
    ]
