# Generated by Django 6.0.1 on 2026-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0008_remove_agendaitemposition_estimated_speech_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Beschreibung"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titel"),
        ),
    ]
