# Generated by Django 6.0.1 on 2026-01-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0009_alter_task_description_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionagendaitem",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Öffentlich"), ("internal", "Nicht-öffentlich")],
                default="public",
                max_length=20,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.AlterField(
            model_name="factionagendaitem",
            name="number",
            field=models.CharField(blank=True, max_length=20, verbose_name="TOP-Nr."),
        ),
    ]
