# Generated by Django 6.0.1 on 2026-01-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0010_add_agenda_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionagendaitem",
            name="approves_meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Die vorherige Sitzung deren Protokoll hier genehmigt wird",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_agenda_items",
                to="work.factionmeeting",
                verbose_name="Genehmigt Sitzung",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="is_approval_item",
            field=models.BooleanField(
                default=False,
                help_text="Automatisch erstellter TOP für Protokoll-/TO-Genehmigung",
                verbose_name="Genehmigungs-TOP",
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="meeting_number",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Fortlaufende Nummer der Sitzung",
                verbose_name="Sitzungsnummer",
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="previous_meeting",
            field=models.OneToOneField(
                blank=True,
                help_text="Die vorherige Fraktionssitzung (für Protokollgenehmigung)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_meeting",
                to="work.factionmeeting",
                verbose_name="Vorherige Sitzung",
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="protocol_approved_in",
            field=models.ForeignKey(
                blank=True,
                help_text="Die Sitzung, in der dieses Protokoll genehmigt wurde",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_previous_protocols",
                to="work.factionmeeting",
                verbose_name="Genehmigt in Sitzung",
            ),
        ),
    ]
