# Generated by Django 6.0.1 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0011_faction_approval_workflow"),
    ]

    operations = [
        # Add new status fields
        migrations.AddField(
            model_name="supportticket",
            name="escalated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Eskaliert am"
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="on_hold_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zurückgestellt am"
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="last_customer_reply_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letzte Kundenantwort"
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="on_hold_reason",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Grund für Zurückstellung"
            ),
        ),
        # Update status choices (AlterField to include new choices)
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("in_progress", "In Bearbeitung"),
                    ("waiting", "Wartet auf Antwort"),
                    ("escalated", "Eskaliert"),
                    ("on_hold", "Zurückgestellt"),
                    ("resolved", "Gelöst"),
                    ("closed", "Geschlossen"),
                ],
                default="open",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
