# Generated by Django 6.0.1 on 2026-01-24 15:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_add_coalition_and_email_fields"),
        ("work", "0012_add_support_ticket_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="motion",
            name="default_edit_mode",
            field=models.CharField(
                choices=[
                    ("edit", "Bearbeiten"),
                    ("suggest", "Vorschlagen"),
                    ("comment", "Nur Kommentieren"),
                    ("view", "Nur Ansehen"),
                ],
                default="edit",
                help_text="Standard-Modus für neue Mitarbeiter",
                max_length=20,
                verbose_name="Standard-Bearbeitungsmodus",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="target_meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Sitzung, in der dieser Antrag behandelt werden soll",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_motions",
                to="work.factionmeeting",
                verbose_name="Ziel-Sitzung",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("review", "In Prüfung"),
                    ("approved", "Freigegeben"),
                    ("submitted", "Eingereicht"),
                    ("completed", "Erledigt"),
                    ("rejected", "Abgelehnt"),
                    ("archived", "Archiviert"),
                    ("deleted", "Gelöscht"),
                    ("internal_review", "Interne Absprache"),
                    ("external_review", "Externe Absprache"),
                    ("at_admin", "Bei Verwaltung"),
                    ("on_agenda", "Auf Tagesordnung"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("meeting_reminder", "Sitzungserinnerung"),
                    ("meeting_updated", "Sitzung aktualisiert"),
                    ("meeting_cancelled", "Sitzung abgesagt"),
                    ("task_assigned", "Aufgabe zugewiesen"),
                    ("task_due_soon", "Aufgabe fällig"),
                    ("task_completed", "Aufgabe erledigt"),
                    ("task_comment", "Kommentar zur Aufgabe"),
                    ("motion_shared", "Antrag geteilt"),
                    ("motion_comment", "Kommentar zum Antrag"),
                    ("motion_status", "Antragsstatus geändert"),
                    ("faction_reminder", "Fraktionssitzung"),
                    ("faction_updated", "Fraktionssitzung aktualisiert"),
                    ("member_joined", "Neues Mitglied"),
                    ("role_changed", "Rolle geändert"),
                    ("support_created", "Support-Ticket erstellt"),
                    ("support_reply", "Neue Antwort auf Ticket"),
                    ("support_status", "Ticketstatus geändert"),
                    ("support_resolved", "Ticket gelöst"),
                    ("support_escalated", "Ticket eskaliert"),
                    ("system", "Systemnachricht"),
                    ("announcement", "Ankündigung"),
                ],
                default="system",
                max_length=30,
                verbose_name="Typ",
            ),
        ),
        migrations.CreateModel(
            name="MotionApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("chair", "Vorsitzende:r"),
                            ("vice_chair", "Stellv. Vorsitzende:r"),
                            ("council", "Ratsmitglied"),
                            ("party_lead", "Fraktionsführung"),
                        ],
                        max_length=20,
                        verbose_name="Genehmigungstyp",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(default=None, null=True, verbose_name="Genehmigt"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Kommentar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Entschieden am"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_approvals",
                        to="tenants.membership",
                        verbose_name="Genehmiger",
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="work.motion",
                        verbose_name="Antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genehmigung",
                "verbose_name_plural": "Genehmigungen",
                "ordering": ["-created_at"],
                "unique_together": {("motion", "approver", "approval_type")},
            },
        ),
    ]
