# Generated by Django 6.0.1 on 2026-01-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_add_coalition_and_email_fields"),
        ("work", "0014_add_factionagendaitem_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factionattendance",
            options={
                "ordering": ["is_guest", "membership__user__last_name", "guest_name"],
                "verbose_name": "Anwesenheit",
                "verbose_name_plural": "Anwesenheiten",
            },
        ),
        # Note: AlterUniqueTogether removed - constraint doesn't exist in DB
        migrations.AddField(
            model_name="factionattendance",
            name="guest_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Name des Gastes"
            ),
        ),
        migrations.AddField(
            model_name="factionattendance",
            name="is_guest",
            field=models.BooleanField(default=False, verbose_name="Ist Gast"),
        ),
        migrations.AlterField(
            model_name="factionattendance",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_attendances",
                to="tenants.membership",
                verbose_name="Mitglied",
            ),
        ),
    ]
