# Generated by Django 6.0.1 on 2026-01-27 14:00

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0008_add_geo_fields_and_tile_cache"),
        ("tenants", "0005_add_coalition_and_email_fields"),
        ("work", "0015_add_guest_support_to_attendance"),
    ]

    operations = [
        # Note: AlterUniqueTogether removed - constraint doesn't exist in DB
        migrations.AlterField(
            model_name="agendaitemnote",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Nur ich"),
                    ("organization", "Meine Organisation"),
                ],
                default="organization",
                max_length=20,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.CreateModel(
            name="PaperComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Nur ich"),
                            ("organization", "Meine Organisation"),
                            ("consulting", "Alle beratenden Gremien"),
                        ],
                        default="organization",
                        max_length=20,
                        verbose_name="Sichtbarkeit",
                    ),
                ),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Inhalt"),
                ),
                (
                    "is_recommendation",
                    models.BooleanField(
                        default=False,
                        help_text="Markiert diesen Kommentar als offizielle Empfehlung der Organisation",
                        verbose_name="Als Empfehlung markiert",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_comments",
                        to="tenants.membership",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_comments",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_comments",
                        to="insight_core.oparlpaper",
                        verbose_name="Vorgang",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorgang-Kommentar",
                "verbose_name_plural": "Vorgang-Kommentare",
                "ordering": ["-is_recommendation", "-created_at"],
            },
        ),
    ]
