# Generated by Django 6.0.1 on 2026-02-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_add_coalition_and_email_fields"),
        ("work", "0016_add_paper_comment_model"),
    ]

    operations = [
        # Add protocol_status to FactionMeeting
        migrations.AddField(
            model_name="factionmeeting",
            name="protocol_status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("pending", "Zur Genehmigung"),
                    ("approved", "Genehmigt"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Protokollstatus",
            ),
        ),
        # Add proposal system fields to FactionAgendaItem
        migrations.AddField(
            model_name="factionagendaitem",
            name="proposal_status",
            field=models.CharField(
                choices=[
                    ("active", "Aktiv"),
                    ("proposed", "Vorgeschlagen"),
                    ("rejected", "Abgelehnt"),
                ],
                default="active",
                help_text="Für TOPs die von Sachkundigen Bürger*innen vorgeschlagen wurden",
                max_length=20,
                verbose_name="Vorschlagsstatus",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="proposed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_agenda_items",
                to="tenants.membership",
                verbose_name="Vorgeschlagen von",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="proposed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Vorgeschlagen am",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_agenda_items",
                to="tenants.membership",
                verbose_name="Geprüft von",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Geprüft am",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                verbose_name="Ablehnungsgrund",
            ),
        ),
        # Add index for proposal queries
        migrations.AddIndex(
            model_name="factionagendaitem",
            index=models.Index(
                fields=["meeting", "proposal_status"],
                name="work_factio_meeting_8e8a4c_idx",
            ),
        ),
    ]
