# Generated by Django 6.0.1 on 2026-02-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0016_add_paper_comment_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="factionattendance",
            unique_together=set(),
        ),
    ]
