# Generated by Django 6.0.1 on 2026-02-04 22:03
# Empty migration - dependency for insight_core ContactRequest

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0018_add_motion_visibility"),
    ]

    operations = [
        # No operations - this migration exists as a dependency placeholder
        # for insight_core.0010_add_contact_request which references work.SupportTicket
    ]
