# Generated by Django 6.0.1 on 2026-02-04 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_add_is_sworn_in_to_membership"),
        ("work", "0019_add_contact_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aufgaben-Freigabe",
                "verbose_name_plural": "Aufgaben-Freigaben",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Privat"),
                    ("shared", "Geteilt"),
                    ("organization", "Organisation"),
                ],
                default="private",
                max_length=20,
                verbose_name="Sichtbarkeit",
            ),
        ),
        migrations.AddField(
            model_name="taskshare",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_tasks",
                to="tenants.membership",
                verbose_name="Mitglied",
            ),
        ),
        migrations.AddField(
            model_name="taskshare",
            name="shared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_shares_given",
                to="tenants.membership",
                verbose_name="Geteilt von",
            ),
        ),
        migrations.AddField(
            model_name="taskshare",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="work.task",
                verbose_name="Aufgabe",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskshare",
            unique_together={("task", "membership")},
        ),
    ]
