# Generated by Django 6.0.1 on 2026-02-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0020_add_task_visibility"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="factionagendaitem",
            new_name="work_factio_meeting_30b6ce_idx",
            old_name="work_factio_meeting_8e8a4c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="factionattendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="reference_links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Links zu internen oder externen Dokumenten [{label, url}]",
                verbose_name="Referenz-Links",
            ),
        ),
    ]
