# Generated by Django 6.0.1 on 2026-02-14 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_add_is_sworn_in_to_membership"),
        ("work", "0021_agenda_item_reference_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("meeting_reminder", "Sitzungserinnerung"),
                    ("meeting_updated", "Sitzung aktualisiert"),
                    ("meeting_cancelled", "Sitzung abgesagt"),
                    ("task_assigned", "Aufgabe zugewiesen"),
                    ("task_due_soon", "Aufgabe fällig"),
                    ("task_completed", "Aufgabe erledigt"),
                    ("task_comment", "Kommentar zur Aufgabe"),
                    ("motion_shared", "Antrag geteilt"),
                    ("motion_comment", "Kommentar zum Antrag"),
                    ("motion_status", "Antragsstatus geändert"),
                    ("faction_reminder", "Fraktionssitzung"),
                    ("faction_updated", "Fraktionssitzung aktualisiert"),
                    ("member_joined", "Neues Mitglied"),
                    ("role_changed", "Rolle geändert"),
                    ("support_created", "Support-Ticket erstellt"),
                    ("support_reply", "Neue Antwort auf Ticket"),
                    ("support_status", "Ticketstatus geändert"),
                    ("support_resolved", "Ticket gelöst"),
                    ("support_escalated", "Ticket eskaliert"),
                    ("change_request_new", "Neuer Änderungsantrag"),
                    ("change_request_decided", "Änderungsantrag entschieden"),
                    ("absence_deputy", "Stellvertretung zugewiesen"),
                    ("system", "Systemnachricht"),
                    ("announcement", "Ankündigung"),
                ],
                default="system",
                max_length=30,
                verbose_name="Typ",
            ),
        ),
        migrations.CreateModel(
            name="MemberAbsence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Von")),
                ("end_date", models.DateField(verbose_name="Bis")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=500, verbose_name="Grund"),
                ),
                (
                    "auto_decline_meetings",
                    models.BooleanField(
                        default=True, verbose_name="Sitzungen automatisch absagen"
                    ),
                ),
                (
                    "notify_deputy",
                    models.BooleanField(
                        default=True, verbose_name="Stellvertreter benachrichtigen"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deputy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deputy_for",
                        to="tenants.membership",
                        verbose_name="Stellvertreter",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="tenants.membership",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_absences",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abwesenheit",
                "verbose_name_plural": "Abwesenheiten",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "membership", "-start_date"],
                        name="work_member_organiz_e3a2e9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemberChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("role_change", "Rollenänderung"),
                            ("committee_change", "Gremienänderung"),
                            ("permission_request", "Berechtigungsanfrage"),
                        ],
                        max_length=30,
                        verbose_name="Antragstyp",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(default=dict, verbose_name="Antragsdaten"),
                ),
                ("reason", models.TextField(verbose_name="Begründung")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entschieden am"
                    ),
                ),
                (
                    "decision_comment",
                    models.TextField(blank=True, verbose_name="Entscheidungskommentar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_change_requests",
                        to="tenants.membership",
                        verbose_name="Entschieden von",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="tenants.membership",
                        verbose_name="Antragsteller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Änderungsantrag",
                "verbose_name_plural": "Änderungsanträge",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-created_at"],
                        name="work_member_organiz_664011_idx",
                    ),
                    models.Index(
                        fields=["requester", "-created_at"],
                        name="work_member_request_b85517_idx",
                    ),
                ],
            },
        ),
    ]
