# Generated by Django 6.0.1 on 2026-02-14 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_add_is_sworn_in_to_membership"),
        ("work", "0022_add_absence_and_change_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("processing", "Wird erstellt"),
                            ("completed", "Fertig"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("json", "JSON"), ("pdf", "PDF")],
                        default="json",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Dateipfad"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dateigröße"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Fehlermeldung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gestartet"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Abgeschlossen"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to="tenants.membership",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datenexport",
                "verbose_name_plural": "Datenexporte",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["membership", "-created_at"],
                        name="work_dataex_members_99e19f_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="work_dataex_organiz_1d3dd5_idx",
                    ),
                ],
            },
        ),
    ]
