# Generated by Django 6.0 on 2026-02-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0007_add_ai_provider_settings"),
        ("work", "0024_motioncomment_mark_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationAITokenUsage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("day", "Tag"), ("week", "Woche"), ("month", "Monat")],
                        max_length=10,
                        verbose_name="Periode",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Periodenbeginn")),
                ("tokens_used", models.PositiveIntegerField(default=0, verbose_name="Verbrauchte Tokens")),
                ("requests_count", models.PositiveIntegerField(default=0, verbose_name="Anfragen")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_usage_entries",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "KI Tokenverbrauch",
                "verbose_name_plural": "KI Tokenverbraeuche",
                "ordering": ["-period_start", "period_type"],
                "unique_together": {("organization", "period_type", "period_start")},
            },
        ),
        migrations.AddIndex(
            model_name="organizationaitokenusage",
            index=models.Index(
                fields=["organization", "period_type", "period_start"],
                name="work_organi_organiz_4f31ce_idx",
            ),
        ),
    ]
