# Generated by Django 6.0 on 2026-02-27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0007_add_ai_provider_settings"),
        ("work", "0025_organization_ai_token_usage"),
    ]

    operations = [
        # TaskLabel
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Rot"),
                            ("orange", "Orange"),
                            ("amber", "Gelb"),
                            ("green", "Grün"),
                            ("teal", "Türkis"),
                            ("blue", "Blau"),
                            ("indigo", "Indigo"),
                            ("purple", "Lila"),
                            ("pink", "Rosa"),
                            ("gray", "Grau"),
                        ],
                        default="blue",
                        max_length=20,
                        verbose_name="Farbe",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_labels",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufgaben-Label",
                "verbose_name_plural": "Aufgaben-Labels",
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        # Task.labels M2M
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                to="work.tasklabel",
                verbose_name="Labels",
            ),
        ),
        # TaskChecklistItem
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                ("is_completed", models.BooleanField(default=False, verbose_name="Erledigt")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Position")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="work.task",
                        verbose_name="Aufgabe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklisten-Punkt",
                "verbose_name_plural": "Checklisten-Punkte",
                "ordering": ["position", "created_at"],
            },
        ),
        # TaskAttachment
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="tasks/attachments/%Y/%m/", verbose_name="Datei")),
                ("filename", models.CharField(max_length=255, verbose_name="Dateiname")),
                ("mime_type", models.CharField(max_length=100, verbose_name="MIME-Typ")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="Dateigröße (Bytes)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="work.task",
                        verbose_name="Aufgabe",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_attachments",
                        to="tenants.membership",
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufgaben-Anhang",
                "verbose_name_plural": "Aufgaben-Anhänge",
                "ordering": ["-created_at"],
            },
        ),
        # TaskActivity
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Erstellt"),
                            ("status_changed", "Status geändert"),
                            ("assigned", "Zugewiesen"),
                            ("completed", "Erledigt"),
                            ("reopened", "Wieder geöffnet"),
                            ("comment", "Kommentar"),
                            ("attachment_added", "Anhang hinzugefügt"),
                            ("attachment_removed", "Anhang entfernt"),
                            ("checklist_item_added", "Checklistenpunkt hinzugefügt"),
                            ("checklist_item_completed", "Checklistenpunkt erledigt"),
                            ("checklist_item_unchecked", "Checklistenpunkt geöffnet"),
                            ("label_added", "Label hinzugefügt"),
                            ("label_removed", "Label entfernt"),
                            ("priority_changed", "Priorität geändert"),
                            ("due_date_changed", "Fälligkeitsdatum geändert"),
                            ("visibility_changed", "Sichtbarkeit geändert"),
                        ],
                        max_length=30,
                        verbose_name="Typ",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Inhalt")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Details")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="work.task",
                        verbose_name="Aufgabe",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_activities",
                        to="tenants.membership",
                        verbose_name="Akteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufgaben-Aktivität",
                "verbose_name_plural": "Aufgaben-Aktivitäten",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(
                fields=["task", "created_at"],
                name="work_taskac_task_id_created_idx",
            ),
        ),
    ]
