# Generated by Django 5.2.11 on 2026-03-04 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_alter_organization_ai_api_key_encrypted_and_more"),
        ("work", "0027_migrate_comments_to_activities"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactionAgendaItemAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="faction/attachments/%Y/%m/", verbose_name="Datei"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Dateiname"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-Typ"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dateigröße (Bytes)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "TOP-Anhang",
                "verbose_name_plural": "TOP-Anhänge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="organizationaitokenusage",
            new_name="work_organi_organiz_f5d27c_idx",
            old_name="work_organi_organiz_4f31ce_idx",
        ),
        migrations.RenameIndex(
            model_name="taskactivity",
            new_name="work_taskac_task_id_216921_idx",
            old_name="work_taskac_task_id_created_idx",
        ),
        migrations.AddField(
            model_name="factionagendaitem",
            name="related_motions",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_agenda_items",
                to="work.motion",
                verbose_name="Verknüpfte Anträge",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_faction_agenda_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="work.factionagendaitem",
                verbose_name="Fraktions-TOP",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitemattachment",
            name="agenda_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="work.factionagendaitem",
                verbose_name="TOP",
            ),
        ),
        migrations.AddField(
            model_name="factionagendaitemattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faction_item_attachments",
                to="tenants.membership",
                verbose_name="Hochgeladen von",
            ),
        ),
    ]
