# Generated by Django 6.0.3 on 2026-03-27 15:07

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_core', '0020_org_wide_meeting_prep_phase1'),
        ('tenants', '0010_administration_contact'),
        ('work', '0029_factionagendaitem_related_papers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaitemnote',
            options={'ordering': ['-is_pinned', '-is_decision', '-created_at'], 'verbose_name': 'TOP-Diskussionsnotiz', 'verbose_name_plural': 'TOP-Diskussionsnotizen'},
        ),
        migrations.AlterUniqueTogether(
            name='agendaitemposition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='meetingpreparation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendaitemposition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_positions', to='tenants.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='agendaitemposition',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_positions', to='tenants.membership', verbose_name='Gesetzt von'),
        ),
        migrations.AddField(
            model_name='agendaspeechnote',
            name='content_encrypted',
            field=apps.common.encryption.EncryptedTextField(verbose_name='Redebeitrag'),
        ),
        migrations.AddField(
            model_name='meetingpreparation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_meetings', to='tenants.membership', verbose_name='Vorbereitet von'),
        ),
        migrations.AlterField(
            model_name='agendaitemnote',
            name='visibility',
            field=models.CharField(choices=[('organization', 'Meine Organisation')], default='organization', max_length=20, verbose_name='Sichtbarkeit'),
        ),
        migrations.AlterField(
            model_name='agendaitemposition',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='work.meetingpreparation', verbose_name='Vorbereitung'),
        ),
        migrations.AlterField(
            model_name='agendaspeechnote',
            name='content',
            field=models.TextField(blank=True, verbose_name='Redetext (alt)'),
        ),
        migrations.AlterField(
            model_name='agendaspeechnote',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Mit Fraktion teilen'),
        ),
        migrations.AlterField(
            model_name='agendaspeechnote',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_speech_notes', to='insight_core.oparlmeeting', verbose_name='Sitzung'),
        ),
        migrations.AlterField(
            model_name='meetingpreparation',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_preparations', to='tenants.membership', verbose_name='Mitglied'),
        ),
        migrations.AlterField(
            model_name='meetingpreparation',
            name='notes_encrypted',
            field=apps.common.encryption.EncryptedTextField(help_text='Org-weite Notizen zur Sitzung', verbose_name='Allgemeine Notizen'),
        ),
        migrations.CreateModel(
            name='AgendaPrivateNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_encrypted', apps.common.encryption.EncryptedTextField(verbose_name='Private Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_private_notes', to='insight_core.oparlagendaitem', verbose_name='Tagesordnungspunkt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_agenda_notes', to='tenants.membership', verbose_name='Autor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_agenda_notes', to='tenants.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Private TOP-Notiz',
                'verbose_name_plural': 'Private TOP-Notizen',
                'unique_together': {('author', 'agenda_item')},
            },
        ),
        migrations.CreateModel(
            name='AgendaSupplementaryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('link', 'Externer Link'), ('file', 'Datei-Upload'), ('oparl', 'OParl-Dokument')], default='link', max_length=10, verbose_name='Typ')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, upload_to='meetings/documents/%Y/%m/', verbose_name='Datei')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Dateiname')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-Typ')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_documents', to='tenants.membership', verbose_name='Hinzugefügt von')),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_supplementary_documents', to='insight_core.oparlagendaitem', verbose_name='Tagesordnungspunkt')),
                ('oparl_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_supplementary_refs', to='insight_core.oparlfile', verbose_name='OParl-Datei')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_documents', to='tenants.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Ergänzendes Dokument',
                'verbose_name_plural': 'Ergänzende Dokumente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AgendaDocumentLink',
        ),
        migrations.RemoveField(
            model_name='agendaitemposition',
            name='discussion_note',
        ),
        migrations.RemoveField(
            model_name='agendaitemposition',
            name='notes_encrypted',
        ),
    ]
