# Generated by Django 6.0.6 on 2026-07-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0030_org_wide_meeting_prep_phase1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaitemnote",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("organization", "Meine Organisation"),
                    ("consulting", "Beratende Gremien"),
                ],
                default="organization",
                max_length=20,
                verbose_name="Sichtbarkeit",
            ),
        ),
    ]
