# Generated by Django 6.0.6 on 2026-07-09 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_antragsdatenbank_tracking"),
        ("work", "0031_agendaitemnote_consulting_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="motion",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="contributing_motions",
                to="tenants.membership",
                verbose_name="Mitarbeit",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Frist"),
        ),
        migrations.AddField(
            model_name="motion",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_motions",
                to="tenants.membership",
                verbose_name="Federführung",
            ),
        ),
        migrations.AddField(
            model_name="motion",
            name="topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="motions",
                to="tenants.topic",
                verbose_name="Themen",
            ),
        ),
        migrations.AddField(
            model_name="motiontype",
            name="default_checklist",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ein Punkt je Zeile; wird bei neuen Dokumenten dieses Typs angelegt",
                verbose_name="Standard-Checkliste",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("meeting_reminder", "Sitzungserinnerung"),
                    ("meeting_updated", "Sitzung aktualisiert"),
                    ("meeting_cancelled", "Sitzung abgesagt"),
                    ("task_assigned", "Aufgabe zugewiesen"),
                    ("task_due_soon", "Aufgabe fällig"),
                    ("task_completed", "Aufgabe erledigt"),
                    ("task_comment", "Kommentar zur Aufgabe"),
                    ("motion_shared", "Antrag geteilt"),
                    ("motion_comment", "Kommentar zum Antrag"),
                    ("motion_status", "Antragsstatus geändert"),
                    ("motion_assigned", "Dokument zugewiesen"),
                    ("motion_due_soon", "Dokument fällig"),
                    ("motion_approval_req", "Freigabe angefragt"),
                    ("motion_approval_dec", "Freigabe entschieden"),
                    ("faction_reminder", "Fraktionssitzung"),
                    ("faction_updated", "Fraktionssitzung aktualisiert"),
                    ("member_joined", "Neues Mitglied"),
                    ("role_changed", "Rolle geändert"),
                    ("support_created", "Support-Ticket erstellt"),
                    ("support_reply", "Neue Antwort auf Ticket"),
                    ("support_status", "Ticketstatus geändert"),
                    ("support_resolved", "Ticket gelöst"),
                    ("support_escalated", "Ticket eskaliert"),
                    ("change_request_new", "Neuer Änderungsantrag"),
                    ("change_request_decided", "Änderungsantrag entschieden"),
                    ("absence_deputy", "Stellvertretung zugewiesen"),
                    ("system", "Systemnachricht"),
                    ("announcement", "Ankündigung"),
                ],
                default="system",
                max_length=30,
                verbose_name="Typ",
            ),
        ),
        migrations.CreateModel(
            name="MotionChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erledigt am"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_motion_checklist_items",
                        to="tenants.membership",
                        verbose_name="Erledigt von",
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="work.motion",
                        verbose_name="Dokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument-Checklisten-Punkt",
                "verbose_name_plural": "Dokument-Checklisten-Punkte",
                "ordering": ["position", "created_at"],
            },
        ),
    ]
