# Generated by Django 6.0.6 on 2026-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0033_migrate_tags_to_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationletterhead",
            name="accent_color_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Akzentlinie in der Primärfarbe der Organisation",
                verbose_name="Akzentfarbe verwenden",
            ),
        ),
        migrations.AddField(
            model_name="organizationletterhead",
            name="address_block",
            field=models.TextField(
                blank=True,
                help_text="Absenderblock rechts oben (mehrzeilig)",
                verbose_name="Absenderblock",
            ),
        ),
        migrations.AddField(
            model_name="organizationletterhead",
            name="footer_text",
            field=models.TextField(
                blank=True,
                help_text="Fußzeile auf jeder Seite, z. B. Kontakt/Bank/Web; Angaben je Zeile mit · trennbar",
                verbose_name="Fußzeile",
            ),
        ),
        migrations.AddField(
            model_name="organizationletterhead",
            name="header_logo_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Nutzt das Logo der Organisation (bzw. der Parteigruppe)",
                verbose_name="Logo anzeigen",
            ),
        ),
        migrations.AddField(
            model_name="organizationletterhead",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF-Datei"),
                    ("generated", "Generiert (Corporate Design)"),
                ],
                default="pdf",
                help_text="PDF-Hintergrund oder aus dem Corporate Design generierter Briefkopf",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AddField(
            model_name="organizationletterhead",
            name="sender_line",
            field=models.CharField(
                blank=True,
                help_text="Einzeilige Absenderzeile über dem Adressfeld, z. B. „Fraktion XYZ · Rathausplatz 1 · 12345 Stadt“",
                max_length=300,
                verbose_name="Absenderzeile",
            ),
        ),
        migrations.AlterField(
            model_name="organizationletterhead",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="motions/letterheads/%Y/%m/",
                verbose_name="PDF-Datei",
            ),
        ),
    ]
