# Generated by Django 6.0.6 on 2026-07-10 10:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0018_backfill_party_group"),
        ("work", "0034_briefkopf_corporate_design"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red", "Rot"),
                            ("orange", "Orange"),
                            ("amber", "Gelb"),
                            ("green", "Grün"),
                            ("teal", "Türkis"),
                            ("blue", "Blau"),
                            ("indigo", "Indigo"),
                            ("purple", "Lila"),
                            ("pink", "Rosa"),
                            ("gray", "Grau"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Farbe",
                    ),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Sortierung")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_document_folders",
                        to="tenants.membership",
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_folders",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="work.documentfolder",
                        verbose_name="Übergeordneter Ordner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumentordner",
                "verbose_name_plural": "Dokumentordner",
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="motion",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motions",
                to="work.documentfolder",
                verbose_name="Ordner",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentfolder",
            constraint=models.UniqueConstraint(
                fields=("organization", "parent", "name"),
                name="uniq_document_folder_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentfolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("organization", "name"),
                name="uniq_document_folder_name_root",
            ),
        ),
    ]
