# Generated by Django 6.0.6 on 2026-07-11 11:14

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0020_org_wide_meeting_prep_phase1"),
        ("work", "0035_dokumentordner_ablage"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaitemnote",
            name="migrated_to_paper_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="migrated_from_notes",
                to="work.papercomment",
                verbose_name="Migriert nach Vorgang-Kommentar",
            ),
        ),
        migrations.AddField(
            model_name="agendaitemposition",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— noch kein Ergebnis —"),
                    ("as_position", "Wie unsere Position"),
                    ("accepted", "Angenommen"),
                    ("rejected", "Abgelehnt"),
                    ("referred", "Verwiesen"),
                    ("deferred", "Vertagt"),
                    ("noted", "Kenntnisnahme"),
                ],
                default="",
                max_length=20,
                verbose_name="Ergebnis der Beratung",
            ),
        ),
        migrations.AddField(
            model_name="agendaitemposition",
            name="reasoning_encrypted",
            field=apps.common.encryption.EncryptedTextField(
                help_text="Kurze Begründung der Position (für die Organisation sichtbar)",
                verbose_name="Begründung",
            ),
        ),
        migrations.AddField(
            model_name="agendaspeechnote",
            name="linked_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_speech_notes",
                to="work.motion",
                verbose_name="Verknüpftes Dokument",
            ),
        ),
        migrations.AddField(
            model_name="agendasupplementarydocument",
            name="paper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_supplementary_documents",
                to="insight_core.oparlpaper",
                verbose_name="Vorlage",
            ),
        ),
        migrations.AddField(
            model_name="agendasupplementarydocument",
            name="share_across_committees",
            field=models.BooleanField(
                default=False,
                help_text="Dokument in den Vorbereitungen aller Gremien anzeigen, die diese Vorlage beraten (nur innerhalb der eigenen Organisation)",
                verbose_name="In allen beratenden Gremien sichtbar",
            ),
        ),
        migrations.AlterField(
            model_name="agendaitemposition",
            name="position",
            field=models.CharField(
                choices=[
                    ("open", "Noch offen"),
                    ("for", "Zustimmung"),
                    ("against", "Ablehnung"),
                    ("abstain", "Enthaltung"),
                    ("defer", "Vertagen"),
                    ("refer", "Verweisen"),
                    ("amended", "Mit Änderungsantrag"),
                    ("info", "Kenntnisnahme"),
                ],
                default="open",
                max_length=20,
                verbose_name="Position",
            ),
        ),
    ]
