# Generated by Django 6.0.6 on 2026-07-11 17:51

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.encryption


class Migration(migrations.Migration):
    dependencies = [
        ("insight_core", "0020_org_wide_meeting_prep_phase1"),
        ("tenants", "0018_backfill_party_group"),
        ("work", "0038_backfill_position_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page", models.PositiveIntegerField(default=1, verbose_name="Seite")),
                (
                    "content_encrypted",
                    apps.common.encryption.EncryptedTextField(verbose_name="Anmerkung"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_annotations",
                        to="tenants.membership",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "oparl_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_annotations",
                        to="insight_core.oparlfile",
                        verbose_name="OParl-Datei",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_annotations",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "supplementary_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="work.agendasupplementarydocument",
                        verbose_name="Eigene Anlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datei-Anmerkung",
                "verbose_name_plural": "Datei-Anmerkungen",
                "ordering": ["page", "created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("oparl_file__isnull", False),
                                ("supplementary_document__isnull", True),
                            ),
                            models.Q(
                                ("oparl_file__isnull", True),
                                ("supplementary_document__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="fileannotation_exactly_one_anchor",
                    )
                ],
            },
        ),
    ]
