# Generated by Django 5.2.11 on 2026-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0040_ordner_gastfreigaben"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionmeeting",
            name="invitation_sequence",
            field=models.PositiveIntegerField(
                default=0,
                help_text="ICS-SEQUENCE: wird bei jeder Aktualisierung/Nachladung erhöht",
                verbose_name="Einladungs-Sequenz",
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="invitation_updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Aktualisierte Einladung versendet am",
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Erinnerung versendet am"
            ),
        ),
    ]
