# Generated by Django 5.2.11 on 2026-07-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_einladung_und_protokoll_opt_in"),
        ("work", "0043_sitzungserzeugung_ausfallregeln"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionmeeting",
            name="invitation_released_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Einladungsversand freigegeben am"
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="invitation_released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_faction_invitations",
                to="tenants.membership",
                verbose_name="Freigegeben von",
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="release_notice_final_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Freigabe-Hinweis (3 h) versandt am"
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="release_notice_first_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Freigabe-Hinweis (24 h) versandt am",
            ),
        ),
        migrations.AlterField(
            model_name="factionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Erstellt"),
                    ("update", "Geändert"),
                    ("delete", "Gelöscht"),
                    ("status", "Statuswechsel"),
                    ("invitation_sent", "Einladung versandt"),
                    ("invitation_updated", "Aktualisierte Einladung versandt"),
                    ("reminder_sent", "Erinnerung versandt"),
                    ("protocol_submitted", "Protokoll zur Genehmigung"),
                    ("protocol_approved", "Protokoll genehmigt"),
                    ("participation", "Teilnahme geändert"),
                    ("proposal", "TOP vorgeschlagen"),
                    ("proposal_accepted", "TOP-Vorschlag angenommen"),
                    ("proposal_rejected", "TOP-Vorschlag abgelehnt"),
                    ("decision", "Abstimmung erfasst"),
                    ("generated", "Automatisch erzeugt"),
                    ("auto_cancelled", "Automatisch entfallen"),
                    ("invitation_released", "Einladungsversand freigegeben"),
                    ("release_notice_sent", "Freigabe-Hinweis versandt"),
                ],
                max_length=50,
                verbose_name="Aktion",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("meeting_reminder", "Sitzungserinnerung"),
                    ("meeting_updated", "Sitzung aktualisiert"),
                    ("meeting_cancelled", "Sitzung abgesagt"),
                    ("task_assigned", "Aufgabe zugewiesen"),
                    ("task_due_soon", "Aufgabe fällig"),
                    ("task_completed", "Aufgabe erledigt"),
                    ("task_comment", "Kommentar zur Aufgabe"),
                    ("motion_shared", "Antrag geteilt"),
                    ("motion_comment", "Kommentar zum Antrag"),
                    ("motion_status", "Antragsstatus geändert"),
                    ("motion_assigned", "Dokument zugewiesen"),
                    ("motion_due_soon", "Dokument fällig"),
                    ("motion_approval_req", "Freigabe angefragt"),
                    ("motion_approval_dec", "Freigabe entschieden"),
                    ("faction_reminder", "Fraktionssitzung"),
                    ("faction_updated", "Fraktionssitzung aktualisiert"),
                    ("faction_inv_release", "Einladungsfreigabe erforderlich"),
                    ("member_joined", "Neues Mitglied"),
                    ("role_changed", "Rolle geändert"),
                    ("support_created", "Support-Ticket erstellt"),
                    ("support_reply", "Neue Antwort auf Ticket"),
                    ("support_status", "Ticketstatus geändert"),
                    ("support_resolved", "Ticket gelöst"),
                    ("support_escalated", "Ticket eskaliert"),
                    ("change_request_new", "Neuer Änderungsantrag"),
                    ("change_request_decided", "Änderungsantrag entschieden"),
                    ("absence_deputy", "Stellvertretung zugewiesen"),
                    ("system", "Systemnachricht"),
                    ("announcement", "Ankündigung"),
                ],
                default="system",
                max_length=30,
                verbose_name="Typ",
            ),
        ),
    ]
