# Generated by Django 5.2.11 on 2026-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0044_einladungslogik_je_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Erstellt"),
                    ("update", "Geändert"),
                    ("delete", "Gelöscht"),
                    ("status", "Statuswechsel"),
                    ("invitation_sent", "Einladung versandt"),
                    ("invitation_updated", "Aktualisierte Einladung versandt"),
                    ("reminder_sent", "Erinnerung versandt"),
                    ("protocol_submitted", "Protokoll zur Genehmigung"),
                    ("protocol_approved", "Protokoll genehmigt"),
                    ("participation", "Teilnahme geändert"),
                    ("proposal", "TOP vorgeschlagen"),
                    ("proposal_accepted", "TOP-Vorschlag angenommen"),
                    ("proposal_rejected", "TOP-Vorschlag abgelehnt"),
                    ("decision", "Abstimmung erfasst"),
                    ("generated", "Automatisch erzeugt"),
                    ("auto_cancelled", "Automatisch entfallen"),
                    ("invitation_released", "Einladungsversand freigegeben"),
                    ("release_notice_sent", "Freigabe-Hinweis versandt"),
                    ("addendum", "Nachtrag erfasst"),
                ],
                max_length=50,
                verbose_name="Aktion",
            ),
        ),
        migrations.AlterField(
            model_name="factionprotocolentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("speech", "Wortbeitrag"),
                    ("decision", "Beschluss"),
                    ("action", "Aufgabe"),
                    ("note", "Notiz"),
                    ("vote", "Abstimmung"),
                    ("addendum", "Nachtrag"),
                ],
                default="note",
                max_length=20,
                verbose_name="Art",
            ),
        ),
    ]
