# Generated by Django 5.2.11 on 2026-07-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_einladung_und_protokoll_opt_in"),
        ("work", "0045_standard_top1_protokollsperre_nachtrag"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionattendance",
            name="confirmed_final_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Final bestätigt am"
            ),
        ),
        migrations.AddField(
            model_name="factionattendance",
            name="confirmed_final_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finally_confirmed_attendances",
                to="tenants.membership",
                verbose_name="Final bestätigt von",
            ),
        ),
        migrations.AddField(
            model_name="factionattendance",
            name="participation_type",
            field=models.CharField(
                choices=[("onsite", "Vor Ort"), ("online", "Online")],
                default="onsite",
                max_length=10,
                verbose_name="Teilnahmeart",
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="attendance_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Teilnahmen bestätigt am"
            ),
        ),
        migrations.AddField(
            model_name="factionmeeting",
            name="attendance_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_confirmed_meetings",
                to="tenants.membership",
                verbose_name="Teilnahmen bestätigt von",
            ),
        ),
        migrations.AlterField(
            model_name="factionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Erstellt"),
                    ("update", "Geändert"),
                    ("delete", "Gelöscht"),
                    ("status", "Statuswechsel"),
                    ("invitation_sent", "Einladung versandt"),
                    ("invitation_updated", "Aktualisierte Einladung versandt"),
                    ("reminder_sent", "Erinnerung versandt"),
                    ("protocol_submitted", "Protokoll zur Genehmigung"),
                    ("protocol_approved", "Protokoll genehmigt"),
                    ("participation", "Teilnahme geändert"),
                    ("proposal", "TOP vorgeschlagen"),
                    ("proposal_accepted", "TOP-Vorschlag angenommen"),
                    ("proposal_rejected", "TOP-Vorschlag abgelehnt"),
                    ("decision", "Abstimmung erfasst"),
                    ("generated", "Automatisch erzeugt"),
                    ("auto_cancelled", "Automatisch entfallen"),
                    ("invitation_released", "Einladungsversand freigegeben"),
                    ("release_notice_sent", "Freigabe-Hinweis versandt"),
                    ("addendum", "Nachtrag erfasst"),
                    ("attendance_confirmed", "Teilnahmen bestätigt"),
                ],
                max_length=50,
                verbose_name="Aktion",
            ),
        ),
    ]
