# Generated by Django 5.2.11 on 2026-07-21 21:19

import apps.work.faction.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0020_eigene_absender_mail"),
        ("work", "0046_teilnahmeart_und_vorstandsbestaetigung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Erstellt"),
                    ("update", "Geändert"),
                    ("delete", "Gelöscht"),
                    ("status", "Statuswechsel"),
                    ("invitation_sent", "Einladung versandt"),
                    ("invitation_updated", "Aktualisierte Einladung versandt"),
                    ("reminder_sent", "Erinnerung versandt"),
                    ("protocol_submitted", "Protokoll zur Genehmigung"),
                    ("protocol_approved", "Protokoll genehmigt"),
                    ("participation", "Teilnahme geändert"),
                    ("proposal", "TOP vorgeschlagen"),
                    ("proposal_accepted", "TOP-Vorschlag angenommen"),
                    ("proposal_rejected", "TOP-Vorschlag abgelehnt"),
                    ("decision", "Abstimmung erfasst"),
                    ("generated", "Automatisch erzeugt"),
                    ("auto_cancelled", "Automatisch entfallen"),
                    ("invitation_released", "Einladungsversand freigegeben"),
                    ("release_notice_sent", "Freigabe-Hinweis versandt"),
                    ("addendum", "Nachtrag erfasst"),
                    ("attendance_confirmed", "Teilnahmen bestätigt"),
                    ("certificate_issued", "Teilnahmenachweis ausgestellt"),
                    ("attendance_exported", "Teilnahmen-Sammel-Export erstellt"),
                    ("api_settings_changed", "Öffentliche API konfiguriert"),
                ],
                max_length=50,
                verbose_name="Aktion",
            ),
        ),
        migrations.CreateModel(
            name="FactionAttendanceCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Zeitraum von")),
                ("period_end", models.DateField(verbose_name="Zeitraum bis")),
                (
                    "attendance_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Bestätigte Teilnahmen"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.work.faction.models.generate_opaque_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Prüfcode",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Prüfsumme"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ausgestellt am"
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_attendance_certificates",
                        to="tenants.membership",
                        verbose_name="Ausgestellt von",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_certificates",
                        to="tenants.membership",
                        verbose_name="Mitglied",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_certificates",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teilnahmenachweis",
                "verbose_name_plural": "Teilnahmenachweise",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "membership"],
                        name="work_factio_organiz_1d704f_idx",
                    )
                ],
            },
        ),
    ]
