# Generated by Django 5.2.11 on 2026-07-21 21:27

import apps.work.faction.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0047_teilnahmenachweis_und_sammelexport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("meeting_reminder", "Sitzungserinnerung"),
                    ("meeting_updated", "Sitzung aktualisiert"),
                    ("meeting_cancelled", "Sitzung abgesagt"),
                    ("task_assigned", "Aufgabe zugewiesen"),
                    ("task_due_soon", "Aufgabe fällig"),
                    ("task_completed", "Aufgabe erledigt"),
                    ("task_comment", "Kommentar zur Aufgabe"),
                    ("motion_shared", "Antrag geteilt"),
                    ("motion_comment", "Kommentar zum Antrag"),
                    ("motion_status", "Antragsstatus geändert"),
                    ("motion_assigned", "Dokument zugewiesen"),
                    ("motion_due_soon", "Dokument fällig"),
                    ("motion_approval_req", "Freigabe angefragt"),
                    ("motion_approval_dec", "Freigabe entschieden"),
                    ("faction_reminder", "Fraktionssitzung"),
                    ("faction_updated", "Fraktionssitzung aktualisiert"),
                    ("faction_inv_release", "Einladungsfreigabe erforderlich"),
                    ("faction_invitation", "Einladung zur Fraktionssitzung"),
                    ("faction_prop_decided", "TOP-Vorschlag entschieden"),
                    ("faction_prot_approved", "Fraktionsprotokoll genehmigt"),
                    ("member_joined", "Neues Mitglied"),
                    ("role_changed", "Rolle geändert"),
                    ("support_created", "Support-Ticket erstellt"),
                    ("support_reply", "Neue Antwort auf Ticket"),
                    ("support_status", "Ticketstatus geändert"),
                    ("support_resolved", "Ticket gelöst"),
                    ("support_escalated", "Ticket eskaliert"),
                    ("change_request_new", "Neuer Änderungsantrag"),
                    ("change_request_decided", "Änderungsantrag entschieden"),
                    ("absence_deputy", "Stellvertretung zugewiesen"),
                    ("system", "Systemnachricht"),
                    ("announcement", "Ankündigung"),
                ],
                default="system",
                max_length=30,
                verbose_name="Typ",
            ),
        ),
        migrations.CreateModel(
            name="CalendarFeedToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.work.faction.models.generate_opaque_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Feed-Token",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "regenerated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt erneuert"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_feed_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer:in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalender-Feed-Token",
                "verbose_name_plural": "Kalender-Feed-Tokens",
            },
        ),
    ]
