# Generated by Django 5.2.11 on 2026-07-21 21:33

import apps.work.faction.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0020_eigene_absender_mail"),
        ("work", "0048_inapp_benachrichtigungen_und_ical_feed"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactionPublicApiAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Öffentliche API aktiviert"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.work.faction.models.generate_opaque_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="API-Token",
                    ),
                ),
                (
                    "past_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Vergangene Sitzungen (Tage)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_api_access",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öffentlicher API-Zugang",
                "verbose_name_plural": "Öffentliche API-Zugänge",
            },
        ),
    ]
