# Generated by Django 5.2.11 on 2026-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0049_oeffentliche_api_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionpublicapiaccess",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                help_text="Leer = alle. Sonst z. B. https://fraktion-beispiel.de, https://www.fraktion-beispiel.de",
                verbose_name="Erlaubte Origins (CORS)",
            ),
        ),
        migrations.AddField(
            model_name="factionpublicapiaccess",
            name="cache_seconds",
            field=models.PositiveIntegerField(
                default=300, verbose_name="Cache-Dauer (Sekunden)"
            ),
        ),
        migrations.AddField(
            model_name="factionpublicapiaccess",
            name="future_days",
            field=models.PositiveIntegerField(
                default=365, verbose_name="Kommende Sitzungen (Tage)"
            ),
        ),
        migrations.AddField(
            model_name="factionpublicapiaccess",
            name="last_request_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letzter Abruf"
            ),
        ),
        migrations.AddField(
            model_name="factionpublicapiaccess",
            name="request_count",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Abrufe gesamt"
            ),
        ),
        migrations.AddField(
            model_name="factionpublicapiaccess",
            name="show_agenda",
            field=models.BooleanField(
                default=True, verbose_name="Tagesordnung ausliefern"
            ),
        ),
        migrations.AddField(
            model_name="factionpublicapiaccess",
            name="show_location",
            field=models.BooleanField(
                default=True, verbose_name="Sitzungsort ausliefern"
            ),
        ),
    ]
