# Generated by Django 6.0.6 on 2026-09-08 16:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0023_endgeraete"),
        ("tenants", "0020_eigene_absender_mail"),
        ("work", "0050_api_optionen"),
    ]

    operations = [
        migrations.AddField(
            model_name="motion",
            name="session_application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_motion",
                to="session.sessionapplication",
                verbose_name="Antrag bei der Verwaltung",
            ),
        ),
        migrations.CreateModel(
            name="AdministrationConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(max_length=64, verbose_name="Token (SHA-256)"),
                ),
                (
                    "token_prefix",
                    models.CharField(blank=True, max_length=8, verbose_name="Token-Präfix"),
                ),
                (
                    "connected_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Verbunden am"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Letzte Einreichung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.membership",
                        verbose_name="Verbunden von",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administration_connection",
                        to="tenants.organization",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_connections",
                        to="session.sessiontenant",
                        verbose_name="Verwaltung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verbindung zur Verwaltung",
                "verbose_name_plural": "Verbindungen zur Verwaltung",
            },
        ),
    ]
