# Generated by Django 6.0.6 on 2026-09-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0051_verwaltung_einreichung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("meeting_reminder", "Sitzungserinnerung"),
                    ("meeting_updated", "Sitzung aktualisiert"),
                    ("meeting_cancelled", "Sitzung abgesagt"),
                    ("task_assigned", "Aufgabe zugewiesen"),
                    ("task_due_soon", "Aufgabe fällig"),
                    ("task_completed", "Aufgabe erledigt"),
                    ("task_comment", "Kommentar zur Aufgabe"),
                    ("motion_shared", "Antrag geteilt"),
                    ("motion_comment", "Kommentar zum Antrag"),
                    ("motion_status", "Antragsstatus geändert"),
                    ("motion_assigned", "Dokument zugewiesen"),
                    ("motion_due_soon", "Dokument fällig"),
                    ("motion_approval_req", "Freigabe angefragt"),
                    ("motion_approval_dec", "Freigabe entschieden"),
                    ("faction_reminder", "Fraktionssitzung"),
                    ("faction_updated", "Fraktionssitzung aktualisiert"),
                    ("faction_inv_release", "Einladungsfreigabe erforderlich"),
                    ("faction_invitation", "Einladung zur Fraktionssitzung"),
                    ("faction_prop_decided", "TOP-Vorschlag entschieden"),
                    ("faction_prot_approved", "Fraktionsprotokoll genehmigt"),
                    ("member_joined", "Neues Mitglied"),
                    ("registration_request", "Registrierungsanfrage"),
                    ("role_changed", "Rolle geändert"),
                    ("support_created", "Support-Ticket erstellt"),
                    ("support_reply", "Neue Antwort auf Ticket"),
                    ("support_status", "Ticketstatus geändert"),
                    ("support_resolved", "Ticket gelöst"),
                    ("support_escalated", "Ticket eskaliert"),
                    ("change_request_new", "Neuer Änderungsantrag"),
                    ("change_request_decided", "Änderungsantrag entschieden"),
                    ("absence_deputy", "Stellvertretung zugewiesen"),
                    ("system", "Systemnachricht"),
                    ("announcement", "Ankündigung"),
                ],
                default="system",
                max_length=30,
                verbose_name="Typ",
            ),
        ),
    ]
