# Generated by Django 6.1.1 on 2026-09-25 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0021_registrierungsanfrage"),
        ("work", "0052_benachrichtigung_registrierungsanfrage"),
        ("common", "0005_protokoll_kettenkopf"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionauditlog",
            name="entry_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Eintrags-Hash",
            ),
        ),
        migrations.AddField(
            model_name="factionauditlog",
            name="membership_ref",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="Mitglied-Referenz"
            ),
        ),
        migrations.AddField(
            model_name="factionauditlog",
            name="prev_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Vorgänger-Hash",
            ),
        ),
        migrations.AddField(
            model_name="factionauditlog",
            name="seq",
            field=models.BigIntegerField(
                blank=True, editable=False, null=True, verbose_name="Laufende Nummer"
            ),
        ),
        migrations.AlterField(
            model_name="factionauditlog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Zeitpunkt",
            ),
        ),
    ]
