# Generated by Django 6.1.1 on 2026-09-25 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0054_fraktionsprotokoll_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="motion",
            name="administration_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Entwurf"),
                    ("review", "In Prüfung"),
                    ("approved", "Freigegeben"),
                    ("submitted", "Eingereicht"),
                    ("completed", "Erledigt"),
                    ("rejected", "Abgelehnt"),
                    ("archived", "Archiviert"),
                    ("deleted", "Gelöscht"),
                    ("internal_review", "Interne Absprache"),
                    ("external_review", "Externe Absprache"),
                    ("at_admin", "Bei Verwaltung"),
                    ("on_agenda", "Auf Tagesordnung"),
                    ("adopted", "Beschlossen"),
                    ("withdrawn", "Zurückgezogen"),
                ],
                max_length=20,
                verbose_name="Stand laut Verwaltung",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("review", "In Prüfung"),
                    ("approved", "Freigegeben"),
                    ("submitted", "Eingereicht"),
                    ("completed", "Erledigt"),
                    ("rejected", "Abgelehnt"),
                    ("archived", "Archiviert"),
                    ("deleted", "Gelöscht"),
                    ("internal_review", "Interne Absprache"),
                    ("external_review", "Externe Absprache"),
                    ("at_admin", "Bei Verwaltung"),
                    ("on_agenda", "Auf Tagesordnung"),
                    ("adopted", "Beschlossen"),
                    ("withdrawn", "Zurückgezogen"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="MotionAdministrationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=200, verbose_name="Schlüssel")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("submitted", "Eingereicht"),
                            ("status", "Antragsstatus"),
                            ("paper", "Vorlagennummer"),
                            ("scheduled", "Beratung terminiert"),
                            ("result", "Beratungsergebnis"),
                            ("decision", "Beschluss"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gemeldet am"),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administration_events",
                        to="work.motion",
                        verbose_name="Dokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rückmeldung der Verwaltung",
                "verbose_name_plural": "Rückmeldungen der Verwaltung",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("motion", "key"),
                        name="uniq_motion_administration_event",
                    )
                ],
            },
        ),
    ]
