# Generated by Django 6.1.1 on 2026-09-26 11:11

import apps.work.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0055_rueckmeldung_verwaltung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendasupplementarydocument",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=apps.work.files.meeting_document_path,
                verbose_name="Datei",
            ),
        ),
        migrations.AlterField(
            model_name="factionagendaitemattachment",
            name="file",
            field=models.FileField(
                upload_to=apps.work.files.faction_attachment_path, verbose_name="Datei"
            ),
        ),
        migrations.AlterField(
            model_name="organizationletterhead",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.work.files.letterhead_path,
                verbose_name="PDF-Datei",
            ),
        ),
        migrations.AlterField(
            model_name="supportticketattachment",
            name="file",
            field=models.FileField(
                upload_to=apps.work.files.support_attachment_path, verbose_name="Datei"
            ),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="file",
            field=models.FileField(
                upload_to=apps.work.files.task_attachment_path, verbose_name="Datei"
            ),
        ),
    ]
