# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-26 18:13
"""
Kalender-Feed-Token nur als Hash speichern (apps/common/tokens.py).

Die Migration hasht den vorhandenen Klartext. Abonnierte Feed-URLs funktionieren weiter, weil die
Anwendung das Token aus der URL ebenso hasht. Anzeigen kann die Profilseite die URL danach nicht
mehr; wer sie noch einmal braucht, erzeugt eine neue. Werte, die schon wie ein Hash aussehen
(64 Hex-Zeichen), bleiben unverändert – die Migration ist damit wiederholbar.

Rückwärts bleibt der Hash stehen: Eine ältere Version findet die Feeds dann nicht mehr; nach
„Feed-URL erneuern“ gibt es wieder eine gültige URL.
"""

import hashlib
import re

import apps.common.tokens
from django.db import migrations, models

HASH_FORM = re.compile(r"[0-9a-f]{64}")


def hash_tokens(apps, schema_editor):
    model = apps.get_model("work", "CalendarFeedToken")
    changed = [
        model(pk=pk, token=hashlib.sha256(value.encode("utf-8")).hexdigest())
        for pk, value in list(model.objects.values_list("pk", "token"))
        if value and not HASH_FORM.fullmatch(value)
    ]
    model.objects.bulk_update(changed, ["token"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0057_editorzustand_verschluesselt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarfeedtoken",
            name="token",
            field=models.CharField(
                default=apps.common.tokens.unusable_token_hash,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="Feed-Token (SHA-256)",
            ),
        ),
        migrations.RunPython(hash_tokens, migrations.RunPython.noop),
    ]
