# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.0.6 on 2026-09-29 09:26
"""
Mitglied entfernen löscht keine Inhalte der Organisation mehr (Issue #420).

Verweise von Organisationsinhalten (Dokumente, Aufgaben, Fraktionssitzungen, Protokolle, Tickets …)
auf die Mitgliedschaft werden beim Entfernen geleert statt die Inhalte per Kaskade zu löschen. Rein
persönliche Daten entfallen weiter (CASCADE bzw. apps/work/organization/member_data.py).

Schema: nur ``DROP NOT NULL`` auf den betroffenen Spalten; ``on_delete`` wirkt in Django, nicht in
der Datenbank. Abwärtskompatibel: Eine ältere Version läuft auf dem Schema weiter.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0023_zugangstoken_als_hash"),
        ("work", "0058_zugangstoken_als_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaitemnote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_notes",
                to="tenants.membership",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="agendaspeechnote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="speech_notes",
                to="tenants.membership",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="agendasupplementarydocument",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_documents",
                to="tenants.membership",
                verbose_name="Hinzugefügt von",
            ),
        ),
        migrations.AlterField(
            model_name="factionattendance",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faction_attendances",
                to="tenants.membership",
                verbose_name="Mitglied",
            ),
        ),
        migrations.AlterField(
            model_name="factionattendancecertificate",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_certificates",
                to="tenants.membership",
                verbose_name="Mitglied",
            ),
        ),
        migrations.AlterField(
            model_name="factiondecision",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_decisions",
                to="tenants.membership",
                verbose_name="Erfasst von",
            ),
        ),
        migrations.AlterField(
            model_name="factionmeeting",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_faction_meetings",
                to="tenants.membership",
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="factionprotocolentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_protocol_entries",
                to="tenants.membership",
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="fileannotation",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_annotations",
                to="tenants.membership",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="meetingpreparation",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meeting_preparations",
                to="tenants.membership",
                verbose_name="Mitglied",
            ),
        ),
        migrations.AlterField(
            model_name="motion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_motions",
                to="tenants.membership",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="motionapproval",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motion_approvals",
                to="tenants.membership",
                verbose_name="Genehmiger",
            ),
        ),
        migrations.AlterField(
            model_name="motioncomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motion_comments",
                to="tenants.membership",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="motiondocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="tenants.membership",
                verbose_name="Hochgeladen von",
            ),
        ),
        migrations.AlterField(
            model_name="motionrevision",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motion_revisions",
                to="tenants.membership",
                verbose_name="Geändert von",
            ),
        ),
        migrations.AlterField(
            model_name="papercomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paper_comments",
                to="tenants.membership",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tickets",
                to="tenants.membership",
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="supportticketmessage",
            name="author_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_messages",
                to="tenants.membership",
                verbose_name="Autor (Mitglied)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to="tenants.membership",
                verbose_name="Zugewiesen an",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to="tenants.membership",
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_activities",
                to="tenants.membership",
                verbose_name="Akteur",
            ),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_attachments",
                to="tenants.membership",
                verbose_name="Hochgeladen von",
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_comments",
                to="tenants.membership",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="taskshare",
            name="shared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_shares_given",
                to="tenants.membership",
                verbose_name="Geteilt von",
            ),
        ),
    ]
