# Generated by Django 6.0.6 on 2026-09-29 22:51

import apps.work.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0064_bezug_dokumente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motiondocument",
            name="file",
            field=models.FileField(
                upload_to=apps.work.files.motion_document_path, verbose_name="Datei"
            ),
        ),
    ]
