# Generated by Django 6.0.6 on 2026-09-29 23:30

import apps.work.motions.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0025_recht_dokumente_ehemaliger_mitglieder"),
        ("work", "0065_anhang_zufallsname"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionEmailSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submitted_by_name",
                    models.CharField(
                        max_length=255, verbose_name="Name der einreichenden Person"
                    ),
                ),
                (
                    "submitted_by_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="E-Mail der einreichenden Person",
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Betreff")),
                (
                    "attachment_names",
                    models.JSONField(blank=True, default=list, verbose_name="Anhänge"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Versendet am"
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_submissions",
                        to="work.motion",
                        verbose_name="Dokument",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.membership",
                        verbose_name="Eingereicht von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einreichung per E-Mail",
                "verbose_name_plural": "Einreichungen per E-Mail",
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("motion",),
                        name="work_email_submission_one_per_motion",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MotionEmailRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Bezeichnung")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "delivered",
                    models.BooleanField(default=False, verbose_name="Versendet"),
                ),
                (
                    "confirmation_nonce",
                    models.CharField(
                        default=apps.work.motions.models._confirmation_nonce,
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eingang bestätigt am"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="work.motionemailsubmission",
                        verbose_name="Einreichung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empfänger der Einreichung",
                "verbose_name_plural": "Empfänger der Einreichung",
                "ordering": ["label", "email"],
            },
        ),
    ]
