# SPDX-License-Identifier: AGPL-3.0-or-later
"""
URL configuration for Session RIS.

All URLs are prefixed with /session/<tenant_slug>/
"""

from django.urls import path

from . import views
from .api import views as api_views

app_name = "session"

urlpatterns = [
    # Einladung annehmen (tenant-unabhängig, token-basiert)
    path(
        "invite/<str:token>/",
        views.InvitationAcceptView.as_view(),
        name="invitation_accept",
    ),
    # Dashboard
    path(
        "<slug:tenant_slug>/",
        views.DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "<slug:tenant_slug>/dashboard/",
        views.DashboardView.as_view(),
        name="dashboard_explicit",
    ),
    # Meetings
    path(
        "<slug:tenant_slug>/meetings/",
        views.MeetingListView.as_view(),
        name="meetings",
    ),
    path(
        "<slug:tenant_slug>/meetings/create/",
        views.MeetingCreateView.as_view(),
        name="meeting_create",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/",
        views.MeetingDetailView.as_view(),
        name="meeting_detail",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/edit/",
        views.MeetingUpdateView.as_view(),
        name="meeting_edit",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/invitation/",
        views.MeetingInvitationView.as_view(),
        name="meeting_invitation",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/agenda.pdf",
        views.MeetingAgendaPdfView.as_view(),
        name="meeting_agenda_pdf",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/sitzung.ics",
        views.MeetingIcsView.as_view(),
        name="meeting_ics",
    ),
    # Niederschrift (Issue #31)
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/",
        views.ProtocolDetailView.as_view(),
        name="meeting_protocol",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/create/",
        views.ProtocolCreateView.as_view(),
        name="meeting_protocol_create",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/edit/",
        views.ProtocolEditView.as_view(),
        name="meeting_protocol_edit",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/<str:action>/",
        views.ProtocolWorkflowView.as_view(),
        name="meeting_protocol_action",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/niederschrift.pdf",
        views.ProtocolPdfView.as_view(),
        name="meeting_protocol_pdf",
    ),
    # Beschlussregister und Beschlussauszüge (Issue #32)
    path(
        "<slug:tenant_slug>/resolutions/",
        views.ResolutionRegisterView.as_view(),
        name="resolutions",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/resolutions/generate/",
        views.ResolutionBatchView.as_view(),
        name="resolutions_generate",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/beschlussauszuege.pdf",
        views.ResolutionMeetingPdfView.as_view(),
        name="resolutions_meeting_pdf",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/beschlussauszug.pdf",
        views.ResolutionExtractPdfView.as_view(),
        name="resolution_extract_pdf",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/forwarding/add/",
        views.ResolutionForwardingCreateView.as_view(),
        name="resolution_forwarding_add",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/agenda/add/",
        views.AgendaItemCreateView.as_view(),
        name="agenda_item_create",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/agenda/reorder/",
        views.AgendaReorderView.as_view(),
        name="agenda_reorder",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/edit/",
        views.AgendaItemUpdateView.as_view(),
        name="agenda_item_edit",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/withdraw/",
        views.AgendaItemWithdrawView.as_view(),
        name="agenda_item_withdraw",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/delete/",
        views.AgendaItemDeleteView.as_view(),
        name="agenda_item_delete",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/move/",
        views.AgendaItemMoveView.as_view(),
        name="agenda_item_move",
    ),
    # Papers
    path(
        "<slug:tenant_slug>/papers/",
        views.PaperListView.as_view(),
        name="papers",
    ),
    path(
        "<slug:tenant_slug>/papers/create/",
        views.PaperCreateView.as_view(),
        name="paper_create",
    ),
    path(
        "<slug:tenant_slug>/papers/review/",
        views.PaperReviewListView.as_view(),
        name="papers_review",
    ),
    path(
        "<slug:tenant_slug>/papers/<uuid:paper_id>/workflow/<str:action>/",
        views.PaperWorkflowView.as_view(),
        name="paper_workflow",
    ),
    path(
        "<slug:tenant_slug>/papers/<uuid:paper_id>/",
        views.PaperDetailView.as_view(),
        name="paper_detail",
    ),
    path(
        "<slug:tenant_slug>/papers/<uuid:paper_id>/edit/",
        views.PaperUpdateView.as_view(),
        name="paper_edit",
    ),
    # Applications
    path(
        "<slug:tenant_slug>/applications/",
        views.ApplicationListView.as_view(),
        name="applications",
    ),
    path(
        "<slug:tenant_slug>/applications/<uuid:application_id>/",
        views.ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path(
        "<slug:tenant_slug>/applications/<uuid:application_id>/process/",
        views.ApplicationProcessView.as_view(),
        name="application_process",
    ),
    path(
        "<slug:tenant_slug>/applications/<uuid:application_id>/convert/",
        views.ApplicationConvertView.as_view(),
        name="application_convert",
    ),
    # Organizations
    path(
        "<slug:tenant_slug>/organizations/",
        views.OrganizationListView.as_view(),
        name="organizations",
    ),
    path(
        "<slug:tenant_slug>/organizations/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/",
        views.OrganizationDetailView.as_view(),
        name="organization_detail",
    ),
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/edit/",
        views.OrganizationUpdateView.as_view(),
        name="organization_edit",
    ),
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/deactivate/",
        views.OrganizationDeactivateView.as_view(),
        name="organization_deactivate",
    ),
    # Memberships (Besetzung)
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/memberships/add/",
        views.MembershipCreateView.as_view(),
        name="membership_create",
    ),
    path(
        "<slug:tenant_slug>/memberships/<uuid:membership_id>/update/",
        views.MembershipUpdateView.as_view(),
        name="membership_update",
    ),
    path(
        "<slug:tenant_slug>/memberships/<uuid:membership_id>/end/",
        views.MembershipEndView.as_view(),
        name="membership_end",
    ),
    path(
        "<slug:tenant_slug>/memberships/<uuid:membership_id>/succession/",
        views.MembershipSuccessionView.as_view(),
        name="membership_succession",
    ),
    # Persons
    path(
        "<slug:tenant_slug>/persons/",
        views.PersonListView.as_view(),
        name="persons",
    ),
    path(
        "<slug:tenant_slug>/persons/create/",
        views.PersonCreateView.as_view(),
        name="person_create",
    ),
    path(
        "<slug:tenant_slug>/persons/<uuid:person_id>/",
        views.PersonDetailView.as_view(),
        name="person_detail",
    ),
    path(
        "<slug:tenant_slug>/persons/<uuid:person_id>/edit/",
        views.PersonUpdateView.as_view(),
        name="person_edit",
    ),
    path(
        "<slug:tenant_slug>/persons/<uuid:person_id>/deactivate/",
        views.PersonDeactivateView.as_view(),
        name="person_deactivate",
    ),
    # Settings
    path(
        "<slug:tenant_slug>/settings/",
        views.SettingsView.as_view(),
        name="settings",
    ),
    path(
        "<slug:tenant_slug>/settings/users/",
        views.UserListView.as_view(),
        name="users",
    ),
    path(
        "<slug:tenant_slug>/settings/users/invite/",
        views.UserInviteView.as_view(),
        name="user_invite",
    ),
    path(
        "<slug:tenant_slug>/settings/users/<uuid:session_user_id>/roles/",
        views.UserRolesUpdateView.as_view(),
        name="user_roles_update",
    ),
    path(
        "<slug:tenant_slug>/settings/users/<uuid:session_user_id>/deactivate/",
        views.UserDeactivateView.as_view(),
        name="user_deactivate",
    ),
    path(
        "<slug:tenant_slug>/settings/invitations/<uuid:invitation_id>/cancel/",
        views.InvitationCancelView.as_view(),
        name="invitation_cancel",
    ),
    # Audit-Log
    path(
        "<slug:tenant_slug>/audit/",
        views.AuditLogListView.as_view(),
        name="audit_log",
    ),
    # Files / Anlagen
    path(
        "<slug:tenant_slug>/files/upload/",
        views.FileUploadView.as_view(),
        name="file_upload",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/download/",
        views.FileDownloadView.as_view(),
        name="file_download",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/update/",
        views.FileUpdateView.as_view(),
        name="file_update",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/replace/",
        views.FileReplaceView.as_view(),
        name="file_replace",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/delete/",
        views.FileDeleteView.as_view(),
        name="file_delete",
    ),
    # Anwesenheit (Issue #30)
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/attendance/generate/",
        views.AttendanceGenerateView.as_view(),
        name="attendance_generate",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/attendance/add/",
        views.AttendanceAddView.as_view(),
        name="attendance_add",
    ),
    path(
        "<slug:tenant_slug>/attendance/<uuid:attendance_id>/delete/",
        views.AttendanceDeleteView.as_view(),
        name="attendance_delete",
    ),
    # HTMX endpoints
    path(
        "<slug:tenant_slug>/attendance/<uuid:attendance_id>/update/",
        views.AttendanceUpdateView.as_view(),
        name="attendance_update",
    ),
    # API (OParl + Session extension)
    path(
        "<slug:tenant_slug>/api/",
        api_views.APIRootView.as_view(),
        name="api_root",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/",
        api_views.OParlSystemView.as_view(),
        name="oparl_system",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/bodies/",
        api_views.OParlBodyListView.as_view(),
        name="oparl_bodies",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/body/",
        api_views.OParlBodyView.as_view(),
        name="oparl_body",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/organizations/",
        api_views.OParlOrganizationListView.as_view(),
        name="oparl_organizations",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/persons/",
        api_views.OParlPersonListView.as_view(),
        name="oparl_persons",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/meetings/",
        api_views.OParlMeetingListView.as_view(),
        name="oparl_meetings",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/papers/",
        api_views.OParlPaperListView.as_view(),
        name="oparl_papers",
    ),
    # Session API (extended, authenticated)
    path(
        "<slug:tenant_slug>/api/session/meetings/",
        api_views.SessionMeetingListAPIView.as_view(),
        name="api_meetings",
    ),
    path(
        "<slug:tenant_slug>/api/session/papers/",
        api_views.SessionPaperListAPIView.as_view(),
        name="api_papers",
    ),
    path(
        "<slug:tenant_slug>/api/session/applications/",
        api_views.SessionApplicationListAPIView.as_view(),
        name="api_applications",
    ),
    path(
        "<slug:tenant_slug>/api/session/applications/submit/",
        api_views.ApplicationSubmitAPIView.as_view(),
        name="api_application_submit",
    ),
]
