# SPDX-License-Identifier: AGPL-3.0-or-later
"""
URL configuration for Session RIS.

All URLs are prefixed with /session/<tenant_slug>/
"""

from django.urls import path

from . import views
from .api import oparl as oparl_api_views
from .api import views as api_views

app_name = "session"

urlpatterns = [
    # Einladung annehmen (tenant-unabhängig, token-basiert)
    path(
        "invite/<str:token>/",
        views.InvitationAcceptView.as_view(),
        name="invitation_accept",
    ),
    # Dashboard
    path(
        "<slug:tenant_slug>/",
        views.DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "<slug:tenant_slug>/dashboard/",
        views.DashboardView.as_view(),
        name="dashboard_explicit",
    ),
    # Meetings
    path(
        "<slug:tenant_slug>/meetings/",
        views.MeetingListView.as_view(),
        name="meetings",
    ),
    path(
        "<slug:tenant_slug>/meetings/create/",
        views.MeetingCreateView.as_view(),
        name="meeting_create",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/",
        views.MeetingDetailView.as_view(),
        name="meeting_detail",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/edit/",
        views.MeetingUpdateView.as_view(),
        name="meeting_edit",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/invitation/",
        views.MeetingInvitationView.as_view(),
        name="meeting_invitation",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/agenda.pdf",
        views.MeetingAgendaPdfView.as_view(),
        name="meeting_agenda_pdf",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/sitzung.ics",
        views.MeetingIcsView.as_view(),
        name="meeting_ics",
    ),
    # Niederschrift (Issue #31)
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/",
        views.ProtocolDetailView.as_view(),
        name="meeting_protocol",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/create/",
        views.ProtocolCreateView.as_view(),
        name="meeting_protocol_create",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/edit/",
        views.ProtocolEditView.as_view(),
        name="meeting_protocol_edit",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/protocol/<str:action>/",
        views.ProtocolWorkflowView.as_view(),
        name="meeting_protocol_action",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/niederschrift.pdf",
        views.ProtocolPdfView.as_view(),
        name="meeting_protocol_pdf",
    ),
    # Sitzungskalender und Jahresplanung (Issue #82)
    path(
        "<slug:tenant_slug>/meetings/calendar/",
        views.MeetingCalendarView.as_view(),
        name="meeting_calendar",
    ),
    path(
        "<slug:tenant_slug>/meetings/plan/",
        views.MeetingPlanView.as_view(),
        name="meeting_plan",
    ),
    path(
        "<slug:tenant_slug>/sitzungsplan.pdf",
        views.YearPlanPdfView.as_view(),
        name="year_plan_pdf",
    ),
    path(
        "<slug:tenant_slug>/organizations/<uuid:org_id>/sitzungen.ics",
        views.OrganizationIcsFeedView.as_view(),
        name="organization_ics_feed",
    ),
    # Übergreifende Suche (Issue #45)
    path(
        "<slug:tenant_slug>/search/",
        views.SessionSearchView.as_view(),
        name="search",
    ),
    # Statistiken und Berichte (Issue #84)
    path(
        "<slug:tenant_slug>/reports/",
        views.ReportsView.as_view(),
        name="reports",
    ),
    path(
        "<slug:tenant_slug>/reports/export.csv",
        views.ReportCsvExportView.as_view(),
        name="reports_export_csv",
    ),
    # Beschlussregister und Beschlussauszüge (Issue #32)
    path(
        "<slug:tenant_slug>/resolutions/",
        views.ResolutionRegisterView.as_view(),
        name="resolutions",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/resolutions/generate/",
        views.ResolutionBatchView.as_view(),
        name="resolutions_generate",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/beschlussauszuege.pdf",
        views.ResolutionMeetingPdfView.as_view(),
        name="resolutions_meeting_pdf",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/beschlussauszug.pdf",
        views.ResolutionExtractPdfView.as_view(),
        name="resolution_extract_pdf",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/forwarding/add/",
        views.ResolutionForwardingCreateView.as_view(),
        name="resolution_forwarding_add",
    ),
    # Beschlusskontrolle (Issue #37)
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/tracking/",
        views.ResolutionTrackingUpdateView.as_view(),
        name="resolution_tracking_update",
    ),
    path(
        "<slug:tenant_slug>/resolutions/export.csv",
        views.ResolutionCsvExportView.as_view(),
        name="resolutions_export_csv",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/agenda/add/",
        views.AgendaItemCreateView.as_view(),
        name="agenda_item_create",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/agenda/reorder/",
        views.AgendaReorderView.as_view(),
        name="agenda_reorder",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/edit/",
        views.AgendaItemUpdateView.as_view(),
        name="agenda_item_edit",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/withdraw/",
        views.AgendaItemWithdrawView.as_view(),
        name="agenda_item_withdraw",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/delete/",
        views.AgendaItemDeleteView.as_view(),
        name="agenda_item_delete",
    ),
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/move/",
        views.AgendaItemMoveView.as_view(),
        name="agenda_item_move",
    ),
    # Papers
    path(
        "<slug:tenant_slug>/papers/",
        views.PaperListView.as_view(),
        name="papers",
    ),
    path(
        "<slug:tenant_slug>/papers/create/",
        views.PaperCreateView.as_view(),
        name="paper_create",
    ),
    path(
        "<slug:tenant_slug>/papers/review/",
        views.PaperReviewListView.as_view(),
        name="papers_review",
    ),
    path(
        "<slug:tenant_slug>/papers/<uuid:paper_id>/workflow/<str:action>/",
        views.PaperWorkflowView.as_view(),
        name="paper_workflow",
    ),
    path(
        "<slug:tenant_slug>/papers/<uuid:paper_id>/",
        views.PaperDetailView.as_view(),
        name="paper_detail",
    ),
    path(
        "<slug:tenant_slug>/papers/<uuid:paper_id>/edit/",
        views.PaperUpdateView.as_view(),
        name="paper_edit",
    ),
    # Beratungsfolge (Issue #34)
    path(
        "<slug:tenant_slug>/papers/<uuid:paper_id>/consultations/add/",
        views.ConsultationCreateView.as_view(),
        name="consultation_add",
    ),
    path(
        "<slug:tenant_slug>/consultations/<uuid:consultation_id>/update/",
        views.ConsultationUpdateView.as_view(),
        name="consultation_update",
    ),
    path(
        "<slug:tenant_slug>/consultations/<uuid:consultation_id>/delete/",
        views.ConsultationDeleteView.as_view(),
        name="consultation_delete",
    ),
    path(
        "<slug:tenant_slug>/consultations/<uuid:consultation_id>/move/",
        views.ConsultationMoveView.as_view(),
        name="consultation_move",
    ),
    path(
        "<slug:tenant_slug>/consultations/<uuid:consultation_id>/schedule/",
        views.ConsultationScheduleView.as_view(),
        name="consultation_schedule",
    ),
    path(
        "<slug:tenant_slug>/consultations/<uuid:consultation_id>/forward/",
        views.ConsultationForwardView.as_view(),
        name="consultation_forward",
    ),
    # Applications
    path(
        "<slug:tenant_slug>/applications/",
        views.ApplicationListView.as_view(),
        name="applications",
    ),
    path(
        "<slug:tenant_slug>/applications/<uuid:application_id>/",
        views.ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path(
        "<slug:tenant_slug>/applications/<uuid:application_id>/process/",
        views.ApplicationProcessView.as_view(),
        name="application_process",
    ),
    path(
        "<slug:tenant_slug>/applications/<uuid:application_id>/convert/",
        views.ApplicationConvertView.as_view(),
        name="application_convert",
    ),
    # Organizations
    path(
        "<slug:tenant_slug>/organizations/",
        views.OrganizationListView.as_view(),
        name="organizations",
    ),
    path(
        "<slug:tenant_slug>/organizations/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/",
        views.OrganizationDetailView.as_view(),
        name="organization_detail",
    ),
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/edit/",
        views.OrganizationUpdateView.as_view(),
        name="organization_edit",
    ),
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/deactivate/",
        views.OrganizationDeactivateView.as_view(),
        name="organization_deactivate",
    ),
    # Memberships (Besetzung)
    path(
        "<slug:tenant_slug>/organizations/<uuid:organization_id>/memberships/add/",
        views.MembershipCreateView.as_view(),
        name="membership_create",
    ),
    path(
        "<slug:tenant_slug>/memberships/<uuid:membership_id>/update/",
        views.MembershipUpdateView.as_view(),
        name="membership_update",
    ),
    path(
        "<slug:tenant_slug>/memberships/<uuid:membership_id>/end/",
        views.MembershipEndView.as_view(),
        name="membership_end",
    ),
    path(
        "<slug:tenant_slug>/memberships/<uuid:membership_id>/succession/",
        views.MembershipSuccessionView.as_view(),
        name="membership_succession",
    ),
    # Persons
    path(
        "<slug:tenant_slug>/persons/",
        views.PersonListView.as_view(),
        name="persons",
    ),
    path(
        "<slug:tenant_slug>/persons/create/",
        views.PersonCreateView.as_view(),
        name="person_create",
    ),
    path(
        "<slug:tenant_slug>/persons/<uuid:person_id>/",
        views.PersonDetailView.as_view(),
        name="person_detail",
    ),
    path(
        "<slug:tenant_slug>/persons/<uuid:person_id>/edit/",
        views.PersonUpdateView.as_view(),
        name="person_edit",
    ),
    path(
        "<slug:tenant_slug>/persons/<uuid:person_id>/deactivate/",
        views.PersonDeactivateView.as_view(),
        name="person_deactivate",
    ),
    # DSGVO-Paket (Issue #43)
    path(
        "<slug:tenant_slug>/datenschutz/",
        views.PrivacyNoticeView.as_view(),
        name="privacy_notice",
    ),
    path(
        "<slug:tenant_slug>/settings/privacy/",
        views.PrivacySettingsView.as_view(),
        name="privacy_settings",
    ),
    path(
        "<slug:tenant_slug>/settings/privacy/purge/",
        views.PrivacyPurgeRunView.as_view(),
        name="privacy_purge",
    ),
    path(
        "<slug:tenant_slug>/persons/<uuid:person_id>/auskunft.json",
        views.PersonDataExportView.as_view(),
        name="person_data_export",
    ),
    # Sitzungsgeld-Abrechnung (Issue #38)
    path(
        "<slug:tenant_slug>/allowances/",
        views.AllowanceListView.as_view(),
        name="allowances",
    ),
    path(
        "<slug:tenant_slug>/allowances/rates/save/",
        views.AllowanceRateSaveView.as_view(),
        name="allowance_rate_save",
    ),
    path(
        "<slug:tenant_slug>/allowances/rates/<uuid:rate_id>/delete/",
        views.AllowanceRateDeleteView.as_view(),
        name="allowance_rate_delete",
    ),
    path(
        "<slug:tenant_slug>/allowances/debtor/save/",
        views.AllowanceDebtorSaveView.as_view(),
        name="allowance_debtor_save",
    ),
    path(
        "<slug:tenant_slug>/allowances/generate/",
        views.AllowanceGenerateView.as_view(),
        name="allowance_generate",
    ),
    path(
        "<slug:tenant_slug>/allowances/approve/",
        views.AllowanceApproveView.as_view(),
        name="allowance_approve",
    ),
    path(
        "<slug:tenant_slug>/allowances/export.csv",
        views.AllowanceCsvExportView.as_view(),
        name="allowance_export_csv",
    ),
    path(
        "<slug:tenant_slug>/allowances/export/sepa/",
        views.AllowanceSepaExportView.as_view(),
        name="allowance_export_sepa",
    ),
    path(
        "<slug:tenant_slug>/allowances/notice/<uuid:person_id>.pdf",
        views.AllowanceNoticePdfView.as_view(),
        name="allowance_notice_pdf",
    ),
    path(
        "<slug:tenant_slug>/allowances/year/",
        views.AllowanceYearView.as_view(),
        name="allowance_year",
    ),
    # Wahlperioden (Issue #39)
    path(
        "<slug:tenant_slug>/archive/",
        views.ArchiveView.as_view(),
        name="archive",
    ),
    path(
        "<slug:tenant_slug>/settings/terms/",
        views.TermListView.as_view(),
        name="terms",
    ),
    path(
        "<slug:tenant_slug>/settings/terms/save/",
        views.TermSaveView.as_view(),
        name="term_save",
    ),
    path(
        "<slug:tenant_slug>/settings/terms/change/",
        views.TermChangeView.as_view(),
        name="term_change",
    ),
    path(
        "<slug:tenant_slug>/settings/terms/<uuid:term_id>/delete/",
        views.TermDeleteView.as_view(),
        name="term_delete",
    ),
    # Settings
    path(
        "<slug:tenant_slug>/settings/",
        views.SettingsView.as_view(),
        name="settings",
    ),
    path(
        "<slug:tenant_slug>/settings/insight-publish/",
        views.InsightPublishView.as_view(),
        name="insight_publish",
    ),
    path(
        "<slug:tenant_slug>/settings/reminders/",
        views.ReminderSettingsView.as_view(),
        name="settings_reminders",
    ),
    # Digitale Abstimmung und Umlaufbeschlüsse (Issue #41)
    path(
        "<slug:tenant_slug>/agenda/<uuid:item_id>/voting/",
        views.VotingCaptureView.as_view(),
        name="voting_capture",
    ),
    path(
        "<slug:tenant_slug>/circulars/",
        views.CircularListView.as_view(),
        name="circulars",
    ),
    path(
        "<slug:tenant_slug>/circulars/create/",
        views.CircularCreateView.as_view(),
        name="circular_create",
    ),
    path(
        "<slug:tenant_slug>/circulars/<uuid:circular_id>/",
        views.CircularDetailView.as_view(),
        name="circular_detail",
    ),
    path(
        "<slug:tenant_slug>/circulars/<uuid:circular_id>/vote/",
        views.CircularVoteView.as_view(),
        name="circular_vote",
    ),
    path(
        "<slug:tenant_slug>/circulars/<uuid:circular_id>/close/",
        views.CircularCloseView.as_view(),
        name="circular_close",
    ),
    # Mitzeichnung (Issue #81)
    path(
        "<slug:tenant_slug>/cosignatures/",
        views.MyCosignaturesView.as_view(),
        name="my_cosignatures",
    ),
    path(
        "<slug:tenant_slug>/cosignatures/<uuid:cosign_id>/<slug:action>/",
        views.CosignatureActionView.as_view(),
        name="cosignature_action",
    ),
    path(
        "<slug:tenant_slug>/settings/cosign/",
        views.CosignSettingsView.as_view(),
        name="settings_cosign",
    ),
    path(
        "<slug:tenant_slug>/settings/cosign/rule/",
        views.CosignRuleManageView.as_view(),
        name="cosign_rule_manage",
    ),
    path(
        "<slug:tenant_slug>/settings/cosign/assignment/",
        views.DepartmentAssignmentView.as_view(),
        name="department_assignment",
    ),
    # Textbausteine und Standard-TOPs (Issue #85)
    path(
        "<slug:tenant_slug>/settings/textblocks/",
        views.TextblockSettingsView.as_view(),
        name="settings_textblocks",
    ),
    path(
        "<slug:tenant_slug>/settings/textblocks/standard/",
        views.StandardItemManageView.as_view(),
        name="standard_item_manage",
    ),
    path(
        "<slug:tenant_slug>/settings/textblocks/block/",
        views.TextblockManageView.as_view(),
        name="textblock_manage",
    ),
    path(
        "<slug:tenant_slug>/settings/users/",
        views.UserListView.as_view(),
        name="users",
    ),
    path(
        "<slug:tenant_slug>/settings/users/invite/",
        views.UserInviteView.as_view(),
        name="user_invite",
    ),
    path(
        "<slug:tenant_slug>/settings/users/<uuid:session_user_id>/roles/",
        views.UserRolesUpdateView.as_view(),
        name="user_roles_update",
    ),
    path(
        "<slug:tenant_slug>/settings/users/<uuid:session_user_id>/deactivate/",
        views.UserDeactivateView.as_view(),
        name="user_deactivate",
    ),
    path(
        "<slug:tenant_slug>/settings/invitations/<uuid:invitation_id>/cancel/",
        views.InvitationCancelView.as_view(),
        name="invitation_cancel",
    ),
    # Audit-Log
    path(
        "<slug:tenant_slug>/audit/",
        views.AuditLogListView.as_view(),
        name="audit_log",
    ),
    # Files / Anlagen
    path(
        "<slug:tenant_slug>/files/upload/",
        views.FileUploadView.as_view(),
        name="file_upload",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/download/",
        views.FileDownloadView.as_view(),
        name="file_download",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/update/",
        views.FileUpdateView.as_view(),
        name="file_update",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/replace/",
        views.FileReplaceView.as_view(),
        name="file_replace",
    ),
    path(
        "<slug:tenant_slug>/files/<uuid:file_id>/delete/",
        views.FileDeleteView.as_view(),
        name="file_delete",
    ),
    # Anwesenheit (Issue #30)
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/attendance/generate/",
        views.AttendanceGenerateView.as_view(),
        name="attendance_generate",
    ),
    path(
        "<slug:tenant_slug>/meetings/<uuid:meeting_id>/attendance/add/",
        views.AttendanceAddView.as_view(),
        name="attendance_add",
    ),
    path(
        "<slug:tenant_slug>/attendance/<uuid:attendance_id>/delete/",
        views.AttendanceDeleteView.as_view(),
        name="attendance_delete",
    ),
    # HTMX endpoints
    path(
        "<slug:tenant_slug>/attendance/<uuid:attendance_id>/update/",
        views.AttendanceUpdateView.as_view(),
        name="attendance_update",
    ),
    # API (OParl + Session extension)
    path(
        "<slug:tenant_slug>/api/",
        api_views.APIRootView.as_view(),
        name="api_root",
    ),
    # OParl-1.1-API je Mandant (Issue #35) — spec-konform, anonym, JSON
    path(
        "<slug:tenant_slug>/api/oparl/",
        oparl_api_views.system_view,
        name="oparl_system",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/bodies/",
        oparl_api_views.bodies_view,
        name="oparl_bodies",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/body/",
        oparl_api_views.body_view,
        name="oparl_body",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/file/<uuid:pk>/download/",
        oparl_api_views.file_download_view,
        name="oparl_file_download",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/<str:segment>/",
        oparl_api_views.list_view,
        name="oparl_list",
    ),
    path(
        "<slug:tenant_slug>/api/oparl/<str:kind>/<uuid:pk>/",
        oparl_api_views.object_view,
        name="oparl_object",
    ),
    # Session API (extended, authenticated)
    path(
        "<slug:tenant_slug>/api/session/meetings/",
        api_views.SessionMeetingListAPIView.as_view(),
        name="api_meetings",
    ),
    path(
        "<slug:tenant_slug>/api/session/papers/",
        api_views.SessionPaperListAPIView.as_view(),
        name="api_papers",
    ),
    path(
        "<slug:tenant_slug>/api/session/applications/",
        api_views.SessionApplicationListAPIView.as_view(),
        name="api_applications",
    ),
    path(
        "<slug:tenant_slug>/api/session/applications/submit/",
        api_views.ApplicationSubmitAPIView.as_view(),
        name="api_application_submit",
    ),
]
