# Generated by Django 6.0.6 on 2026-09-12 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bezeichnung")),
                (
                    "credential_id",
                    models.CharField(
                        max_length=512, unique=True, verbose_name="Credential-ID"
                    ),
                ),
                (
                    "public_key",
                    models.BinaryField(verbose_name="Öffentlicher Schlüssel"),
                ),
                (
                    "sign_count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Signaturzähler"
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Übertragungswege"
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True, max_length=36, verbose_name="Geräte-Modell (AAGUID)"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Gerätetyp"
                    ),
                ),
                (
                    "backed_up",
                    models.BooleanField(default=False, verbose_name="Synchronisiert"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sicherheitsschlüssel",
                "verbose_name_plural": "Sicherheitsschlüssel",
                "ordering": ["created_at"],
            },
        ),
    ]
