# Generated by Django 6.1.1 on 2026-09-25 10:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_registration_rejected_at"),
        ("common", "0005_protokoll_kettenkopf"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Zeitpunkt",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("login", "Anmeldung"),
                            ("logout", "Abmeldung"),
                            ("login_failed", "Anmeldung fehlgeschlagen"),
                        ],
                        max_length=30,
                        verbose_name="Ereignis",
                    ),
                ),
                (
                    "user_ref",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Konto-Referenz",
                    ),
                ),
                (
                    "identifier_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="Kennung (HMAC-SHA-256)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-Adresse"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="User-Agent"
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Angaben"),
                ),
                (
                    "seq",
                    models.BigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Laufende Nummer",
                    ),
                ),
                (
                    "prev_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        verbose_name="Vorgänger-Hash",
                    ),
                ),
                (
                    "entry_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        verbose_name="Eintrags-Hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sicherheitsprotokoll-Eintrag",
                "verbose_name_plural": "Sicherheitsprotokoll",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="security_audit_created"),
                    models.Index(
                        fields=["user_ref", "created_at"],
                        name="security_audit_user_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("seq__isnull", False)),
                        fields=("seq",),
                        name="uniq_security_audit_seq",
                    )
                ],
            },
        ),
    ]
