# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 6.1.1 on 2026-09-26 18:13
"""
Zugangstoken nur als Hash speichern (apps/common/tokens.py).

Bestätigungslinks der Selbstregistrierung und Geräte-Tokens stehen ab jetzt nur als SHA-256-Hash in
der Datenbank. Die Migration hasht den vorhandenen Klartext; bereits verschickte Links funktionieren
weiter, weil die Anwendung das Token aus dem Link ebenso hasht.

Bestätigungslinks: Werte, die schon wie ein Hash aussehen (64 Hex-Zeichen), bleiben unverändert – die
Migration ist damit wiederholbar. Geräte-Tokens wurden mit ``token_hex(32)`` erzeugt und haben dieselbe
Form wie ein Hash; sie werden deshalb ausnahmslos gehasht (einmalig, es gibt keinen Schreibpfad, der
währenddessen neue anlegt).

Rückwärts bleibt der Hash stehen: Eine ältere Version findet die Links dann nicht mehr, sie laufen ins
Leere statt in einen Fehler.
"""

import hashlib
import re

import apps.common.tokens
from django.db import migrations, models

HASH_FORM = re.compile(r"[0-9a-f]{64}")


def _hash(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _hash_column(model, field: str, *, skip_hash_form: bool) -> None:
    changed = []
    for pk, value in list(model.objects.values_list("pk", field)):
        if not value or (skip_hash_form and HASH_FORM.fullmatch(value)):
            continue
        changed.append(model(pk=pk, **{field: _hash(value)}))
    model.objects.bulk_update(changed, [field], batch_size=500)


def hash_tokens(apps, schema_editor):
    _hash_column(apps.get_model("accounts", "EmailVerificationToken"), "token", skip_hash_form=True)
    _hash_column(apps.get_model("accounts", "TrustedDevice"), "device_token", skip_hash_form=False)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_sicherheitsprotokoll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.CharField(
                default=apps.common.tokens.unusable_token_hash,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="Token (SHA-256)",
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="device_token",
            field=models.CharField(
                default=apps.common.tokens.unusable_token_hash,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="Geräte-Token (SHA-256)",
            ),
        ),
        migrations.RunPython(hash_tokens, migrations.RunPython.noop),
    ]
